- Projects/Embark/Sources/EmbarkStore.swift
We weren't parsing and/or conditions correctly which lead to the isYouth question always appearing even though the eligibility criteria wasn't met, also noticed that we weren't using the `getValue` method meaning that `computedStoreValues` wouldn't be calculated correctly so fixed that aswell.
> [APP-315] Clean up expression logic and parse and or conditions correctly

- Projects/Embark/Sources/Viewables/Actions/EmbarkInput.swift
- Projects/Embark/Sources/Viewables/Actions/TextAction/EmbarkTextAction.swift
- Projects/Embark/Sources/Viewables/Actions/TextActionSet.swift
- Projects/hCore/Sources/Masking.swift
- Fix spaces not rendering, see link for why this thing happens 🙃 
https://stackoverflow.com/questions/19569688/right-aligned-uitextfield-spacebar-does-not-advance-cursor-in-ios-7/20129483#20129483
[APP-335]: https://hedvig.atlassian.net/browse/APP-335
> [APP-335] Add MaskType.none that handles only spaces

- Projects/Market/Sources/MarketPicker.swift
- Adjust welcomeLabel when verticalSizeClass is compact
[APP-350]: https://hedvig.atlassian.net/browse/APP-350
> Adjust welcomeLabel when verticalSizeClass is compact

- Projects/Embark/GraphQL/InsuranceProviders.graphql
- Projects/Embark/Sources/Viewables/Actions/InsuranceProviderAction/InsuranceProviderAction.swift
- Add `other` insurance option (this one doesn't insert into the store) it just notifies the user that we can't perform the move for them
[APP-341]: https://hedvig.atlassian.net/browse/APP-341
> Add `other` insurance option

- Projects/Embark/Sources/EmbarkPlans.swift
- Projects/hCoreUI/Sources/GradientView.swift
- Fix GradientView not rerendering correctly when bounds change
[APP-354]: https://hedvig.atlassian.net/browse/APP-354
> Fix GradientView not rerendering correctly when bounds change

- Projects/Payment/Sources/Screens/Adyen/AdyenPayIn.swift
- Fix `payInMethodStatus` after setting up Adyen
[APP-121]: https://hedvig.atlassian.net/browse/APP-121
> Fix `payInMethodStatus` after setting up Adyen

- Projects/Embark/Sources/Viewables/Actions/Action.swift
- I think `systemLayoutSizeFitting` doesn't seem to work for UIDatePicker so we need to use frame here instead. I think we can always use the bigger of the two. 
[APP-548]: https://hedvig.atlassian.net/browse/APP-548
> App 548 date picker animation

- Projects/App/Sources/Screens/DebugScreen/Debug.swift
App got stuck during App Store review because the environment picker got placed under the navigation bar for some reason, we should just rewrite this screen to `hForm` later I think. Doing a simple fix for now.
> Add naive padding to Wizard

- Projects/Contracts/Example/Sources/Debug.swift
- Projects/Contracts/Sources/View/CrossSellingItem.swift
- Projects/Contracts/Sources/View/CrossSellingSigned.swift
- Projects/hCoreUI/Sources/hButton/hButton.swift
- Projects/hGraphQL/GraphQL/ActiveContractBundles.graphql
- Projects/hGraphQL/Sources/Models/CrossSellModels.swift
> Use typeOfContract as fingerprint for cross selling notification, also fix `.hButtonFilledStyle` not being applied on iOS 14.
[APP-790]: https://hedvig.atlassian.net/browse/APP-790
> Use typeOfContract as fingerprint for cross selling notification

- Projects/App/Sources/Journeys/ClaimsJourney.swift
Fix claim status polling never stopping
- Add new `sendActionOnDismiss`
> trigger action before dismissing

- Projects/Home/Example/Sources/Debug.swift
- Projects/Home/Sources/Viewables/TerminatedSection.swift
- Projects/Home/Testing/HomeTestingData.swift
- Added the correct action to `Terminated Section` for claims.
- Updated the home example to have a `Terminated` state.
[APP-1180]: https://hedvig.atlassian.net/browse/APP-1180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APP-1180] terminated member claim bug

- Projects/Contracts/Sources/Contracts.swift
- Projects/Contracts/Sources/View/ContractTable.swift
- Make sure terminated insurances are shown as cards when there are no active contracts.
[APP-1132]: https://hedvig.atlassian.net/browse/APP-1132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> APP-1132 Fix terminated contracts row

- Projects/Offer/Sources/Components/MainContentForm/Sections/Coverage/FrequentlyAskedQuestionsSection.swift
- Projects/Payment/Sources/Screens/Adyen/AdyenSuccess.swift
- Projects/hCoreUI/Sources/ImageTextAction.swift
- Make center-aligned sucess screen left-aligned (and in the process add an alignment option to ImageTextAction)
- Fix arrow sometimes being compressed in FAQ table
[APP-1395]: https://hedvig.atlassian.net/browse/APP-1395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-1401]: https://hedvig.atlassian.net/browse/APP-1401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UI fixes II

- Projects/App/Sources/Journeys/LoginJourney.swift
- Projects/App/Sources/Screens/LoginScreen/BankIDLoginQR.swift
- Projects/App/Sources/Screens/LoginScreen/BankIDLoginSweden.swift
- Changes to an alternative Login button on `BankIDSweden` page to choose between E-mail and bankID on another device.
- Adds email button on `BankIDQRCode` page to start generic auth
[APP-1659]: https://hedvig.atlassian.net/browse/APP-1659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Start generic auth from bank id pages

- Projects/App/Sources/Screens/ChatScreen/Reusables/Message+Reusable.swift
> Fixes height calculation for new font also found a bug where some labels disappeared so changed some logic so that messages appear correctly
[APP-1684]: https://hedvig.atlassian.net/browse/APP-1684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix height calculation for new font + fix labels disappearing

- Projects/App/Sources/Journeys/LoggedInJourney.swift
- Projects/hGraphQL/GraphQL/Claims.graphql
- Projects/hGraphQL/Sources/Models/Claims.swift
- Fetch claims on app start up. Will be needed going forward for account deletion to check active claims.
- For some reason, the status of claims was always being stored as .none 🤯. It now reads and updates the status properly.
[APP-1768]: https://hedvig.atlassian.net/browse/APP-1768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Read claims' status and fetch claims on startup

- Projects/Contracts/Sources/View/CrossSellingItem.swift
Adding contentShape so that the button gets the correct tap area, else it grows outside of it 🤷‍♂️ 
[APP-1787]: https://hedvig.atlassian.net/browse/APP-1787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add contentShape to CrossSellingItem button

- Projects/hCoreUI/Sources/RemoteVectorIcon.swift
- The `RemoteVectorIcon` doesn't update on changing from light to dark and vice-versa. The check for imageView's size returns and doesn't let the icon render again.
[APP-1476]: https://hedvig.atlassian.net/browse/APP-1476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove the check which doesn’t let icons update on changing traits

- Projects/Home/Sources/Viewables/FutureSection.swift
- Projects/Home/Sources/Viewables/TerminatedSection.swift
- Projects/hCoreUI/Sources/Styling/TextStyle.swift
> Set title to prominent in some home sections
[APP-1792]: https://hedvig.atlassian.net/browse/APP-1792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Set title to prominentTitle in some home sections

- Projects/App/Sources/Journeys/LoggedInJourney.swift
- Projects/App/Sources/UgglanStore.swift
- Validate auth token and logout the member if the token is found to be invalid
[APP-1756]: https://hedvig.atlassian.net/browse/APP-1756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Validate auth token on app startup

- Projects/Contracts/Sources/Screens/ContractDetail.swift
- Projects/hCoreUI/Sources/InsurableLimits/InsurableLimits.swift
When the text in the rows under `Insurable Limits` has many characters, it is causing the whole screen to render with an unwanted offset. This was the reason behind the increase in size of the contract card under Qasa.
The fix includes adding a `fixedSize(horizontal: false, vertical: true)` modifier that now renders the text in multiple lines instead of truncating it.
- removed a `VStack` that wraps a `hForm`.
- Removed `UIKit` implementation of `InsurableLimitsSection`
[APP-1622]: https://hedvig.atlassian.net/browse/APP-1622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix bug for insurable limits text size

- Projects/App/Sources/Journeys/ClaimsJourney.swift
- Projects/App/Sources/Journeys/LoggedInJourney.swift
- Projects/App/Sources/UgglanStore.swift
- Projects/Claims/Sources/ClaimState.swift
- Projects/Claims/Sources/CommonClaims/CommonClaimDetail.swift
- Projects/Claims/Sources/Views/ClaimSectionLoading.swift
- Projects/Claims/Sources/Views/ClaimsInfoPager.swift
- Projects/Home/Sources/HomeState.swift
- Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift
- `ClaimsOrigin` to encapsulate all the data that will be sent to Odyssey
- Removes unused code for `openClaim` action in `HomeStore` and `openClaims` action in `UgglanStore`
[CLX-167]: https://hedvig.atlassian.net/browse/CLX-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Pass initial data from app to Odyssey

- Projects/Claims/Sources/CommonClaims/CommonClaimDetail.swift
- Projects/hCoreUI/Sources/PerilCollection/PerilDetail.swift
- Removed peril icons to match design
https://www.figma.com/file/qUhLjrKl98PAzHov9ilaDH/*NEW*-.com-UI-Kit?node-id=1685-7405&t=x53wrpFiNSVZ7Nst-0
[CLX-394]: https://hedvig.atlassian.net/browse/CLX-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CLX-394: Update Peril Design

- Projects/App/Sources/Generic/Extensions/NSFileCoordinator+Flow.swift
Apparently we need to call `url.startAccessingSecurityScopedResource()` before starting to read the data at the URL else it won't do it, how this worked in the past is a mystery to me 🤸‍♂️
> Fix file uploads

- Projects/App/Sources/Screens/ClaimsScreen/Screens/ClaimFlowAskForPushnotifications.swift
- Projects/Claims/Sources/Views/SubmitClaim/AudioRecording/SubmitClaimAudioRecordingScreen.swift
- Ask for notification button spacing
- Continue button shows a little bit after we press record again on audio recording screen
> Added spacing for notifications; fixed issue with recording audio layout

- Projects/Offer/Sources/OfferStore.swift
- Projects/hCore/Sources/Array+Unique.swift
- Added unique to quoteCart_startCheckout mutation
We got report that moving flow is out of order.
https://hedviginsurance.slack.com/archives/CPCUHMMJQ/p1682081269778709
After analysing the issue we found out that we are sending same value 2 times on requestQuoteCartSign mutation.
To avoid this, I have added unique for this before sending this mutation.
This is fast solution that should fix issue.
> Added unique to quoteCart_startCheckout

- Projects/App/Sources/Journeys/LoggedInJourney.swift
[https://www.notion.so/hedviginsurance/Opening-a-chat-notification-takes-the-member-to-the-Home-tab-instead-of-the-chat-4a0bc613c12a40608b3c5330c6ac10dc](url)
Issue was that tabController wasn't loaded and therefore action openChat was't called
- Fixed issue with running app from the notifications
> Fixed issue with starting app from notificaiton

- Projects/Claims/Sources/Views/ClaimStatus.swift
- Fix bug with claim card not opening if only one claim
> fixed issue with claim card not opening if only one

- Projects/App/Sources/Screens/SettingsScreen/SettingsScreen.swift
- open settings for language picker
- ask for notification permission or open settings for notifications
> GEN-785:Added notifications and language to settings screen

- Projects/hCoreUI/Sources/Toasts.swift
- Projects/hCoreUI/Sources/Views/SuccessScreen.swift
- Projects/hCoreUI/Sources/Views/TextInputView.swift
- Projects/hCoreUI/Sources/hForm/hFloatingTextField.swift
- Updated toaster height
- Removed first responder on text field for change code
- Updated clear button on text field so it doesn't flicker anymore
- Moved success screen inside change your code
> Feature/app redesign/forever fixes

- Projects/App/Sources/Screens/ChatScreen/Chat.swift
- Projects/App/Sources/Screens/ClaimsScreen/Screens/ClaimFlowAskForPushnotifications.swift
- Projects/App/Sources/Screens/ClaimsScreen/Screens/HonestyPledge.swift
- Fixed honesty pledge crash (same for notifications permission)
> Fixed crash on honesty pledge when dismissed (happens offten)

- Projects/Market/Sources/Screens/NotLoggedIn/NotLoggedViewModel.swift
- Login screen not showing since
onLoad() doesn't get called after removing of detectMarket
> Fix for login screen not showing

- Projects/Claims/Sources/Views/SubmitClaim/SummaryInfo/SubmitClaimSummaryScreen.swift
- Projects/hCoreUI/Sources/HedvigColors.swift
- Projects/hCoreUI/Sources/Styling/DefaultStyling.swift
- remove go back button on summary screen
- date picker color fix
> GEN-1338-remove go back buttton on summary screen and fix date picker color

- Projects/Contracts/Sources/Stores/ContractState.swift
- Projects/Contracts/Sources/View/CoInsured/AlreadyExistingCoInsured/InsuredPeopleScreen.swift
- Projects/Contracts/Sources/View/CoInsured/CoInsuredSelectScreen.swift
- Added possibility to reuse already existing co-insured for other contracts when updating your co-insured
> add possibility to select already entered co-insured for other contracts

- Projects/Contracts/Sources/Journeys/EditCoInsuredJourney.swift
- Projects/Contracts/Sources/View/CoInsured/CoInsuredSelectScreen.swift
- Fixed UI issue when wants to add new co insured. Steps
1. You have already added co insured to one contract
2. In another contract you want to add new co insured
3. Screen with already added co insured popup but you want to add new co insured
4. you go back - screen get splashed
https://github.com/HedvigInsurance/ugglan/assets/127749787/7b25a7b0-0400-4b26-a825-d3722bc72722
y added coinsured
> Fix squished flow on add new co insured

- Projects/Contracts/Sources/Models/CoInsuredModel.swift
- Projects/Contracts/Sources/Models/ContractModels.swift
- Projects/Contracts/Sources/View/CoInsured/CoInusuredInput.swift
- Projects/Contracts/Sources/View/CoInsured/EditCoInsuredDisplayFields.swift
- Projects/hCore/Sources/Date+LocalDateString.swift
- Projects/hCore/Sources/Masking.swift
- Projects/hCore/Sources/UIApplication+GetTopViewController.swift
- Projects/hCoreUI/Sources/hForm/hDatePickerField.swift
- Tuist/Config.swift
- Added datepicker list for birth date instead of typing in text
- [Figma](https://www.figma.com/file/WlwFCAWywXNcXVgPfYVmWu/Final-Design?node-id=6900%3A10499&mode=dev)
> add datepicker list for birth date instead of typing in text

- Projects/Contracts/Sources/Journeys/EditCoInsuredJourney.swift
- Fixed showing "Input view" when not neede
> Added fix not to show "Input view" when not needed

- Projects/Contracts/Sources/Journeys/ContractInformation.swift
- Projects/Contracts/Sources/View/CoInsured/AlreadyExistingCoInsured/InsuredPeopleScreen.swift
- Projects/Contracts/Tests/EditCoInsuredTests.swift
- Redirect directly to edit co-insured if it's the only option
> redirect directly to edit coinsured if moving flow is off

- Projects/App/Sources/AppDelegate+hAnalytics.swift
- Projects/App/Sources/AppDelegate.swift
Reintroduced hAnalytics on app start since we need to check for app version
> Returned hAnalytics on app start

- Projects/EditCoInsured/Sources/Journeys/EditCoInsuredJourney.swift
- Fixed issue with dismissing journey on canceling editing co insured
- Added alert when trying to dismiss edit co insured (pressing "X" on top)
> Edit co insured journey

- Projects/Home/Sources/Screens/HelpCenter/HelpCenterStartView.swift
- Projects/Home/Sources/Screens/HelpCenter/ReusableComponents.swift
- Projects/TerminateContracts/Sources/Views/ReusableComponents.swift
- Projects/hCoreUI/Sources/hForm/hSection.swift
- iPad fix for help center (hSection)
> fix for iPad padding in help center

- Projects/Chat/Sources/Views/ChatScreen.swift
- fix ChatInputView being cut off/missing padding on iPad
> fix ChatInputView being cut off/missing padding on iPad

- .github/workflows/ProductionDeploy.yml
Create the `.netrc` file which contains the right credentials to be able to download authlib which is behind authentication, just like we have to do on our local machines to be able to build the project
> Try to create the .netrc file for the CI runner

- Projects/Claims/GraphQL/Octopus/StartClaimsFlow.graphql
- Projects/Claims/Sources/ClaimMutation+Actions.swift
- Projects/Claims/Sources/Models/FlowClaimDeflectStepModel.swift
- Projects/Claims/Sources/Views/SubmitClaim/Deflect/SubmitClaimDeflectScreen.swift
- Projects/Claims/Sources/Views/SubmitClaim/Subviews/ClaimContactCard.swift
- Add deflect model for towing.
- Some design edits. Added info button which we had on design but didn't add before.
- [Figma](https://www.figma.com/file/LlJgc0axJygj5FxLdYgevj/Car-Claims-2024?type=design&node-id=3701-1558&mode=design&t=9mha49QYCyauC45j-0)
> GEN-1889: Towing deflect screens

- Projects/Contracts/Sources/ContractsTabBarItemConfiguration.swift
- Projects/Home/Sources/Screens/Home.swift
- Projects/hCore/Sources/DeepLink.swift
Context:
https://hedviginsurance.slack.com/archives/C05TQ9TFQ6M/p1710850325979789?thread_ts=1710844864.449339&cid=C05TQ9TFQ6M
Should work when CI pulls the latest strings from lokalise.
They live here https://app.lokalise.com/project/743091915e9da969db9340.20943733/?view=multi&filter=tag_fd9160bbd656f75ab74e8935e4330d9e
> Use consistent L10n for tab names

- Projects/App/Sources/Journeys/ClaimsJourney.swift
- Projects/App/Sources/Journeys/LoggedInJourney.swift
- Projects/Claims/Sources/Claims.swift
Looking at [graphQL metrics](https://studio.apollographql.com/graph/Octopus-fxevz/variant/production/clients?clientName=iOS%3Acom.hedvig.app&clientVersion=12.4.14) we are calling too ofter for claims. Lets rework it a little bit so we don't call it so often. 
Lets move to call them every 60s and see how that will work.
- Removed calling fetchClaims when the app starts
- Added fetch claims when we finish with submit claims flow
- Reworked how and when we fetchClaims
> Updated how often we call for claims

- Projects/App/Sources/AnalyticsCoordinator.swift
- Projects/App/Sources/AppDelegate+DI.swift
- Projects/App/Sources/AppDelegate+Tracking.swift
- Projects/App/Sources/AppDelegate.swift
- Projects/App/Sources/Journeys/LoggedInJourney.swift
- Projects/App/Sources/Journeys/LoginJourney.swift
- Projects/Authentication/Sources/SEBankID/BankIDLoginQRView.swift
- Projects/Home/Sources/HomeState.swift
- Projects/hCore/Sources/ApplicationContext.swift
- Projects/hGraphQL/Sources/TokenRefresher.swift
We had strange handling of demo mode and now we are removing some flags so now we have clearer handing of demo mode.
Also we were setting memberId only after we fetch it from the service, now we set it immediately after we init DataDog ( if available from the profile store)
- Removed isDemoFlag from TokenRefresher
- Upgraded and renamed hAnalyticsCoordinator to AnalyticsService 
- Removed isDemoMode from context ApplicationContext
> Updated demo logic + analytics service

- Projects/App/Sources/AppDelegate+Deeplinks.swift
- Projects/App/Sources/Journeys/LoggedInJourney.swift
- Projects/Home/Sources/Screens/HomeBottomScrollView.swift
- Projects/Payment/GraphQL/Octopus/PaymentInformation.graphql
- Projects/Payment/Sources/Models/PaymentStatusData.swift
- Projects/Payment/Sources/PaymentStore.swift
- Projects/Payment/Sources/Screens/ConnectPayments/ConnectPaymentCard.swift
- Projects/Payment/Sources/Screens/ConnectPayments/DirectDebitSetup.swift
- Projects/Payment/Sources/Screens/PaymentsView.swift
- Projects/Payment/Sources/Services/PaymentService/PaymentServiceDemo.swift
- Projects/Payment/Sources/Services/PaymentService/PaymentStatusData+octopus.swift
- Projects/hCore/Sources/DeepLink.swift
- Added new payment statuses: noNeedToConnect and contactUs
- noNeedToConnect status when we dont have any active and pending contracts
- contactUs when we have termination reason because of missed payments
- Changed GraphQL query for payment status
- Added open-chat deep link so we can open it on the top wherever we are located in the app
[Notion](https://www.notion.so/hedviginsurance/a4c35052b6794b36a4b0d58b537cc325?v=c74a8cb958ab4ba6ba4c904d8540b106&p=2b2316d35ab34dcea505aea7fb07bcbd&pm=s)
No Figma
> GEN-1993-added-missed-connect-payments

- Projects/Claims/Sources/Views/SubmitClaim/AudioRecording/SubmitClaimAudioRecordingScreen.swift
- Prevent device to go asleep when audio step is presented
> Disable device sleep on audio step

- Projects/EditCoInsured/Sources/Navigation/EditCoInsuredNavigation.swift
- Projects/EditCoInsured/Sources/Stores/EditCoInsuredStore.swift
- Projects/EditCoInsured/Sources/View/EditCoInsured+modifier.swift
- Projects/EditCoInsuredShared/Sources/Models/EditCoInsuredViewModel.swift
- Projects/hCoreUI/Sources/DetentRouter.swift
- Projects/hCoreUI/Sources/ModallyRouter.swift
- Removed replaceCurrent - source of issues
- Reworked navigations for easier handing of whats going on
Steps to reproduce on the current main:
1. Add home and accident insurances with co insured
2. Add one insurance co insured
3. Alert will popup saying another insurance is missing co insured
4. After adding co insured the edit co insured navigation doesn't dismiss
That navigation in step 4 should dismiss now
> Fixed edit co insured navigation not dismissing

- Projects/Payment/Sources/Models/PaymentStatusData.swift
- Changed bank account button when user has failed payment
> GEN-2461: Updated change bank account button in PaymentsView

- Projects/Payment/Sources/Screens/PaymentDiscounts/PaymentsDiscountsView.swift
- Fixed the padding between the monthly discount and referral information for members without referrals.
> Added padding for empty refferal lists

- Projects/Profile/Sources/Views/Screens/AppInfo/AppInfoView.swift
- Projects/hCoreUI/Sources/hForm/hRow.swift
- Fixed a minor bug where the device ID was top aligned instead of being vertically centered
> Changed alignment of hRow to fix Device ID alignment

- Projects/EditCoInsured/Sources/View/AlreadyExistingCoInsured/InsuredPeopleScreen.swift
- Projects/EditCoInsured/Sources/View/CoInusuredInput.swift
Add/remove co insured localy only when we get intentId from the service
How it used to work:
1. App delete/add co insured
2. Request to the service is sent
3. If the request fails, we don't get intent id and the local list is off
How it works now:
1.  We send request for the intent
2. When we get response from the service, we remove/add co insured to the local list
> GEN-2498 fix issue when sending empty intentId on edit co insured

- Projects/App/Sources/Journeys/LoggedInNavigation.swift
- Projects/App/Sources/Journeys/MainNavigationJourney.swift
Wait for the feature flags before executing notification (only when running app from the notification)
Some push notifications depend on the feature flags, so when opening app from the notification which depends on the feature flags would cause odd behaviour, checking if the feature flags are fetched is added.
> Check for feature flags before executing notification

- Projects/Contracts/Sources/Journeys/ContractInformation.swift
Showing insurance details when having upcoming reviewal.
How it looked before:
> GEN-2504: Fixed issue with not showing contract details in some cases

- Projects/Contracts/Sources/View/ContractRow.swift
According to the [figma](https://www.figma.com/design/5kmmDdh6StpXzbEfr7WevV/Hedvig-UI-Kit?node-id=15991-41631&node-type=FRAME&t=BZtZ5PCHYlJhDZpm-0), we need to show statuses for the active insurance
> Added active status for the insurance

- Projects/ChangeTier/Sources/Navigation/ChangeTierNavigation.swift
- Projects/ChangeTier/Sources/Views/ChangeTierLandingScreen.swift
- Projects/ChangeTier/Sources/Views/CompareTierScreen.swift
- Projects/hCoreUI/Sources/Views/ScrollableSegmentedView.swift
- Update button and title on comparison screen to be "show coverage" if we only have one tier
- Make selected tier preselected in comparision table
> Fixes for change tier comparision screen

- Projects/ChangeTier/Sources/Service/OctopusImplementation/ChangeTierClientOctopus.swift
Matching tier wasn't working and its not smart to have currentDeductible if we don't have current tier, so better leave it empty instead populating it
- setting current tier
- setting current deductible
> Fixed issue with setting currentTier and currentDeductible

- Projects/ChangeTier/Sources/Views/ChangeTierLandingScreen.swift
- Projects/ChangeTier/Sources/Views/ChangeTierProcessingScreen.swift
- Projects/EditCoInsured/Sources/View/CoInusuredInput.swift
- Projects/TerminateContracts/Sources/Views/SetTerminationDateLandingScreen.swift
- Projects/hCoreUI/Sources/Views/Dropdown.swift
- Projects/hCoreUI/Sources/hForm/hFieldBackground.swift
- Projects/hCoreUI/Sources/hForm/hFloatingField.swift
- Projects/hCoreUI/Sources/hForm/hFloatingTextField.swift
> Fx background field color and refactor environment variables

- Projects/App/Sources/Journeys/LoggedInNavigation.swift
- Projects/ChangeTier/Sources/Navigation/ChangeTierNavigation.swift
- Projects/ChangeTier/Sources/Views/ChangeTierSummaryScreen.swift
- Projects/ChangeTier/Sources/Views/ChangeTierViewModel.swift
- Projects/Contracts/Sources/ContractsNavigation.swift
- Projects/Contracts/Sources/Journeys/ContractDocuments.swift
- Projects/Contracts/Sources/Journeys/ContractInformation.swift
- Projects/Home/Sources/Components/RenewalCard.swift
- Projects/Home/Sources/Navigation/HomeNavigation.swift
- Projects/MoveFlow/Sources/MovingFlowNavigationViewModel.swift
- Projects/MoveFlow/Sources/View/MovingFlowConfirm.swift
- Projects/TravelCertificate/Sources/TravelCertificateNavigation.swift
- Projects/hCore/Sources/Models/ProductVariant.swift
- Projects/hCoreUI/Sources/Document.swift
- Projects/hCoreUI/Sources/Views/InsuranceTermView.swift
- Projects/hCoreUI/Sources/Views/QuoteSummaryScreen.swift
- Projects/hGraphQL/Sources/Models/PDFDocument.swift
- Projects/hGraphQL/Sources/Models/hPDFDocument.swift
- I have really been confused about those Insurance Terms and Documents since they contain the same thing. I therefore decided to remove Document and only use InsuranceTerm.
> Replace Document with InsuranceTerm to use same one

- Projects/App/Sources/Journeys/LoggedInNavigation.swift
- Projects/EditCoInsured/Sources/Navigation/EditCoInsuredNavigation.swift
- Projects/EditCoInsured/Sources/View/AlreadyExistingCoInsured/InsuredPeopleScreen.swift
- Projects/EditCoInsured/Sources/View/CoInsuredErrorScreen.swift
- Projects/EditCoInsured/Sources/View/CoInsuredProcessingScreen.swift
- Projects/EditCoInsured/Sources/View/CoInsuredSelectScreen.swift
- Projects/EditCoInsured/Sources/View/CoInusuredInput.swift
- Projects/EditCoInsured/Sources/View/EditCoInsured+modifier.swift
- Projects/EditCoInsured/Sources/View/NewCoInsured/InsuredPeopleNewScreen.swift
- Projects/EditCoInsured/Sources/View/NewCoInsured/RemoveCoInsuredScreen.swift
- Updated what is observed and how to access properties and updated view when they change
- For example "Add co-insured" never actually reflected loading state
> Improvement/edit coinsured/remove store suggestions

- Projects/App/Sources/Journeys/LoggedInNavigation.swift
- Projects/App/Sources/Journeys/MainNavigationJourney.swift
- Handle deeplink after successful login instead immediately 
Why?
Some deeplinks will not work because of missing data
> Updated logic to check deeplink after login

- Projects/ChangeTier/Sources/Views/ChangeTierSummaryScreen.swift
- We are not supposed to show info button for addons when doing change tier
> Removed info for addons when changing tiers

- Projects/hCore/Sources/FeatureFlags/FeatureFlagOctopus.swift
- Changes in the unleash flags caused crash
- Having [ongoing issue](https://github.com/Unleash/unleash-proxy-client-swift/issues/98) with the unleash team
> Fixed crash caused by unleash update

- Projects/App/Config/Production/Hedvig.entitlements
- Projects/App/Config/Test/Ugglan.entitlements
- Projects/App/Sources/Journeys/LoggedInNavigation.swift
- Projects/Home/Sources/Models/HelpCenterModel.swift
- Projects/TerminateContracts/Sources/Navigation/TerminationFlowNavigationViewModel.swift
- Projects/hCore/Sources/DeepLink.swift
- Projects/hCore/Sources/String+isDeepLink.swift
- Projects/hGraphQL/Sources/Environment.swift
- Added support for deeplink for dev.hedvigit.com/deeplink/ for stage and www.hedvig.com/deeplink/
Ugglan:
https://hedvigtest.page.link/forever -> should open the app
https://dev.hedvigit.com/deeplink/forever -> should open the app
https://dev.hedvigit.com/forever -> should open web
Hedvig:
https://hedvig.page.link/forever -> should open the app
https://www.hedvig.com/deeplink/forever -> should open the app
https://www.hedvig.com/forever -> should open web
Since we recently added  .well-known to our web sometimes it doesn't work until the app is deleted and the phone is restarted. So in the case its not working thats what needs to be done. I am preatty sure that apple reset this when new version is released and check for new associated domains so release should be fine
> GEN-3215: Add support for deeplinks from hedvig

- Projects/App/Sources/Journeys/LoggedInNavigation.swift
- Projects/Claims/Sources/Views/ClaimDetailView.swift
- Projects/Home/Sources/Navigation/HomeNavigation.swift
- reworked logic for open terms in claim details
- crash happened when you enter claim details from the conversation and try to open terms
-  [datadog crash ](https://app.datadoghq.eu/rum/sessions?query=%40type%3Aerror%20%40application.id%3A416e8fc0-c96a-4485-8c74-84412960a479%20%40error.is_crash%3Atrue&agg_m=count&agg_m_source=base&agg_t=count&cols=&event=AwAAAZTLKqxIRhcwoAAAABhBWlRMS3dJTEFBQUFxMkF5QzFvdVRRQUIAAAAkMDE5NGNiMzEtNTI4My00ZTVhLWJhM2ItY2ZlYWI5NjQ0NGYzAAAIvQ&fromUser=false&track=rum&viz=stream&from_ts=1738493280166&to_ts=1738579680166&live=true)
> Fixed crash when opening terms on claim details

- Projects/Chat/Sources/Views/ChatInputView.swift
- Adding some additional delay should fix it.
> Missing last character in the chat when sending a mesage

- Projects/EditCoInsured/Sources/View/CoInsuredProcessingScreen.swift
- Projects/EditCoInsuredShared/Sources/Models/EditCoInsuredViewModel.swift
When checking for insurances that have missed co-insured, exclude insurance that has been updated at a moment of checking.
> CoInsured: Exclude alert check for updated contract

- Projects/hCoreUI/Sources/Views/ProcessingStateView.swift
- Fix height of processing screen to be same as success and error screen
- [This bug task ](https://www.notion.so/hedviginsurance/Addons-E2E-test-18fc3f71cb0a80a797f7e4bc3c85974b?p=18fc3f71cb0a814ca33dd2aef0191273&pm=s)from addon test session
> Fix loading view to be same height as success and error screen

- Projects/Addons/Sources/Views/ConfirmChangeAddonScreen.swift
- Projects/ChangeTier/Sources/Navigation/ChangeTierNavigation.swift
- Projects/ChangeTier/Sources/Views/ChangeTierSummaryScreen.swift
- Projects/ChangeTier/Sources/Views/ConfirmChangeTierScreen.swift
- Projects/hCoreUI/Sources/Views/ConfirmChangesScreen.swift
- Added confirmation step before committing tier change
- Made this view generic to be reused for addons and maybe other places in the future
- [Figma](https://www.figma.com/design/SNVLvLq7ztclXiDqqMNXgY/Tiers-%26-Addons-(App)?node-id=3345-32241&p=f&t=lKG4NKkeptejJgEH-0)
> GEN-3279: add ConfirmChangeTierScreen

- Projects/Home/Sources/Service/OctopusImplementation/HomeClientOctopus.swift
- Moved address to quick actions and removed from edit insurance in help center
- [Figma](https://www.figma.com/design/zItETkT4mu5ANVDYED5gEm/Retention-UX-Improvements-App?node-id=5-8974&t=iDNAaZcU3PVEKdCR-0)
> GEN-3287: Move address to quick actions

- Projects/Contracts/Sources/ContractsNavigation.swift
- Projects/Contracts/Sources/Stores/ContractAction.swift
- Projects/Contracts/Sources/View/ContractInformation.swift
- Updated buttons for moving and cancellation in insurance details. Switched places.
- [Figma](https://www.figma.com/design/zItETkT4mu5ANVDYED5gEm/Retention-UX-Improvements-App?node-id=5-12340&t=iDNAaZcU3PVEKdCR-0)
> GEN-3289: Update moving/cancellation buttons in insurance details

- Projects/ChangeTier/Sources/Navigation/ChangeTierNavigation.swift
- It happens that we are missing contracts when opening change tier
This happens if we open deeplink https://hedvig.page.link/change-tier and we don't have any contracts
This is a quick fix, have a nice bottom sheet instead
> Added error screen if we end up on screen without any contracts

- Projects/hCoreUI/Sources/Peril/Accordion.swift
- Projects/hCoreUI/Sources/Peril/PerilCollection.swift
- Remove number if we only have one cover item
> remove number if perilCover is only one

- Projects/Addons/Sources/Views/ChangeAddonViewModel.swift
- Projects/Contracts/Sources/View/ContractTable.swift
BE should immediately give us a new contract info when adding addon, but it happens that it take some time sometimes so adding delay to refresh after 1s. Also we have success screen anyway so it will not create any confusion for the member
> Added small delay when adding addon since BE can take some async time

- Projects/TerminateContracts/GraphQL/Octopus/TerminationStartFlow.graphql
- Projects/TerminateContracts/Sources/Models/TerminationFlowSurveyStepModel.swift
- Projects/TerminateContracts/Sources/Service/OctopusImplementation/TerminateContractsClientOctopus.swift
- Projects/TerminateContracts/Sources/Views/TerminationSurveyScreen.swift
- Projects/hCore/Sources/DeepLink.swift
- Updated design in termination survey flow for suggestions (info cards)
- We want to use both campaign (green) and info cards (blue) and have with and without buttons
- [Figma](https://www.figma.com/design/zItETkT4mu5ANVDYED5gEm/Retention-UX-Improvements-App?node-id=27-4697&t=iDNAaZcU3PVEKdCR-0)
##Blockers
- Waiting for graphQL implementation on backend
> GEN-3291: New design for suggestion cards in termination survey

- Projects/Addons/Sources/Navigation/ChangeAddonNavigation.swift
- Projects/Addons/Sources/Views/AddonSelectInsuranceScreen.swift
- Select insurance for addons didn't work, fixed in this PR
how to test: replace following code inside `ChangeAddonNavigation` when starting any addon flow
```
public init(
input: ChangeAddonInput
) {
self.changeAddonNavigationVm = .init(input: input)
}
```
with
```
public init(
input: ChangeAddonInput
) {
var testConfig = input.contractConfigs ?? []
testConfig.append(.init(contractId: "test", exposureName: "exp", displayName: "dis"))
self.changeAddonNavigationVm = .init(input: .init(contractConfigs: testConfig))
}
```
and select first option and continue
> Fixed not working select insurances screen for addons

- Projects/ChangeTier/Sources/Service/OctopusImplementation/ChangeTierClientOctopus.swift
- Fix for this [issue](https://hedviginsurance.slack.com/archives/C03U9C6Q7TP/p1740041137641069)
- Deductible percentage should be set to nil if value is 0
> Set deductible percentage to nil if value is 0

- Projects/Authentication/Sources/Service/OctopusImplementation/AuthenticationClientAuthLib.swift
- Projects/hGraphQL/Sources/Apollo Extensions/ApolloClient+Fetch.swift
- Projects/hGraphQL/Sources/HeadersInterceptor.swift
- Projects/hGraphQL/Sources/TokenRefresher.swift
When member has:
- bad internet connection which causes different network related errors
- app is sent to the background and refreshing of the token is not performed
we get IOError from the authLib. This error shouldn't logout member, just show errors in the app.
[datadog](https://app.datadoghq.eu/logs?query=service%3Aios%20%22IO%20Error%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1739797756318&to_ts=1740402556318&live=true)
> Logout from the app only when error is caused by non network issues

- Projects/Payment/Sources/Models/PaymentData.swift
- Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsDiscount.swift
- Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsView.swift
- Projects/Payment/Sources/Screens/PaymentDiscounts/DeleteCampaignView.swift
- Projects/Payment/Sources/Screens/PaymentDiscounts/PaymentsDiscountsView.swift
- Projects/Payment/Sources/Service/PaymentService/DemoImplementation/PaymentClientDemo.swift
- Projects/Payment/Sources/Service/PaymentService/OctopusImplementation/PaymentData+octopus.swift
- Projects/Payment/Sources/Service/PaymentService/OctopusImplementation/PaymentDiscountData+octopus.swift
- Projects/Payment/Sources/Service/PaymentService/OctopusImplementation/PaymentHistoryData+octopus.swift
- It can happen that we get 2 discounts with the same id
Make a id that is always unique and don't depend on the id of the discount ( which is odd to have same for 2 records )
> Fixed discounts with the same code

- Projects/ChangeTier/Sources/Views/ChangeTierLandingScreen.swift
- Projects/ChangeTier/Sources/Views/CompareTierScreen.swift
- Projects/Contracts/Sources/View/ContractCoverage.swift
- Projects/Contracts/Sources/View/ContractInformation.swift
- Projects/Contracts/Sources/View/UpcomingChangesScreen.swift
- Projects/Home/Sources/Screens/HelpCenter/ReusableComponents.swift
- Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsDiscount.swift
- Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsView.swift
- Projects/Payment/Sources/Screens/PaymentDiscounts/PaymentsDiscountsView.swift
- Projects/Payment/Sources/Screens/PaymentsView.swift
- Projects/Profile/Sources/Views/Screens/AppInfo/AppInfoView.swift
- Projects/Profile/Sources/Views/Screens/Profile/Profile.swift
- Projects/hCoreUI/Sources/ToggleStyles/CheckboxToggleStyle.swift
- Projects/hCoreUI/Sources/hForm/hRow.swift
- Projects/hCoreUI/Sources/hForm/hSection.swift
- Renaming of hWithoutHorizontalPadding to hRowWithoutHorizontalPadding to make it more readable since we also have hSectionWithoutHorizontalPadding
> Rename hWithoutHorizontalPadding to hRowWithoutHorizontalPadding

- Projects/Addons/Sources/Navigation/ChangeAddonNavigation.swift
- Projects/Addons/Sources/Views/AddonSelectInsuranceScreen.swift
- Projects/ChangeTier/Sources/Navigation/ChangeTierNavigation.swift
- Projects/ChangeTier/Sources/Views/SelectInsuranceScreen.swift
- Projects/Claims/GraphQL/Octopus/StartClaimsFlow.graphql
- Projects/Claims/Sources/Navigation/ClaimsNavigation.swift
- Projects/Claims/Sources/Service/OctopusImplementation/SubmitClaimClientOctopus.swift
- Projects/Claims/Sources/Views/ModelPickerView.swift
- Projects/Claims/Sources/Views/SubmitClaim/Contracts/SelectContractView.swift
- Projects/Claims/Sources/Views/SubmitClaim/LocationView.swift
- Projects/EditCoInsured/Sources/Navigation/EditCoInsuredNavigation.swift
- Projects/EditCoInsured/Sources/View/AlreadyExistingCoInsured/InsuredPeopleScreen.swift
- Projects/EditCoInsured/Sources/View/CoInsuredSelectScreen.swift
- Projects/MoveFlow/Sources/Service/Navigation/MovingFlowNavigation.swift
- Projects/MoveFlow/Sources/View/MovingFlowAddExtraBuildingScreen.swift
- Projects/MoveFlow/Sources/View/TypeOfBuildingPickerScreen.swift
- Projects/TravelCertificate/Sources/TravelCertificateNavigation.swift
- Projects/TravelCertificate/Sources/Views/ContractsScreen.swift
- Projects/TravelCertificate/Sources/Views/TravelCertificateProcessingScreen.swift
- Projects/TravelCertificate/Sources/Views/WhoIsTravelingScreen.swift
- Projects/hCoreUI/Sources/ItemPickerScreen.swift
- Added preselected contract id
- Refactored ItemPickerScreen since it didn't save data when view dissapear
- Changed it everywhere where is needed + checked all places where its updated 🥳 
Issue was related to that every time ItemPickerScreen is rendered, new ItemConfig is created. 
Having it as a property on the view is solution where it is generated once
Its a lot
> GEN-3411: Added preselected contract id for contract step in ClaimFlow + refactor ItemPickerScreen

- Projects/App/Sources/Navigation/LoggedInNavigation.swift
- Projects/Claims/GraphQL/Octopus/ClaimAcknowledgeClosedStatus.graphql
- Projects/Claims/GraphQL/Octopus/Claims.graphql
- Projects/Claims/Sources/Models/ClaimModel.swift
- Projects/Claims/Sources/Service/DemoImplementation/FetchClaimDetailsClientDemo.swift
- Projects/Claims/Sources/Service/OctopusImplementation/FetchClaimClientOctopus.swift
- Projects/Claims/Sources/Service/OctopusImplementation/FetchClaimDetailsClientOctopus.swift
- Projects/Claims/Sources/Service/Protocols/FetchClaimDetailsClient.swift
- Projects/Claims/Sources/Views/ClaimDetailView.swift
- Projects/Claims/Sources/Views/ClaimStatus.swift
- Added `showClaimClosedFlow` and `claimAcknowledgeClosedStatus` mutation from schema
- After dismissing claim details screen, show cross sell if `showClaimClosedFlow` is true, then call `claimAcknowledgeClosedStatus`
> GEN-3389: Handle cross sell after dismissing claim details

- Projects/Claims/Sources/Models/ClaimModel.swift
- Projects/Claims/Sources/Views/ClaimStatus.swift
- Add handling of claim outcome UNRESPONSIVE
> GEN-3477: Add claim outcome unresponsive

- Projects/Addons/Sources/Views/AddonProcessingScreen.swift
- Projects/Addons/Sources/Views/ChangeAddonViewModel.swift
- Projects/App/Sources/Navigation/LoggedInNavigation.swift
- Projects/ChangeTier/Sources/Views/ChangeTierProcessingScreen.swift
- Projects/CrossSell/Sources/Models/CrossSellInfo.swift
- Projects/CrossSell/Sources/View/CrossSellingScreen.swift
- Projects/EditCoInsuredShared/Sources/Models/EditCoInsuredViewModel.swift
- Projects/Home/Sources/Navigation/HomeNavigation.swift
- Projects/Home/Sources/Screens/HomeScreen.swift
- Projects/MoveFlow/Sources/View/MovingFlowProcessingScreen.swift
- Projects/hCore/Sources/NotificationCenter+NotificationName.swift
Added cross sells after:
1. moving flow 
2. edit co insured
3. add-on flow (either add or upgrade)
4. change tier flow
> GEN-3530: Add cross sell screen for other flows

- Projects/Addons/Sources/Views/AddonProcessingScreen.swift
- Projects/Addons/Sources/Views/ChangeAddonViewModel.swift
- Projects/App/Sources/Navigation/LoggedInNavigation.swift
- Projects/ChangeTier/Sources/Views/ChangeTierProcessingScreen.swift
- Projects/CrossSell/Sources/Models/CrossSellInfo.swift
- Projects/CrossSell/Sources/View/CrossSellingScreen.swift
- Projects/EditCoInsuredShared/Sources/Models/EditCoInsuredViewModel.swift
- Projects/Home/Sources/Navigation/HomeNavigation.swift
- Projects/Home/Sources/Screens/HomeScreen.swift
- Projects/MoveFlow/Sources/View/MovingFlowProcessingScreen.swift
- Projects/hCore/Sources/NotificationCenter+NotificationName.swift
Added cross sells after:
- moving flow
- edit co insured
- add-on flow (either add or upgrade)
- change tier flow
Show cross sale only once after success flow
> Add cross sell screen for other flows

- Projects/Home/Sources/Screens/HelpCenter/ReusableComponents.swift
- Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift
- Upgraded Datadog dependency to version 25.5 in order to be compatible with Xcode 16.3
> GEN-3558: Upgrade datadog dependency version to 2.25

- Projects/hCoreUI/Sources/hForm/RadioFields/hRadioOptionField.swift
- Bug fix when radio button is disabled and not selected. Looked like all options were selected before.
- [Slack thread](https://hedviginsurance.slack.com/archives/C03U9C6Q7TP/p1744814689560039)
> GEN-3608: Fix for radio button when not selected and disabled

- Projects/TravelCertificate/Sources/Views/WhoIsTravelingScreen.swift
> GEN-3619: Bugfix for showing coinsured info card incorrect in travel certificate

- Projects/hCoreUI/Sources/Views/DocumentPreview.swift
- [Figma](https://www.notion.so/hedviginsurance/Laggy-transition-on-the-image-should-should-appear-instantly-instead-of-sliding-in-1f3c3f71cb0a80e5b263d506530477d1)
> Design fix: Make image appear instant

- Projects/SubmitClaim/Sources/Views/AudioRecording/AudioRecorder.swift
- Projects/SubmitClaim/Sources/Views/AudioRecording/SubmitClaimAudioRecordingScreen.swift
- Fixed issue with voicover being mute after stopping recording.
- https://reports.useit.se/hedvig-iosapp-may2025/problems/recording-a-clip-highjacks-the-audio-of-voiceover/
> GEN-3768: Fix accessibility voice over issue

- Projects/SubmitClaim/Sources/Views/Entrypoints/SelectClaimEntrypoint.swift
- Display error when visible 
- [Change 2](https://reports.useit.se/hedvig-iosapp-may2025/problems/error-messages-not-read-with-voiceover/)
> GEN-3769: Fix for claims flow triaging voiceover when error message is displayed

- Projects/Contracts/Sources/View/ContractCoverage.swift
- Projects/hCoreUI/Sources/Views/CoverageView.swift
Spacing for perils in insurance details increased and needs to be reduced. Moving hWithoutHorizontalPadding to CoverageView fixes it
> Fixed perils spacing for insurance details

- Projects/App/Sources/Navigation/MainNavigation.swift
- Projects/hCoreUI/Sources/ToolbarButtonView/TooltipType.swift
If we have new offer:
- show new offer tooltip max once per 10 minutes
- show new offer tooltip when app starts
> Feature/cross sell/tooltip timming update

- Projects/Chat/Sources/Views/ChatInputView.swift
- Projects/hCoreUI/Sources/View+dismissButton.swift
- Increase click target are to 44x44 which is minimum for accessibility
- Chat send button and dismiss buttom
> GEN-3786: Increase target area for chat and dismiss button

- Projects/Forever/Sources/Navigation/ForeverNavigation.swift
- Projects/hCoreUI/Sources/Views/SuccessScreen.swift
Fixed issue reported [here](https://www.notion.so/hedviginsurance/iOS-Design-fixes-1f8c3f71cb0a80d9a1c7c8d48398eb5a?p=1f3c3f71cb0a80038ec9ff34bd6266ed&pm=s)
> Fix for success screen to use hForm instead of view

- Projects/Claims/Sources/Views/FilesGridView.swift
- Projects/Contracts/Sources/View/ContractInformation.swift
- Projects/EditCoInsuredShared/Sources/Views/CoInsuredField.swift
- Projects/SubmitClaim/Sources/Views/FilesUpload/SubmitClaimFilesUploadScreen.swift
- Projects/hCoreUI/Sources/Peril/Accordion.swift
- Projects/hCoreUI/Sources/Styling/DefaultStyling.swift
- Projects/hCoreUI/Sources/View+dismissButton.swift
- dismiss button proper spacing and accessibility text
- moved info card in upload files for submit claim to bottom instead of having it in the always visible one since it can block whole screen in same cases
- updated button title when removing file from the mentioned step
- combine co-insured filed in insurance details
- read accordion inner content with voice over
> Updated accessibility

- Projects/hCoreUI/Sources/View+dismissButton.swift
- Dismiss button was outside of bubble in iOS26. Removed offset for iOS26 and higher.
> GEN-3920: Make dismiss button align in bubble

- Projects/Contracts/Sources/View/ContractDocuments.swift
- Today we show addon pill "header" under contract documents even if documents are empty
- Added check to not display that header if contracts are empty
> Check if addonVariant has any contracts

- Projects/Addons/Sources/Models/AddonOffer.swift
- Projects/Addons/Sources/Service/DemoImplementation/AddonsClientDemo.swift
- Projects/Addons/Sources/Views/AddonSelectSubOptionScreen.swift
- Projects/Addons/Sources/Views/ChangeAddonSummaryScreen.swift
- Projects/Addons/Tests/ViewModelTests/AddonsViewModelTests.swift
- Projects/App/Sources/Service/OctopusClientsImplementation/AddonsClientOctopus.swift
- Projects/hGraphQL/GraphQL/Octopus/Addons/UpsellTravelAddonOffer.graphql
- Introducing new field for documents in addon flow
background: [slack](https://hedviginsurance.slack.com/archives/C09DF7AB28G/p1756456399847199)
> Instead of showing variant documents, show ones from UpsellTravelAddonQuoteFragment

- Projects/TerminateContracts/Sources/Views/TerminationSummaryScreen.swift
- Added termination date in summary screen
- Placed info box on the bottom
[Figma](https://www.figma.com/design/bgQsRTbBnpYRzbhee97ilh/Bundle-Discounts?node-id=99-22262&m=dev)
> Updated termination flow summary with date

- Projects/Chat/Sources/Views/ChatScreen.swift
- Projects/Chat/Sources/Views/ChatScreenViewModel.swift
- Projects/Chat/Sources/Views/MessageView.swift
- This regards [this slack conversation] (https://hedviginsurance.slack.com/archives/C08C1DG4TFD/p1759482879804499)
- Show only "Hedvig Service Team" if it's the first Hedvig sent message after automation
> GEN-4316: Only show “Hedvig Service Team” if first message after automation
