HedvigInsurance/ugglan

Src/Assets/HedvigColors.swift
Src/Data/GraphQL/MyHome.graphql
Src/Generic/Viewables/CircleLabel.swift
Src/Screens/ProfileScreen/Screens/MyHome/MyHome.swift
Src/Screens/ProfileScreen/Screens/MyHome/Viewables/AddressCircle.swift

The following is added to the "My Home" screen:
- An "address circle" at the top
- A row for living space

"My Home" iterations

---

Src/Generic/Extensions/UIControl+DelayedTouchCancel.swift
Src/Screens/ClaimsScreen/Viewables/CommonClaimsCollection/CommonClaimCard.swift
Src/Screens/DashboardScreen/Viewables/ExpandableRow.swift
Src/Screens/DashboardScreen/Viewables/LargeIconTitleSubtitle.swift
Src/Screens/DashboardScreen/Viewables/Peril.swift

Added haptic tap feedback on perils

Tap feedback on perils

---

Projects/Embark/Example/Sources/StoryList.swift
Projects/Embark/Sources/EmbarkPlans.swift
Projects/Embark/Sources/EmbarkState.swift
Projects/Embark/Sources/MessageBubble.swift
Projects/Embark/Sources/Viewables/Actions/EmbarkInput.swift
Projects/Embark/Sources/Viewables/Actions/InsuranceProviderAction/InsuranceProviderAction.swift
Projects/Embark/Sources/Viewables/Actions/InsuranceProviderAction/InsuranceProviderSelection.swift
Projects/Embark/Sources/Viewables/Actions/Masking.swift
Projects/Embark/Sources/Viewables/Actions/TextAction/EmbarkTextAction.swift
Projects/Embark/Sources/Viewables/Actions/TextActionSet.swift
Projects/Embark/Sources/Viewables/Passage.swift
Projects/Embark/Sources/Viewables/PlanRow.swift
Projects/hCoreUI/Sources/Bullet.swift
Projects/hCoreUI/Sources/GradientView.swift
scripts/post-build-action.sh

Embark fixes

---

Projects/App/Sources/Generic/AppFlow.swift
Projects/App/Sources/Screens/OnboardingScreen/WebOnboarding.swift
Projects/Embark/Sources/Embark.swift

+ moving more button to the other side and `state.goBack()` when the user comes back to embark.

[APP-317] remove restart

---

Projects/Embark/Sources/Embark.swift

Else the progress bar has rounded corners hehe

[APP-292] Set `progressView.progressViewStyle` to `.bar`

---

Projects/App/Sources/Screens/BankIDLoginScreen/SimpleSignLogin.swift

- Add field style to simple sign bank id
[APP-81]: https://hedvig.atlassian.net/browse/APP-81

apply default field style

---

Projects/hCoreUI/Sources/PresentationStyle+Detented.swift

- Adjust insets for detented modals .scrollViewContentSize
[APP-348]: https://hedvig.atlassian.net/browse/APP-348

Adjust detented insets

---

Projects/Payment/Sources/Screens/Adyen/AdyenError.swift
Projects/Payment/Sources/Screens/Adyen/AdyenSuccess.swift
Projects/hCoreUI/Sources/ImageTextAction.swift

- Adjust insets for AdyenError and AdyenSuccess
[APP-346]: https://hedvig.atlassian.net/browse/APP-346

Adjust insets for AdyenError and AdyenSuccess

---

Projects/Contracts/Sources/Reusables/ContractRow+Pills.swift

- Fix status coInsured pill for norwegianTravel
[APP-120]: https://hedvig.atlassian.net/browse/APP-120

Fix status coInsured pill for norwegianTravel

---

Projects/Embark/Sources/Viewables/EmbarkMessages.swift

- Fix auto responses being presented even though they contain no info
[APP-349]: https://hedvig.atlassian.net/browse/APP-349

Fix auto responses being presented even though they contain no info

---

Projects/App/Sources/Generic/AppFlow.swift
Projects/App/Sources/Screens/BankIDLoginScreen/Login.swift
Projects/App/Sources/Screens/BankIDLoginScreen/SimpleSignLogin.swift
Projects/App/Sources/Screens/ChatScreen/OnboardingChat.swift
Projects/App/Sources/Screens/OnboardingScreen/WebOnboarding.swift
Projects/hCore/Sources/Masking.swift

- Fix NIN validation
[APP-347]: https://hedvig.atlassian.net/browse/APP-347

Fix NIN validation

---

Projects/App/Sources/Generic/AppFlow.swift
Projects/App/Sources/Screens/OnboardingScreen/Onboarding.swift
Projects/Payment/Sources/Screens/Adyen/AdyenPayIn.swift

- Remove navbar on top
- Present PostOnboarding detented
- Fix crash that occurred when setting up payments
[APP-356]: https://hedvig.atlassian.net/browse/APP-356

Remove navbar on top + fix crash

---

Projects/Offer/Example/Sources/Debug.swift
Projects/Offer/GraphQL/QuoteBundleQuery.graphql
Projects/Offer/Sources/Components/Header/StartDateSection.swift
Projects/Offer/Sources/Components/MainContentForm/MainContentForm.swift
Projects/Offer/Sources/Components/MainContentForm/Sections/DetailsSection.swift
Projects/Offer/Sources/Offer.swift
Projects/Offer/Testing/NorwegianBundle.swift
Projects/Offer/Testing/SwedishApartment.swift
Projects/Offer/Testing/SwedishHouse.swift

[APP-90]: https://hedvig.atlassian.net/browse/APP-90

Offer details

---

README.md
devices.txt
fastlane/Fastfile
fastlane/README.md

This makes it easier to provision test devices :)

Enhance device provisioning

---

Projects/Offer/Sources/Components/MainContentForm/MainContentForm.swift
Projects/hCoreUI/Sources/Bubbles/CampaignBubble.swift
Projects/hCoreUI/Sources/ExpandableContent.swift

- Fix collapsed details overflow
- Fix button animation
- Better dark mode support
[APP-427]: https://hedvig.atlassian.net/browse/APP-427

App 427 fix collapsed details

---

Projects/App/Sources/Screens/ChatScreen/CallMeChat.swift
Projects/App/Sources/Screens/ChatScreen/FreeTextChat.swift
Projects/App/Sources/Screens/ChatScreen/OfferChat.swift
Projects/App/Sources/Screens/ChatScreen/OnboardingChat.swift
Projects/App/Sources/Screens/OnboardingScreen/WebOnboarding.swift
Projects/Embark/Sources/Embark.swift
Projects/Offer/Example/Sources/Debug.swift
Projects/Offer/GraphQL/QuoteBundleQuery.graphql
Projects/Offer/Sources/Components/Header/DiscountCodeSection.swift
Projects/Offer/Sources/Offer.swift
Projects/Offer/Testing/DanishBundle.swift
Projects/Offer/Testing/NorwegianBundle.swift
Projects/Offer/Testing/SwedishApartment.swift
Projects/Offer/Testing/SwedishHouse.swift
Projects/Offer/Testing/SwedishMovingFlow.swift
Projects/hCoreUI/Sources/UIView+TitleWordmarkView.swift

- Remove campaign management when false
- Add new title and logo title
[APP-529]: https://hedvig.atlassian.net/browse/APP-529

[APP-529] Use `quoteBundle.appConfiguration` in Offer

---

Projects/App/GraphQL/LastQuoteOfMember.graphql
Projects/App/Sources/Screens/ChatScreen/Chat.swift

Fetch offer id from `Query.lastQuoteOfMember` in Swedish OnboardingChat
[APP-530]: https://hedvig.atlassian.net/browse/APP-530

[APP-530] last quote of member fix

---

Projects/App/Sources/Screens/DebugScreen/Debug.swift
Projects/App/Sources/Screens/OnboardingScreen/WebOnboarding.swift
Projects/App/Sources/Screens/OnboardingScreen/WebOnboardingState.swift
Projects/hGraphQL/Sources/Environment.swift

> Add the possibility to send a custom WebOnboarding url.

Fix custom web onboarding url

---

Projects/Offer/GraphQL/QuoteBundleQuery.graphql
Projects/Offer/Sources/Components/Header/Header.swift
Projects/Offer/Sources/Offer.swift
Projects/Offer/Testing/DanishBundle.swift
Projects/Offer/Testing/NorwegianBundle.swift
Projects/Offer/Testing/SwedishApartment.swift
Projects/Offer/Testing/SwedishHouse.swift
Projects/Offer/Testing/SwedishMovingFlow.swift
Projects/hCoreUI/Sources/GradientView+DefaultOptions.swift
Projects/hCoreUI/Sources/GradientView.swift

> So this was rather hard to combine with the loader, but what I did for now is that I initialise with a random gradientOption and then animate between them if they end up being different, looks kind of good IMO and its a 33% chance that you get the correct one, other option would be to have a white screen for a while, but that didn't look as good.
https://user-images.githubusercontent.com/5459507/124501583-250dfe00-ddc2-11eb-99a0-8baa367533e4.mp4
[APP-547]: https://hedvig.atlassian.net/browse/APP-547

Show correct gradient option

---

Projects/Embark/Sources/Embark.swift
Projects/Embark/Sources/EmbarkState+API.swift
Projects/Embark/Sources/EmbarkState.swift
Projects/Embark/Sources/EmbarkStore.swift
Projects/Embark/Sources/Viewables/Passage.swift
Projects/Embark/Tests/ResultMapTests.swift

> Embark wasn't finding and decoding API responses correctly which resulted in moving flow not working.
[APP-553]: https://hedvig.atlassian.net/browse/APP-553

Fix Embark Store and API

---

Projects/Offer/Sources/Screens/Checkout.swift

- Very basic error handling, we need to do a lot more here in v2.
[APP-552]: https://hedvig.atlassian.net/browse/APP-552

App 552 error handling checkout

---

Projects/App/Sources/Generic/AppFlow+MovingFlow.swift
Projects/App/Sources/Screens/LoggedInScreen/LoggedIn.swift
Projects/Contracts/Sources/Contracts.swift
Projects/Contracts/Sources/ContractsState.swift
Projects/Contracts/Sources/Reusables/ContractRow.swift
Projects/Contracts/Sources/Screens/ContractDetail.swift
Projects/Contracts/Sources/Screens/ContractInformation.swift
Projects/Contracts/Sources/Viewables/ContractTable.swift
Projects/Contracts/Tests/ContractRowTests.swift

- Add button
- Add route signal + State to contracts
[APP-600]: https://hedvig.atlassian.net/browse/APP-600

[APP-600] Start moving flow from contracts

---

Projects/App/Sources/Generic/AppFlow+MovingFlow.swift
Projects/App/Sources/Generic/AppFlow.swift
Projects/App/Sources/Screens/LoggedInScreen/LoggedIn.swift
Projects/Embark/Sources/Embark.swift
Projects/Embark/Sources/EmbarkState.swift
Projects/Offer/Example/Sources/Debug.swift
Projects/Offer/Sources/Offer.swift

> Add support for closing offer
[APP-601]: https://hedvig.atlassian.net/browse/APP-601

[APP-601] Close offer

---

Projects/App/Sources/Screens/ProfileScreen/Viewables/MyPaymentRow.swift

- Remove pay with card
[APP-123]: https://hedvig.atlassian.net/browse/APP-123

APP-123-remove-pay-with-card

---

Projects/Market/Sources/MarketPicker.swift
Projects/Market/Sources/MarketStore.swift
Projects/Market/Sources/Viewables/LanguageRow.swift
Projects/Market/Sources/Viewables/MarketRow.swift

> Moving over to use the MarketStore fully for the Market Picker screen, hopefully this makes the screen less flaky.

Fix market picker flaky

---

Projects/App/Sources/AnalyticsCoordinator.swift
Projects/App/Sources/AppDelegate.swift

Track against firebase

---

Projects/Offer/GraphQL/QuoteBundleQuery.graphql
Projects/Offer/Sources/Components/Header/PriceRow.swift
Projects/Offer/Sources/Components/Header/SignSection/SignSection.swift
Projects/Offer/Sources/Components/Header/StartDateSection.swift
Projects/Offer/Sources/Screens/StartDate/StartDate.swift
Projects/Offer/Testing/DanishBundle.swift
Projects/Offer/Testing/NorwegianBundle.swift
Projects/Offer/Testing/SwedishApartment.swift
Projects/Offer/Testing/SwedishHouse.swift
Projects/Offer/Testing/SwedishMovingFlow.swift

> Handle new offer configuration
[APP-782]: https://hedvig.atlassian.net/browse/APP-782

New offer configuration

---

Projects/Offer/Testing/Perils.swift
Projects/hCoreUI/Sources/PerilCollection/PerilDetail.swift
Projects/hGraphQL/GraphQL/PerilFragment.graphql
Projects/hGraphQL/Sources/Models/ContractModels.swift

> Remove peril info, shouldn't be shown any more (request from IPC)

Remove peril info

---

Projects/App/Sources/AppDelegate+Deeplinks.swift
Projects/App/Sources/AppDelegate+Notifications.swift
Projects/App/Sources/AppDelegate.swift
Projects/App/Sources/Journeys/LoggedInJourney.swift
Projects/App/Sources/UgglanStore.swift

- Extend appdelegate to reduce clutter for notifications and deeplinks
- Handle new firebase deeplinks
[APP-789]: https://hedvig.atlassian.net/browse/APP-789

App 789 firebase deeplinking

---

Projects/hGraphQL/Sources/Models/ContractModels.swift

Null gradient

---

Projects/Contracts/Sources/View/ContractTable.swift
Projects/Contracts/Sources/View/CrossSellingStack.swift
Projects/hCore/Sources/PresentableStoreLens.swift

> Add some animations for CrossSelling

CrossSelling animations

---

Projects/App/Sources/Journeys/MovingFlowJourney.swift
Projects/Contracts/Sources/Screens/MovingFlow/MovingFlowSuccess.swift

> Add date to MovingFlowSuccess
[APP-879]: https://hedvig.atlassian.net/browse/APP-879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Moving flow date

---

Projects/Contracts/Sources/View/CrossSellingItem.swift

- Change 1
- Change 2
[APP-1027]: https://hedvig.atlassian.net/browse/APP-1027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APP-1027] cross selling title fix

---

.github/workflows/CleanDerivedData.yml
Projects/Contracts/Sources/Screens/MovingFlow/MovingFlowIntro.swift

- Fix centering of content
[APP-1065]: https://hedvig.atlassian.net/browse/APP-1065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APP-1065] Fix centering of image content

---

Projects/Embark/GraphQL/EmbarkStory.graphql
Projects/Embark/Sources/Viewables/Actions/SelectAction/EmbarkSelectActionOption.swift

- Adds badge for embark select action
[APP-992]: https://hedvig.atlassian.net/browse/APP-992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Badge for Embark select action

---

Projects/App/Sources/Journeys/LoggedInJourney.swift

- Fix fetching contracts on login
[APP-1153]: https://hedvig.atlassian.net/browse/APP-1153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

APP-1153-fetch on login

---

Projects/Home/Sources/AudioTrack/AudioPlayer.swift
Projects/Home/Sources/Claims/ClaimDetailView.swift
Projects/Home/Sources/Claims/ClaimSection.swift
Projects/Home/Sources/Claims/ClaimStatus.swift
Projects/Home/Sources/Claims/ContactChatView.swift
Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift

- Adds events for tracking claim details flow
[APP-1246]: https://hedvig.atlassian.net/browse/APP-1246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Analytics for claim details

---

Projects/Contracts/Sources/ContractsStore.swift

- Remove distinct filtering on fetch active contract bundles
[APP-1187]: https://hedvig.atlassian.net/browse/APP-1187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

APP-1187-infinite-spinner-no-active-contracts

---

Projects/Embark/GraphQL/EmbarkStory.graphql
Projects/Embark/Sources/EmbarkState+API.swift

- Constant Variable GraphQL querying and parsing in the app

Embark - constant variable graphql

---

Projects/App/Sources/AppDelegate+hAnalytics.swift
Projects/App/Sources/AppDelegate.swift
Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift

> Send `granted: nil` when notDetermined

Adjust push tracking

---

Projects/App/Sources/Screens/ProfileScreen/Screens/MyInfo/MyInfo.swift
Projects/Offer/Sources/Offer.swift
Projects/Payment/Sources/Screens/Adyen/AdyenPayIn.swift

> Fixes some missing tracking events

More tracking events

---

Projects/App/Sources/Screens/DebugScreen/Impersonate.swift

Fix impersonation crash

---

Projects/Home/Sources/Home.swift

> Center title on home, request from design in prep for new font
[APP-1488]: https://hedvig.atlassian.net/browse/APP-1488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Center title on home

---

fastlane/Fastfile

> Set test device to iPhone 13 Pro (15.4)

Change test device

---

Projects/Home/Sources/Home.swift
Projects/hCoreUI/Sources/Fonts.swift
Projects/hCoreUI/Sources/hText/hText.swift
Tuist/Config.swift

> Adds a new text style `prominentTitle` that is Serif and keep `largeTitle` as Sans-Serif.

Add prominentTitle text style

---

Projects/Contracts/Sources/View/ContractRow.swift
Projects/hGraphQL/GraphQL/ActiveContractBundles.graphql
Projects/hGraphQL/GraphQL/Contracts.graphql
Projects/hGraphQL/Sources/Models/ContractModels.swift

- Displays contracts' logo after querying for it
[APP-1628]: https://hedvig.atlassian.net/browse/APP-1628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Render contracts' logo from response

---

Projects/Offer/Sources/OfferStore.swift
Tuist/Config.swift

- Add received quotes analytics event
[APP-1788]: https://hedvig.atlassian.net/browse/APP-1788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add received quotes event

---

Projects/hCoreUI/Sources/GradientView.swift

> Don't really get what causes this but the gradient was a bit too small height wise, super ugly fix, but it solves it 🙈
[APP-774]: https://hedvig.atlassian.net/browse/APP-774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix gradient being slightly too small

---

Projects/hCoreUI/Sources/hForm/hRow.swift

> Increase hRow padding
[APP-929]: https://hedvig.atlassian.net/browse/APP-929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APP-929] Increase hRow padding

---

Projects/App/Sources/Screens/ClaimsScreen/Screens/ClaimsAskForPushnotifications.swift

> Change button colors
[APP-1001]: https://hedvig.atlassian.net/browse/APP-1001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 Notifications buttons

---

Projects/hCoreUI/Sources/Views/DetailsTableView.swift

> Render table titles correctly
[APP-1782]: https://hedvig.atlassian.net/browse/APP-1782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Render table titles correctly

---

Projects/Contracts/Sources/Screens/MovingFlow/MovingFlowIntro.swift

> Migrate moving flow buttons to SwiftUI and meanwhile fix icon aligment inside button
[APP-681]: https://hedvig.atlassian.net/browse/APP-681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Migrate moving flow buttons to SwiftUI

---

Projects/Contracts/Sources/Screens/MovingFlow/MovingFlowIntro.swift
Projects/Embark/Sources/Embark.swift

> Check the boolean in the Embark restart alert if we should actually restart 😅 
[APP-1540]: https://hedvig.atlassian.net/browse/APP-1540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Only restart if the user clicked OK

---

Projects/Offer/Sources/Components/MainContentForm/Sections/Variation/VariantSelector.swift

> Handle `ignoreCampaigns` for variants in the offer screen
[APP-1803]: https://hedvig.atlassian.net/browse/APP-1803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle ignore campaigns for variants

---

Projects/hCoreUI/Sources/Pager/Viewables/ContentIconPagerItem.swift

[APP-1805]: https://hedvig.atlassian.net/browse/APP-1805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix centre alignment on pagers

---

Projects/Market/Sources/Market.swift
Projects/Market/Sources/Viewables/MarketRow.swift

[APP-1407]: https://hedvig.atlassian.net/browse/APP-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Display country name on market picker based on locale

---

Projects/App/Sources/AnalyticsCoordinator.swift

> Send `Localization.Locale.currentLocale` to Shake bugs.
[APP-1456]: https://hedvig.atlassian.net/browse/APP-1456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Send locale to shake bugs

---

Projects/Contracts/Sources/Screens/ContractInformation.swift

- Add change coinsured messaging + cta to all contract information pages
[APP-1516]: https://hedvig.atlassian.net/browse/APP-1516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add change people to all active contracts

---

Projects/Offer/Sources/Components/BottomAttachedSignButton.swift
Projects/Offer/Sources/Components/Header/HeaderForm.swift
Projects/Offer/Sources/Components/Header/SignSection/SignSection.swift
Projects/Offer/Sources/Components/MainContentForm/MainContentForm.swift
Projects/Offer/Sources/Offer.swift
Projects/hCore/Sources/HostingView.swift

> Add purchase button to bottom of offer screen
[APP-1352]: https://hedvig.atlassian.net/browse/APP-1352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add purchase button to bottom of offer screen

---

Projects/Claims/Sources/ClaimAction.swift
Projects/Claims/Sources/ClaimStore.swift
Projects/Claims/Sources/Journeys/ClaimJourneys.swift
Projects/Claims/Sources/Views/SubmitClaim/IncidentInfo/DatePickerScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/IncidentInfo/SubmitClaimOccurrenceScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/SingleItem/SubmitClaimSingleItem.swift
Projects/Claims/Sources/Views/SubmitClaim/SummaryInfo/SubmitClaimEditSummaryScreen.swift

- Added handling of date of occurrence step

Added handling of DateOfOccurrence step

---

Projects/hCoreUI/Sources/Presentation+withDismissButton.swift

- Added dismiss button with confirmation

Added dismiss journey button with confirmation

---

Projects/Claims/Sources/CommonClaims/CommonClaimDetail.swift

CLX-504 Changed id for firstVet link

---

Projects/Contracts/Sources/View/Termination/SetTerminationDate.swift
Projects/Contracts/Sources/View/Termination/TerminationDeleteScreen.swift

- Added keys: 
TERMINATION_CONFIRM_BUTTON
TERMINATION_CONTRACT_DELETION_CONFIRM_BUTTON
[CLX-510]: https://hedvig.atlassian.net/browse/CLX-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Changed text keys for termination

---

Projects/Claims/Sources/ClaimStore.swift

- Added missing currency on summary screen

Added missing currency for summary screen

---

Projects/App/GraphQL/Giraffe/InsurancePrice.graphql
Projects/App/GraphQL/Giraffe/Profile.graphql
Projects/App/GraphQL/Giraffe/ReferralsScreen.graphql
Projects/App/Sources/Screens/ProfileScreen/Viewables/MyPaymentRow.swift
Projects/App/Sources/Screens/ProfileScreen/Viewables/ProfileSection.swift
Projects/Payment/GraphQL/Giraffe/AdyenAvailableMethods.graphql
Projects/Payment/GraphQL/Giraffe/MyPayment.graphql
Projects/Payment/Sources/PaymentStore.swift
Projects/Payment/Sources/Viewables/PaymentDetailsSection/PaymentDetailsSection.swift

> `insuranceCost` gives the wrong info with members with more than one contract, hence we shouldn't use that but `chargeEstimation` instead.
[APP-519]: https://hedvig.atlassian.net/browse/APP-519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Stop using `insuranceCost` and start using `chargeEstimation`

---

Projects/Claims/Sources/Views/SubmitClaim/IncidentInfo/SubmitClaimOccurrenceScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/SingleItem/SubmitClaimSingleItem.swift
Projects/hCoreUI/Sources/hForm/hTextField.swift

UI cleanup of Claims flow, use hRow and hSection accordingly to automatically get styling

---

Projects/Claims/Sources/Journeys/ClaimJourneys.swift

- Fixed bugfix with common claim från quick choice. The user is now redirected to entrypoints.

Removed cases to make common claims go to entrypoint flow

---

Projects/App/Sources/AppDelegate.swift
Projects/hCore/Sources/ApplicationContext.swift
Projects/hCore/Sources/hAnalyticsExperiment+RetryingLoad.swift

- Added handling of hAnalytics error

Added handling of hAnalytics error

---

Projects/Contracts/Sources/Screens/ContractDetail.swift
Projects/Payment/Sources/Viewables/PaymentDetailsSection/CardDetailsSection.swift
Projects/Payment/Sources/Viewables/PaymentDetailsSection/PayoutDetailsSection.swift
Projects/hCoreUI/Sources/Views/DetailsTableView.swift

- Fix detend style for add payment (this happened on danish/norway market)
- Fix detend style for contract update full details
https://hedviginsurance.slack.com/archives/CPCUHMMJQ/p1682429052083669
https://hedviginsurance.slack.com/archives/CPCUHMMJQ/p1682076243184359

Not showing modal content on some screens

---

Projects/App/Sources/Journeys/ChatJourney.swift
Projects/App/Sources/Screens/ChatScreen/Chat.swift
Projects/App/Sources/Screens/ChatScreen/ChatState.swift
Projects/App/Sources/Screens/ChatScreen/Viewables/AttachFilePane.swift

- Added erro handling for chat

Added error check for chat

---

Projects/App/Sources/AppDelegate+Notifications.swift
Projects/App/Sources/Journeys/LoggedInJourney.swift
Projects/hCore/Sources/HostingJourney/HostingJourney.swift
Projects/hCore/Sources/PresentationStyle+UnlessAlreadyPresented.swift
Projects/hCoreUI/Sources/Toasts.swift

Fixes some issues i found while testing pushes

Fix views not opening correctly after clicking push notification

---

Projects/App/Sources/Generic/AccessoryViewController.swift
Projects/App/Sources/Journeys/ChatJourney.swift
Projects/App/Sources/Journeys/ClaimsJourney.swift
Projects/App/Sources/Screens/ChatScreen/Chat.swift
Projects/App/Sources/Screens/ChatScreen/ChatState.swift
Projects/App/Sources/Screens/ClaimsScreen/Screens/ClaimFlowAskForPushnotifications.swift
Projects/App/Sources/UgglanStore.swift
Projects/hCoreUI/Sources/PerilCollection/PerilDetail.swift
Projects/hGraphQL/GraphQL/Octopus/HelloFromOdysseyQuery.graphql

- Update handling of notifications permissions

Added handling of chat permission on chat screen; Update existing handling

---

Projects/hCoreUI/Sources/hForm/hTextField.swift

- Added focus support for iOS 15+

Fixed focus for iOS 15+

---

Projects/Claims/Sources/SubmitClaimStore.swift

add check if entrypointId is nil

---

Projects/App/Sources/Journeys/LoggedInJourney.swift
Projects/Contracts/Sources/Contracts.swift
Projects/Contracts/Sources/View/ContractTable.swift
Projects/hCoreUI/Sources/hForm/Gradient/GradientState.swift
Projects/hCoreUI/Sources/hForm/Gradient/GradientType.swift
Projects/hCoreUI/Sources/hForm/hForm.swift

- Show cross sells when user has only terminated contracts
- Updated gradient transition from Insurances to terminated insurances

Show cross sell for terminated contracts

---

Projects/Contracts/Sources/Screens/ContractInformation.swift

remove “change your info” button

---

Projects/hCoreUI/Sources/hForm/hFloatingField.swift
Projects/hCoreUI/Sources/hForm/hFloatingTextField.swift

added hFloatingField and added suffix option to text field

---

Projects/hCoreUI/Sources/hForm/hForm.swift

added blur and scoll option to hForm

---

Projects/hCoreUI/Sources/Views/NoticeComponent.swift

add notice component

---

Projects/App/Sources/Screens/ChatScreen/Models/Message.swift
Projects/App/Sources/Screens/ChatScreen/Reusables/Message+Reusable.swift

[--- Notion --- ](https://www.notion.so/hedviginsurance/a4c35052b6794b36a4b0d58b537cc325?v=daf931945e6243fcbbbf7016a5802265&p=c7cc8482e82a4f5c9e5f89e7346b4403&pm=s)
- Removed edit button for chat

Removed edit button for chat

---

Projects/Market/Sources/Market.swift
Projects/Market/Sources/MarketPicker.swift

- Removed "Get quote" button for other Countries

Removed get quote for other countries beside sweden

---

Projects/hCoreUI/Sources/hForm/hForm.swift

fix header style

---

Projects/App/Sources/AppDelegate+Deeplinks.swift
Projects/App/Sources/AppDelegate.swift
Projects/App/Sources/Journeys/LoggedInJourney.swift
Projects/App/Sources/Screens/ProfileScreen/Screens/EuroBonus/EuroBonusView.swift

- added pull to refresh on profile

Pull to refresh on profile / deep link

---

Projects/App/Sources/Screens/ChatScreen/Reusables/Message+Reusable.swift

[Notion](https://www.notion.so/hedviginsurance/a4c35052b6794b36a4b0d58b537cc325?v=c74a8cb958ab4ba6ba4c904d8540b106&p=c3e1257962854c9fab4ca776e90db08f&pm=s)

Fixed issue with attachment name in chat

---

Projects/Contracts/Sources/Contracts.swift
Projects/Contracts/Sources/Stores/ContractAction.swift
Projects/Contracts/Sources/Stores/ContractsStore.swift

- pull to refresh on insraunces tab

Added pull to refresh on contracts tab

---

Projects/App/Sources/Journeys/ClaimsJourney.swift
Projects/App/Sources/Screens/ClaimsScreen/Screens/ClaimFlowAskForPushnotifications.swift
Projects/App/Sources/Screens/ClaimsScreen/Screens/HonestyPledge.swift
Projects/Claims/Sources/Journeys/ClaimJourneys.swift
Projects/Claims/Sources/SubmitClaimAction.swift
Projects/Claims/Sources/SubmitClaimState.swift
Projects/Claims/Sources/SubmitClaimStore.swift
Projects/Claims/Sources/Views/SubmitClaim/Entrypoints/SelectClaimEntrypoint.swift
Projects/Claims/Sources/Views/SubmitClaim/Entrypoints/SelectClaimEntrypointOld.swift
Projects/hCoreUI/Sources/PresentationStyle+Detented.swift

- Move honesty pledge to first place on claims flow

Feature/claims navigation/change honesty pledge order

---

Projects/App/Sources/AppDelegate.swift
Projects/Authentication/Sources/AuthenticationStore.swift
Projects/Claims/Sources/Claims.swift

- Added logs for Swedish login
- Call set user id only when logged in
- Remove claims fetch when user is logged out

Added log for swedish login; call set user id only when logged in

---

Projects/App/Sources/Journeys/ClaimsJourney.swift
Projects/Claims/Sources/Journeys/ClaimsProgressBar.swift
Projects/Claims/Sources/SubmitClaimAction.swift
Projects/Claims/Sources/SubmitClaimState.swift
Projects/Claims/Sources/SubmitClaimStore.swift
Projects/Claims/Sources/Views/SubmitClaim/Entrypoints/SelectClaimEntrypoint.swift
Projects/hCoreUI/Sources/HedvigColorsNew.swift

- Added progress bar for claims flow

Added progress bar for claims

---

Projects/hCoreUI/Sources/hForm/hFieldBackground.swift

- Removed border for field background when not editing

Removed border for field background when not editing

---

Projects/App/Sources/AppDelegate+Tracking.swift
Projects/App/Sources/AppDelegate.swift
Projects/App/Sources/DatadogLogger.swift
Projects/App/Sources/Journeys/LoginJourney.swift
Projects/App/Sources/Journeys/MainJourney.swift
Projects/Authentication/Sources/AuthenticationStore.swift
Projects/Authentication/Sources/SEBankID/BankIDLoginQR.swift
Projects/Authentication/Sources/SEBankID/BankIDLoginSweden.swift
Projects/hGraphQL/Sources/TokenRefresher.swift
Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift

- Fixed logs to work
- Added additional logs for login
- Update datadog version

Added login logs; fix logs

---

Projects/Claims/Sources/Views/SubmitClaim/AudioRecording/SubmitClaimAudioRecordingScreenOld.swift

- Fixed not visible questions for old design on claims audio

Fixed audio recording quesitons not visible

---

Projects/Claims/Sources/Journeys/ClaimJourneys.swift
Projects/Claims/Sources/Views/SubmitClaim/AudioRecording/SubmitClaimAudioRecordingScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/AudioRecording/SubmitClaimAudioRecordingScreenOld.swift
Projects/Claims/Sources/Views/SubmitClaim/Entrypoints/SelectClaimEntrypointOld.swift
Projects/Claims/Sources/Views/SubmitClaim/IncidentInfo/LocationPickerScreenOld.swift
Projects/Claims/Sources/Views/SubmitClaim/IncidentInfo/SubmitClaimOccurrencePlusLocationScreenOld.swift
Projects/Claims/Sources/Views/SubmitClaim/LoadingViewWithState.swift
Projects/Claims/Sources/Views/SubmitClaim/SingleItem/SubmitClaimSingleItemOld.swift
Projects/Claims/Sources/Views/SubmitClaim/SubmitClaimContactScreenOld.swift
Projects/hCoreUI/Sources/ActivityIndicator.swift

Added loading indicator for new design

---

Projects/hCoreUI/Sources/hForm/hFieldBackground.swift

remove border

---

Projects/App/Sources/Screens/ClaimsScreen/Screens/HonestyPledge.swift
Projects/Claims/Sources/Views/SubmitClaim/Entrypoints/SelectClaimEntrypoint.swift

- Padding, blur and text fixes for triaging and honesty pledge

Fix/claims navigation/fix triaging and honesty pledge paddings

---

Projects/Claims/Sources/CommonClaims/CommonClaimsCollection.swift

- Removed recommended for you if no items to show

Removed Recommended for you if nothing to show

---

Projects/hCoreUI/Sources/PresentationStyle+Detented.swift

- Detented corner radius updated to 16

Updated detent corner radius

---

Projects/App/Sources/AppDelegate.swift
Projects/Authentication/Sources/AuthenticationStore.swift
Projects/Authentication/Sources/SEBankID/BankIDLoginQR.swift
Projects/Authentication/Sources/SEBankID/BankIDLoginSweden.swift
Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift

- Added error handling for authlib

Added better error handling for login

---

Projects/App/Sources/Screens/ProfileScreen/Screens/EuroBonus/EuroBonusView.swift
Projects/Claims/Sources/Views/SubmitClaim/SingleItem/SubmitClaimSingleItemOld.swift
Projects/Contracts/Sources/View/TravelInsurance/TravelInsuranceEmailScreen.swift
Projects/Contracts/Sources/View/TravelInsurance/TravelInsuranceInsuredMemberScreen.swift

- Possible fix for eurobonus crash

Try to fix euro bonus crash

---

Projects/Claims/Sources/Journeys/ClaimJourneys.swift
Projects/Claims/Sources/Views/SubmitClaim/IncidentInfo/DatePickerScreen.swift

- Fixed date picker for old flow
- Fixed location picker for old flow

Fixed date and location picker screens for old flow

---

Projects/App/GraphQL/Giraffe/Profile.graphql
Projects/App/Sources/Screens/ProfileScreen/Profile.swift
Projects/App/Sources/Screens/ProfileScreen/ProfileState.swift

- Updated business model to not contain cashback

updated business model to not contain cashback

---

Projects/Claims/Sources/Views/submitClaim/Checkout/SubmitClaimCheckoutTransferringScreen.swift
Projects/hCoreUI/Sources/hText/hTextNew.swift

- added haptic feedback when money is payed out on checkout step
- updated text color on checkout step
- updated missing line height for font

haptic feedback and updated missing font

---

Projects/Claims/Sources/Journeys/ClaimJourneys.swift
Projects/Claims/Sources/Views/SubmitClaim/SubmitClaimSuccessScreen.swift

- Updated position of content
- Removed dismiss button and title

updated position and removed dismiss button and title

---

Projects/Claims/Sources/Journeys/ClaimJourneys.swift
Projects/Claims/Sources/SubmitClaimAction.swift
Projects/Claims/Sources/Views/SubmitClaim/IncidentInfo/DatePickerScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/LoadingViewWithState.swift
Projects/hCoreUI/Sources/Styling/DefaultStyling.swift
Projects/hCoreUI/Sources/hColor/hColorNew.swift

- Added different options for LoadingButtonWithContent to match date picker need
- Updated color from lavender to black

Updated color and fixed buttons that did not look as expected

---

Projects/hCoreUI/Sources/hForm/hCounterField.swift
Projects/hCoreUI/Sources/hForm/hDatePickerField.swift
Projects/hCoreUI/Sources/hForm/hFieldBackground.swift
Projects/hCoreUI/Sources/hForm/hFloatingField.swift
Projects/hCoreUI/Sources/hForm/hFloatingTextField.swift
Projects/hCoreUI/Sources/hText/hTextNew.swift

- Fixed input fields height
- Added animation

Feature/claims navigation/fix input fields height

---

Projects/Claims/Sources/Journeys/ClaimJourneys.swift
Projects/Claims/Sources/SubmitClaimAction.swift
Projects/Claims/Sources/Views/SubmitClaim/SingleItem/PriceInputScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/SingleItem/SubmitClaimSingleItem.swift
Projects/hCoreUI/Sources/PresentationStyle+Detented.swift
Projects/hCoreUI/Sources/hForm/hFloatingTextField.swift

- Created own screen for price input
- Modified text field to match design 
TODO:
- scroll size doesn't work when keyboard is visible

Feature/claims navigation/price input field

---

Projects/Claims/Sources/Journeys/ClaimJourneys.swift
Projects/Home/Sources/ConfigureHomeScroll.swift
Projects/Offer/Sources/Offer.swift
Projects/hCoreUI/Sources/Document.swift
Projects/hCoreUI/Sources/Fonts/Fonts.swift
Projects/hCoreUI/Sources/Fonts/FontsNew.swift
Projects/hCoreUI/Sources/Journey+ScrollEdgeToStandard.swift
Projects/hCoreUI/Sources/Presentation+withDismissButton.swift
Projects/hCoreUI/Sources/PresentationStyle+Detented.swift
Projects/hCoreUI/Sources/Styling/DefaultStyling.swift
Projects/hCoreUI/Sources/hForm/hFieldBackground.swift
Projects/hCoreUI/Sources/hForm/hFloatingTextField.swift
Projects/hCoreUI/Sources/hText/hTextNew.swift

- Added support for large navigation bar
- Updated font for large navigation bar
-

Added large navigation bar

---

Projects/Claims/Sources/Views/SubmitClaim/LoadingViewWithState.swift

- Added delay when loading finish for claims

Added delay for loading button (use could press button multiple times)

---

Projects/Claims/Sources/Journeys/ClaimJourneys.swift

- Fixed claims navigation brand/model picker

Fixed brand/model picker on claims navigation

---

Projects/App/Sources/Journeys/ClaimsJourney.swift
Projects/Claims/Sources/Journeys/ClaimJourneys.swift
Projects/Claims/Sources/Views/SubmitClaim/SingleItem/PriceInputScreen.swift
Projects/hCoreUI/Sources/PresentationStyle+Detented.swift
Projects/hCoreUI/Sources/hForm/hForm.swift

- Added blur to modals on claims flow for new design
- Fixed unnecessary spacing for detent style

Added blur to modals on claims flow

---

Projects/Payment/Sources/Screens/DirectDebitSetup.swift

- Added retry for payment screen

Added retry alert for add/change payment

---

Projects/App/Sources/Journeys/ClaimsJourney.swift
Projects/Claims/Sources/Journeys/ClaimJourneys.swift
Projects/Claims/Sources/Views/SubmitClaim/IncidentInfo/DatePickerScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/IncidentInfo/SubmitClaimOccurrencePlusLocationScreen.swift
Projects/hCoreUI/Sources/PresentationStyle+Detented.swift
Projects/hCoreUI/Sources/Styling/DefaultStyling.swift

- Moved progress bar above keyboard
- Moved navigation bar a little for screen with progress bar
- Removed date picker background color

Moved progress bar above navigation bar

---

Projects/Contracts/Sources/View/TravelInsurance/TravelInsuranceFormScreen.swift

- Fix travel insurance select date

Fixed issue with selected date

---

Projects/App/Sources/Screens/ClaimsScreen/Screens/ClaimFlowAskForPushnotifications.swift
Projects/App/Sources/Screens/ClaimsScreen/Screens/HonestyPledge.swift

- Remove memory leak on honesty pledge
- Remove memory leak on notification permission

Fixed memory leak on honesty pledge

---

Projects/Claims/Sources/Views/SubmitClaim/SingleItem/PriceInputScreen.swift
Projects/hCoreUI/Sources/hButton/hButton.swift
Projects/hCoreUI/Sources/hColor/hColorNew.swift

- fixed height of button to 56
- updated color on press for new deisgn

fixed height of button and color on press

---

Projects/App/Sources/Screens/ClaimsScreen/Screens/ClaimFlowAskForPushnotifications.swift
Projects/Claims/Sources/Journeys/ClaimJourneys.swift
Projects/hCore/Sources/UIApplication+safearea.swift
Projects/hCoreUI/Sources/PresentationStyle+Detented.swift
Projects/hCoreUI/Sources/Styling/DefaultStyling.swift
Projects/hCoreUI/Sources/hForm/hForm.swift

- Added blur to navbag
- Added blue to form "toolbar"

Added blurred navbar + "toolbar"

---

Projects/App/Sources/Journeys/ClaimsJourney.swift
Projects/App/Sources/Screens/ClaimsScreen/Screens/ClaimFlowAskForPushnotifications.swift
Projects/Claims/Sources/ClaimMutation+Actions.swift
Projects/Claims/Sources/Journeys/ClaimJourneys.swift
Projects/Claims/Sources/SubmitClaimAction.swift
Projects/Claims/Sources/SubmitClaimStore.swift
Projects/hCoreUI/Sources/PresentationStyle+Detented.swift

- Updated progress bar to include triaging

update progress bar to include triaging

---

Projects/Claims/Sources/ClaimMutation+Actions.swift
Projects/Claims/Sources/SubmitClaimAction.swift
Projects/Claims/Sources/SubmitClaimState.swift
Projects/Claims/Sources/SubmitClaimStore.swift
Projects/Claims/Sources/Views/SubmitClaim/AudioRecording/SubmitClaimAudioRecordingScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/Entrypoints/SelectClaimEntrypoint.swift
Projects/Claims/Sources/Views/SubmitClaim/IncidentInfo/DatePickerScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/IncidentInfo/SubmitClaimOccurrencePlusLocationScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/SingleItem/SubmitClaimSingleItem.swift
Projects/Claims/Sources/Views/SubmitClaim/SubmitClaimContactScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/SummaryInfo/SubmitClaimSummaryScreen.swift
Projects/Claims/Sources/Views/submitClaim/Checkout/SubmitClaimCheckoutTransferringScreen.swift
Projects/hCoreUI/Sources/ActivityIndicatorView.swift
Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift

- Upgraded presentation to 2.0.21 which contains loading state
- Moved loading elements to hCoreUI

Moved loading state to store + loading elements to hCoreUI

---

Projects/Contracts/Sources/Contracts.swift
Projects/Contracts/Sources/View/ContractTable.swift
Projects/hCoreUI/Sources/ChatButtonView/ChatButtonView.swift

- Updated cancelled insurances screen

Feature/app redesign/gen 689 insurance/gen 708 update cancelled insurances screen

---

Projects/Home/Sources/ConfigureHomeScroll.swift
Projects/Offer/Sources/Offer.swift
Projects/hCoreUI/Resources/Assets.xcassets/QuickNavigation/ChatQuickNav.imageset/Contents.json
Projects/hCoreUI/Resources/Assets.xcassets/QuickNavigation/ChatQuickNavNotification.imageset/Contents.json
Projects/hCoreUI/Resources/Assets.xcassets/QuickNavigation/FirstVetQuickNav.imageset/Contents.json
Projects/hCoreUI/Resources/Assets.xcassets/QuickNavigation/FirstVetQuickNavNotification.imageset/Contents.json
Projects/hCoreUI/Sources/ChatButtonView/ChatButtonView.swift
Projects/hCoreUI/Sources/Document.swift
Projects/hCoreUI/Sources/Journey+ScrollEdgeToStandard.swift
Projects/hCoreUI/Sources/Presentation+withDismissButton.swift
Projects/hCoreUI/Sources/Styling/DefaultStyling.swift

- Updated navigation to be transparent everywhere

Feature/app redesign/gen 744 navigation

---

Projects/Contracts/Sources/View/CrossSellingItem.swift
Projects/Contracts/Sources/View/CrossSellingSigned.swift
Projects/hCoreUI/Sources/CrossSell+image.swift
Projects/hCoreUI/Sources/hForm/hForm.swift
Projects/hGraphQL/GraphQL/Octopus/CrossSale.graphql
Projects/hGraphQL/Sources/Models/CrossSellModels.swift

Feature/app redesign/gen 689 insurance/cross sell type

---

Projects/Contracts/Sources/Contracts.swift
Projects/Contracts/Sources/Journeys/ContractDetail.swift

Feature/app redesign/gen 689 insurance/fix edit info

---

Projects/Claims/Sources/Views/SubmitClaim/AudioRecording/SubmitClaimAudioRecordingScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/Entrypoints/SelectClaimEntrypoint.swift
Projects/Claims/Sources/Views/SubmitClaim/IncidentInfo/SubmitClaimOccurrencePlusLocationScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/SingleItem/SubmitClaimSingleItem.swift
Projects/Claims/Sources/Views/SubmitClaim/SubmitClaimContactScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/SummaryInfo/SubmitClaimSummaryScreen.swift
Projects/hCoreUI/Sources/ActivityIndicatorView.swift
Projects/hCoreUI/Sources/Loading+disabled.swift
Projects/hCoreUI/Sources/hForm/hFieldBackground.swift
Projects/hCoreUI/Sources/hForm/hFloatingField.swift
Projects/hCoreUI/Sources/hForm/hFloatingTextField.swift

Added disabled for floatingField + textFloatingField

---

Projects/Forever/Sources/Components/InivtationTable.swift
Projects/Forever/Sources/Forever.swift
Projects/Forever/Sources/ForeverService.swift
Projects/Forever/Sources/ForeverServiceGraphQL.swift
Projects/Forever/Sources/ForeverStore.swift
Projects/Forever/Sources/Header.swift
Projects/hCoreUI/Sources/hForm/hSection.swift
Projects/hCoreUI/Sources/hText/hText.swift

Updated invitations

---

Projects/Contracts/Sources/Journeys/ContractDetail.swift
Projects/Contracts/Sources/Journeys/ContractDocuments.swift

edit color and placement of termination button

---

Projects/Forever/Sources/Components/PriceSectionView.swift
Projects/Forever/Sources/Forever.swift
Projects/Forever/Sources/Header.swift

- Added scroll down to bottom if info icon is tapped

GEN-762: Feature/app redesign/gen 691 forever/gen 762 add scroll

---

Projects/App/Sources/Journeys/LoggedInJourney.swift
Projects/App/Sources/Screens/ProfileScreen/Profile.swift

Remove chat and large navigation title

---

Projects/App/Sources/Journeys/ClaimsJourney.swift
Projects/App/Sources/Screens/ChatScreen/Reusables/Message+Reusable.swift
Projects/Claims/Sources/AudioTrack/AudioPlayer.swift
Projects/Claims/Sources/AudioTrack/TrackPlayer.swift
Projects/Claims/Sources/ClaimAction.swift
Projects/Claims/Sources/Views/ClaimDetailHeader.swift
Projects/Claims/Sources/Views/ClaimDetailView.swift
Projects/Claims/Sources/Views/ContactChatView.swift
Projects/Claims/Sources/Views/SubmitClaim/AudioRecording/SubmitClaimAudioRecordingScreen.swift
Projects/Home/Sources/Screens/Home.swift
Projects/hCore/Sources/Date+LocalDateString.swift
Projects/hCore/Sources/JourneyPresentation+HidesToolbar.swift
Projects/hCore/Sources/String+toDate.swift
Projects/hCoreUI/Sources/HedvigColorsNew.swift
Projects/hCoreUI/Sources/RaisedCard.swift
Projects/hCoreUI/Sources/Styling/DefaultStyling.swift
Projects/hCoreUI/Sources/Views/CardComponent.swift
Projects/hGraphQL/Sources/Models/Claims.swift

GEN-817: Updated claim details

---

Projects/Forever/Sources/DiscountCodeSection.swift
Projects/hCoreUI/Sources/HedvigColorsNew.swift
Projects/hCoreUI/Sources/Toasts.swift

GEN-830: Toasts

---

Projects/App/Sources/Screens/ProfileScreen/Profile.swift
Projects/App/Sources/Screens/ProfileScreen/ProfileRowType.swift
Projects/App/Sources/Screens/ProfileScreen/ProfileState.swift
Projects/App/Sources/Screens/SettingsScreen/SettingsScreen.swift
Projects/App/Sources/UgglanStore.swift
Projects/Contracts/Sources/Stores/ContractsStore.swift
Projects/Market/Sources/PickLanguage.swift

- Updated settings language change

Updated language picker

---

Projects/Home/Sources/Components/ActiveSectionView.swift
Projects/Home/Sources/Components/FutureSectionView.swift
Projects/Home/Sources/Components/TerminatedSectionView.swift
Projects/Home/Sources/Screens/Home.swift
Projects/hCoreUI/Sources/Fonts/Fonts.swift
Projects/hCoreUI/Sources/Views/InfoCard.swift
Projects/hCoreUI/Sources/hText/hText.swift

GEN-819: Added different messages for different states

---

Projects/App/Sources/Journeys/LoggedInJourney.swift
Projects/App/Sources/Screens/ProfileScreen/ProfileRowType.swift
Projects/Contracts/Sources/Contracts.swift
Projects/Contracts/Sources/EditContract.swift
Projects/Contracts/Sources/Journeys/ContractInformation.swift
Projects/Contracts/Sources/Stores/ContractAction.swift
Projects/Contracts/Sources/Stores/ContractState.swift
Projects/Contracts/Sources/Stores/ContractsStore.swift
Projects/Contracts/Sources/View/ContractRow.swift
Projects/Contracts/Sources/View/ContractTable.swift
Projects/Forever/Sources/Forever.swift
Projects/Home/Sources/CommonClaims/CommonClaimsCollection.swift
Projects/Home/Sources/HomeState.swift
Projects/Home/Sources/Screens/Home.swift
Projects/Home/Sources/Screens/OtherService.swift
Projects/hCoreUI/Sources/ChatButtonView/ChatButtonView.swift
Projects/hCoreUI/Sources/hButton/hButton.swift

GEN-816: Home navigation items

---

Projects/TravelCertificate/Sources/Store/TravelInsuranceStore.swift
Projects/TravelCertificate/Sources/Views/ContractsScreen.swift
Projects/TravelCertificate/Sources/Views/ProcessingScreen.swift
Projects/TravelCertificate/Sources/Views/StartDateScreen.swift
Projects/TravelCertificate/Sources/Views/WhoIsTravelingScreen.swift
Projects/hCoreUI/Sources/hForm/hForm.swift

- Spacing
- animations
- delayed generating

Feature/app redesign/travel certificate fixes

---

Projects/Contracts/Sources/Contracts.swift
Projects/Contracts/Sources/Journeys/ContractDetail.swift
Projects/Contracts/Sources/Journeys/ContractInformation.swift
Projects/Contracts/Sources/Stores/ContractAction.swift
Projects/Contracts/Sources/View/UpcomingChangesScreen.swift
Projects/hCoreUI/Sources/hButton/hButton.swift

Feature/app redesign/update insurance details

---

Projects/Claims/Sources/Views/SubmitClaim/Entrypoints/SelectClaimEntrypoint.swift
Projects/Contracts/Sources/Journeys/ContractDetail.swift
Projects/Contracts/Sources/Journeys/TerminationFlowJourney.swift
Projects/Contracts/Sources/Models/TerminationFlowDateNextStepModel.swift
Projects/Contracts/Sources/Stores/ContractAction.swift
Projects/Contracts/Sources/Stores/ContractsStore.swift
Projects/Contracts/Sources/View/ContractTable.swift
Projects/Contracts/Sources/View/Termination/SetTerminationDate.swift
Projects/Contracts/Sources/View/Termination/TerminationDeleteScreen.swift
Projects/Payment/Sources/MyPayment.swift
Projects/hCoreUI/Sources/ActivityIndicatorView.swift

Updated activity indicator and retry view

---

Projects/Home/Sources/Screens/Home.swift
Projects/hCoreUI/Sources/ChatButtonView/ChatButtonView.swift
Projects/hCoreUI/Sources/ChatButtonView/ChatTooltipView.swift
Projects/hCoreUI/Sources/Journey+TabBarDot.swift
Projects/hCoreUI/Sources/Styling/DefaultStyling.swift
Projects/hCoreUI/Sources/hText/hText.swift

- Updated tooltip for chat
- Updated tab bar item appearance

Feature/app redesign/home navigation tooltip

---

Projects/Contracts/Sources/View/CrossSellingItem.swift
Projects/hCoreUI/Sources/Views/MarqueeText.swift

- Added Marquee label
- Changed cross sell subtitle to marquee label

Added marquee label

---

Projects/App/Sources/Screens/ProfileScreen/Screens/EuroBonus/ChangeEuroBonusView.swift
Projects/Forever/Sources/ChangeCodeView.swift
Projects/hCore/Sources/Masking.swift
Projects/hCoreUI/Sources/Views/TextInputView.swift

- Updated validation for eurobonus

Updated validation for eurobonus

---

Projects/Home/Sources/Components/ImportantMessagesView.swift
Projects/Home/Sources/HomeState.swift
Projects/Home/Sources/Screens/Home.swift
Projects/Home/Sources/Screens/OtherService.swift
Projects/hGraphQL/Sources/Models/CommonClaim.swift

Moved important message view logic

---

Projects/hCoreUI/Sources/Styling/DefaultStyling.swift
Projects/hCoreUI/Sources/hForm/hForm.swift

Fixed navigation bar height

---

Projects/App/Sources/Journeys/ClaimsJourney.swift

- Fixed cancel button on honesty pledge

Fixed cancel button on honesty pledge

---

Projects/App/Sources/Screens/ProfileScreen/Screens/EuroBonus/ChangeEuroBonusView.swift

- Dismiss success screen after success change of SAS euro bonus code

Dismiss success screen after success change of SAS euro bonus code

---

Projects/Contracts/Sources/Journeys/MovingFlow/MovingFlowIntro.swift
Projects/hCoreUI/Sources/Views/DetailsTableView.swift
Projects/hCoreUI/Sources/hForm/hRow.swift

- Updated already moving flow screen

Updated already moving screen

---

Projects/App/Sources/Screens/ProfileScreen/Screens/MyInfo/MyInfoView.swift

- Added save button on my info view

Added save button on my info view

---

Projects/App/Sources/Journeys/MovingFlowJourney.swift

- Fix x button to work on insurance --> edit --> moving flow --> open free text chat

fix x button to work

---

Projects/Forever/Sources/DiscountCodeSection.swift
Projects/Forever/Sources/Forever.swift
Projects/Forever/Sources/ForeverStore.swift

Fixed forever share text

---

Projects/App/Sources/Journeys/ChatJourney.swift
Projects/App/Sources/UgglanStore.swift
Projects/hCoreUI/Sources/Views/RetryView.swift
Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift

- Added "disable_chat" flag in hAnalytics
- Added error message when chat is disabled

GEN-1100: Added flag + UI

---

Projects/App/Sources/Screens/ChatScreen/Reusables/Message+Reusable.swift

GEN-1120: Update chat message size

---

Projects/App/Sources/Screens/ChatScreen/Reusables/Message+Reusable.swift

- Fixed message height calculation

Fixed message height calculation

---

Projects/App/Sources/AppDelegate.swift
Projects/App/Sources/Journeys/LoginJourney.swift
Projects/Market/Sources/LanguageAndMarketPickerView.swift
Projects/Market/Sources/Screens/NotLoggedIn/NotLoggedInView.swift

- Fix crash on login with email
- Fix segmenet controll on language
- Fix logout animation

Fixed crash on email; animations fix;

---

Projects/App/Sources/Journeys/LoggedInJourney.swift
Projects/App/Sources/Journeys/MovingFlowJourney.swift
Projects/MoveFlow/Sources/Journey.swift
Projects/MoveFlow/Sources/Store/MoveFlowStore.swift
Projects/MoveFlow/Sources/View/MovingFlowFailure.swift
Projects/MoveFlow/Sources/View/MovingFlowHousingType.swift
Projects/hCoreUI/Sources/ActivityIndicatorView.swift
Projects/hCoreUI/Sources/Views/RetryView.swift

GEN-1191: Updated moving flow error view

---

Projects/hGraphQL/Sources/ApolloClient.swift

Fixed upload file authorization

Fixed authorization header for upload files

---

Projects/Profile/Sources/Views/Screens/Profile/Profile.swift

- Merge bottom content with content on profile

Added fix for profile content size

---

Projects/Contracts/Sources/Models/ContractModels.swift

- Fixed active in future logic
- Fixed is terminated logic

Fixed contract status calculation

---

Projects/TravelCertificate/Sources/Views/ContractsScreen.swift
Projects/TravelCertificate/Sources/Views/StartDateScreen.swift

- Updated contracts list for travel certificate
- Removed info if more contracts involved

Fixed travel certificate contracts view + removed info if has multiple contracts

---

Projects/Contracts/Sources/Contracts.swift
Projects/Contracts/Sources/Stores/ContractAction.swift
Projects/Contracts/Sources/Stores/ContractsStore.swift

- Fixed contracts pull to refresh

Fixed contracts pull to refresh

---

Projects/Contracts/Sources/Models/ContractModels.swift
Projects/Contracts/Sources/Stores/ContractAction.swift

- Show edit info only if there are options for it

Updated show edit info logic

---

Projects/App/Sources/AppDelegate+Deeplinks.swift
Projects/hCore/Sources/UIApplication+GetTopViewController.swift

- Fixed opening app from connect-payment deeplink

Connect payment deeplink not showing when opened closed app

---

Projects/Claims/GraphQL/Octopus/Claims.graphql
Projects/Claims/Sources/Models/ClaimModel.swift
Projects/Claims/Sources/Views/ClaimDetailView.swift
Projects/Claims/Sources/Views/ClaimStatus.swift
Projects/hGraphQL/Sources/Models/MonetaryAmount.swift

- Added payout handling for claim

Added payout amount handling for claim

---

Projects/hCoreUI/Sources/Toasts.swift

GEN-1362: Fix toast interaction

---

Projects/hCoreUI/Sources/hButton/hButton.swift
Projects/hCoreUI/Sources/hForm/hSection.swift

GEN-1364: Updated shadow generating on the butotn

---

Projects/Contracts/Sources/Journeys/ContractDetail.swift
Projects/Contracts/Sources/Journeys/ContractDocuments.swift
Projects/Contracts/Sources/Journeys/ContractInformation.swift
Projects/hCoreUI/Sources/InsurableLimits/InsurableLimits.swift
Projects/hCoreUI/Sources/PerilCollection/PerilCollection.swift
Projects/hCoreUI/Sources/hColor/Color+UIColor.swift

- Updated contract details overview
- Updated contract details coverage
- Updated contract details documents

GEN-1325: Updated contract details layout

---

Projects/Claims/Sources/Views/SubmitClaim/SubmitClaimSuccessScreen.swift
Projects/Forever/Sources/Header.swift

GEN-1339-update new success screen

---

Projects/Home/GraphQL/Octopus/CommonClaims.graphql
Projects/Home/Sources/CommonClaim.swift
Projects/Home/Sources/HomeState.swift
Projects/MoveFlow/Sources/View/MovingFlowHousingType.swift

- Fixed common claims query
- Moving flow error got lost durring PRs

Fixed common claim query + moving flow error

---

Projects/App/GraphQL/Giraffe/UpdateLanguage.graphql
Projects/App/GraphQL/Octopus/UpdateLanguage.graphql
Projects/App/Sources/AppDelegate+UpdateLanguageMutation.swift

Moved update language to octopus

---

Projects/App/Sources/Screens/ClaimsScreen/Screens/ClaimFlowAskForPushnotifications.swift
Projects/hCoreUI/Sources/hForm/hForm.swift

GEN-1333: Updated notifications screen

---

Projects/Profile/GraphQL/Octopus/MemberDeletionRequest.graphql
Projects/Profile/Sources/Store/ProfileAction.swift
Projects/Profile/Sources/Views/Screens/DeleteAccount/DeleteAccountView.swift
Projects/Profile/Sources/Views/Screens/DeleteAccount/DeleteAccountViewModel.swift
Projects/Profile/Sources/Views/Screens/DeleteAccount/DeleteRequestLoadingView.swift
Projects/hCoreUI/Sources/hForm/hForm.swift

Updated delete account

---

Projects/App/Sources/AppDelegate.swift
Projects/Payment/GraphQL/Octopus/MemberReferralInformationCodeUpdatePayment.graphql
Projects/Payment/Sources/Models/PaymentData.swift
Projects/Payment/Sources/Models/PaymentDiscountsData.swift
Projects/Payment/Sources/PaymentStore.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetails.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsDiscount.swift
Projects/Payment/Sources/Screens/PaymentDiscounts/AddCampaingCodeView.swift
Projects/Payment/Sources/Screens/PaymentDiscounts/ChangeCodeView.swift
Projects/Payment/Sources/Screens/PaymentDiscounts/DeleteCampaignView.swift
Projects/Payment/Sources/Screens/PaymentDiscounts/PaymentsDiscountsView.swift
Projects/Payment/Sources/Screens/PaymentDiscounts/ReferralsView.swift
Projects/Payment/Sources/Screens/PaymentsView.swift
Projects/Payment/Sources/Services/CampaignsService.swift
Projects/Payment/Sources/Services/ForeverCodeService.swift
Projects/Payment/Sources/Services/PaymentService.swift
Projects/hCoreUI/Sources/Views/SuccessScreen.swift
Projects/hCoreUI/Sources/Views/TextInputView.swift
Projects/hGraphQL/Sources/Apollo Extensions/ApolloClient+Fetch.swift

GEN-1404: Discounts view

---

Projects/Home/Sources/Screens/HomeBottomScrollView.swift
Projects/Profile/GraphQL/Octopus/hGraphQL
Projects/hCoreUI/Sources/Views/InfoCardScrollView.swift

- fixed issue with home elements jumping on bottom scroll list update
https://github.com/HedvigInsurance/ugglan/assets/127749787/8e5afcf7-0170-4af4-8949-8ab8f146a59e

Fixed home screen content jumping

---

Projects/App/Sources/Journeys/LoggedInJourney.swift
Projects/Contracts/Sources/Contracts.swift
Projects/Contracts/Sources/Journeys/EditCoInsuredJourney.swift

Fixed CoInsuredMissingAlertView from home handinling

---

Projects/Contracts/Sources/Journeys/EditCoInsuredJourney.swift
Projects/hCoreUI/Sources/NavigationView+Title.swift

- Added handling of navigation title when there are more lines

Updated navigation title

---

Projects/App/Sources/AppDelegate+Deeplinks.swift
Projects/App/Sources/Screens/ChatScreen/Models/Message.swift
Projects/App/Sources/Screens/ChatScreen/Reusables/Message+Reusable.swift
Projects/Forever/Sources/Components/InivtationTable.swift
Projects/Payment/GraphQL/Octopus/DiscountsData.graphql
Projects/Payment/GraphQL/Octopus/PaymentData.graphql
Projects/Payment/Sources/Models/PaymentData.swift
Projects/Payment/Sources/Screens/ConnectPayments/PaymentSetup.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetails.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsContractDetails.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsDiscount.swift
Projects/Payment/Sources/Screens/PaymentDiscounts/AddCampaingCodeView.swift
Projects/Payment/Sources/Screens/PaymentDiscounts/PaymentsDiscountsView.swift
Projects/Payment/Sources/Screens/PaymentsHistoryView.swift
Projects/Payment/Sources/Screens/PaymentsView.swift
Projects/Payment/Sources/Services/PaymentService/PaymentData+octopus.swift
Projects/Payment/Sources/Services/PaymentService/PaymentDiscountData+octopus.swift
Projects/Payment/Sources/Services/PaymentService/PaymentHistoryData+octopus.swift
Projects/Payment/Sources/Services/PaymentService/PaymentServiceDemo.swift
Projects/hCore/Sources/Date+Calendar.swift
Projects/hCore/Sources/DeepLink.swift
Projects/hCore/Sources/MonetaryAmount.swift
Projects/hCoreUI/Sources/DeepLink+Title.swift
Projects/hCoreUI/Sources/HedvigColors.swift
Projects/hCoreUI/Sources/Toasts.swift

- added deeplink
Tets session feedback fixes:
-  Add Outstanding payment in history list if missed payment
- Discount shows negative value in discounts and payment details
- Campaign shows affected insurances in the Discounts (skipped this in payment details)

Feature/new payment details/feedback fixes

---

Projects/Contracts/Sources/Journeys/ContractInformation.swift
Projects/Contracts/Sources/View/CoInsured/AlreadyExistingCoInsured/InsuredPeopleScreen.swift
Projects/Contracts/Sources/View/CoInsured/EditCoInsuredDisplayFields.swift
Projects/Contracts/Sources/View/CoInsured/NewCoInsured/InsuredPeopleNewScreen.swift
Projects/Contracts/Sources/View/CoInsured/NewCoInsured/RemoveCoInsuredScreen.swift

- Added property to contract field to check if divider should be applied or not

add property to check if there is content under contract field

---

Projects/Contracts/Sources/View/CoInsured/CoInsuredSelectScreen.swift
Projects/hCoreUI/Sources/CheckboxPickerScreen.swift
Projects/hCoreUI/Sources/hButton/hButton.swift

- Added fix when we want to add co insured from another insurance ( selected co insured doesn't disappear from the list)

Fix for add co insured from another insruance

---

Projects/App/Sources/Screens/ChatScreen/ChatState.swift
Projects/hCoreUI/Sources/Toasts.swift

- Updated push notifications toast
[Figma](https://www.figma.com/file/WlwFCAWywXNcXVgPfYVmWu/Final-Design?type=design&node-id=7142-12159&mode=design&t=xyHQObDgjSss1ivQ-0)

Updated push notification toast for chat

---

Projects/hCoreUI/Sources/hForm/hDatePickerField.swift

- Added small field to date picker

Updated date picker field

---

Projects/App/Sources/Screens/UpdateAppScreen/UpdateAppView.swift

- Updated "AppUpdateView" to error view

Updated "AppUpdateView" to error view

---

Projects/App/Sources/Journeys/CoInsuredJourney.swift
Projects/App/Sources/Journeys/LoggedInJourney.swift
Projects/Contracts/Sources/Contracts.swift
Projects/Contracts/Sources/EditContract.swift
Projects/Contracts/Sources/Journeys/ContractInformation.swift
Projects/Contracts/Sources/Journeys/EditCoInsuredJourney.swift
Projects/Contracts/Sources/Stores/ContractAction.swift
Projects/Contracts/Sources/View/CoInsured/AlreadyExistingCoInsured/InsuredPeopleScreen.swift
Projects/Contracts/Sources/View/CoInsured/CoInsuredSelectScreen.swift
Projects/Contracts/Sources/View/CoInsured/EditCoInsuredDisplayFields.swift
Projects/Contracts/Sources/View/CoInsured/NewCoInsured/CoInsuredInfoView.swift
Projects/Contracts/Sources/View/CoInsured/NewCoInsured/CoInsuredMissingAlertView.swift
Projects/Contracts/Sources/View/CoInsured/NewCoInsured/InsuredPeopleNewScreen.swift
Projects/Contracts/Sources/View/CoInsured/NewCoInsured/RemoveCoInsuredScreen.swift
Projects/Home/Sources/HomeState.swift
Projects/Home/Sources/Screens/Home.swift
Projects/Home/Sources/Screens/HomeBottomScrollView.swift
Projects/hCoreUI/Sources/CheckboxPickerScreen.swift

- Added configuration for edit co insured

Add configuration to communicate with edit co insured

---

Projects/Payment/Sources/Screens/PaymentDetails/PaymentStatusView.swift

- Updated image colour for pending
- Updated copy for pending to be as one in figma

Updated payment status

---

Projects/App/Sources/AppDelegate.swift
Projects/Claims/Sources/ClaimAction.swift
Projects/Claims/Sources/Journeys/ClaimJourneys.swift
Projects/Claims/Sources/Models/ClaimModel.swift
Projects/Claims/Sources/Services/FetchClaimService.swift
Projects/Claims/Sources/SubmitClaimAction.swift
Projects/Claims/Sources/Views/ClaimDetailView.swift
Projects/Claims/Sources/Views/SubmitClaim/IncidentInfo/SubmitClaimOccurrencePlusLocationScreen.swift
Projects/hCoreUI/Sources/hButton/hButton.swift
Projects/hCoreUI/Sources/hText/hText.swift

- Updated UI for claim details

GEN-1533: claim details update

---

Projects/App/Sources/AppDelegate.swift
Projects/App/Sources/Journeys/ClaimsJourney.swift
Projects/Claims/GraphQL/Octopus/Claims.graphql
Projects/Claims/Sources/Models/ClaimModel.swift
Projects/Claims/Sources/Models/File.swift
Projects/Claims/Sources/Services/FetchClaimService.swift
Projects/Claims/Sources/Services/UploadClaimFileService.swift
Projects/Claims/Sources/Views/ClaimDetailView.swift
Projects/Claims/Sources/Views/ClaimFilesView.swift
Projects/Claims/Sources/Views/ClaimStatus.swift
Projects/Claims/Sources/Views/FilesGridView.swift
Projects/hCore/Sources/Models/MimeType.swift
Projects/hCore/Sources/Networking/NetworkClient.swift
Projects/hGraphQL/Sources/Environment.swift
Projects/hGraphQL/Sources/TokenRefresher.swift

- Implemented  octopus service
review [this first](https://github.com/HedvigInsurance/ugglan/pull/1136)

Gen-1539: upload file service

---

Projects/Claims/Sources/Models/File.swift
Projects/Claims/Sources/Views/ClaimFilesView.swift
Projects/Claims/Sources/Views/FilesGridView.swift
Projects/hCoreUI/Sources/Views/DocumentPreview.swift

- Add open file from list
review [this](https://github.com/HedvigInsurance/ugglan/pull/1144) first

Feature/attach files to claim/added open file

---

Projects/App/Sources/Screens/ChatScreen/ChatState.swift
Projects/Home/GraphQL/Octopus/CommonClaims.graphql
Projects/Home/Sources/HomeState.swift
Projects/Home/Sources/Screens/Home.swift
Projects/hCoreUI/Sources/ChatButtonView/ChatButtonView.swift

GEN-1607: add notification badge on chat when new message is received

---

Projects/hCoreUI/Sources/hForm/hCounterField.swift

- UI fix for plus and minus sign alignment
- [Figma](https://www.figma.com/file/BbYyhe0vJe9Q8XTVMSdRPr/Design-QA?node-id=156%3A4568&mode=dev)

fix plus and minus sign to align

---

Projects/Home/Sources/Screens/HelpCenter/HelpCenterStartView.swift
Projects/Home/Sources/Screens/HelpCenter/HelpCenterTopicView.swift
Projects/Home/Sources/Screens/HelpCenter/ReusableComponents.swift

add logging for question click

---

Projects/App/Sources/AppDelegate+hAnalytics.swift
Projects/App/Sources/AppDelegate.swift
Projects/App/Sources/Journeys/LoginJourney.swift
Projects/Market/Sources/Screens/NotLoggedIn/NotLoggedInView.swift
Projects/Market/Sources/Screens/NotLoggedIn/NotLoggedViewModel.swift
Projects/hCore/Sources/ApplicationContext.swift
Projects/hGraphQL/Sources/ApolloClient.swift

- load experiments only for logged in user
- show login screen based on selected country (instead of relying on the hAnalytics)

RND-410: Removed loading experiments without token

---

Projects/hGraphQL/Sources/Apollo Extensions/ApolloClient+Fetch.swift

add graphql error logs

---

Projects/App/Sources/Journeys/CoInsuredJourney.swift
Projects/App/Sources/Journeys/MovingFlowJourney.swift
Projects/Contracts/Sources/Contracts.swift
Projects/Contracts/Sources/Journeys/ContractInformation.swift
Projects/Contracts/Sources/Models/ContractModels.swift
Projects/Contracts/Sources/View/ContractRow.swift

- Send fetch contracts when we have upcoming changes without url
- Fetch contracts when we dismiss move flow
- Fetch contracts when we dismiss edit co insured flow

GEN-1697: Added handling of missing url when we have upcoming agreement

---

Projects/Claims/Sources/ClaimMutation+Actions.swift
Projects/Claims/Sources/SubmitClaimStore.swift

- Setting up claim id on every mutation for claim flow
[slack](https://hedviginsurance.slack.com/archives/CPCUHMMJQ/p1705933860691149)
Fixed issue with "My trip abroad" -> "Sickness" -> "No"

Setting up claim id on every mutation for claim flow

---

Projects/TerminateContracts/Sources/Journeys/TerminationFlowJourney.swift
Projects/TerminateContracts/Sources/Store/TerminationContractStore.swift
Projects/TerminateContracts/Sources/TerminationMutation+Actions.swift
Projects/TerminateContracts/Sources/Views/SetTerminationDate.swift
Projects/TerminateContracts/Sources/Views/TerminationDeleteScreen.swift

- added handling of error screen

Updated termination flow error handling

---

Projects/App/Sources/DatadogLogger.swift
Projects/TerminateContracts/Sources/Store/TerminationContractStore.swift
Projects/TerminateContracts/Sources/Views/ReusableComponents.swift
Projects/TerminateContracts/Sources/Views/TerminationSuccessScreen.swift
Projects/hCoreUI/Sources/Views/InfoExpandableView.swift
Projects/hGraphQL/Sources/Log.swift

Feature/termination flow/add logging

---

Projects/App/Sources/AppDelegate+Deeplinks.swift
Projects/App/Sources/Journeys/LoggedInJourney.swift
Projects/Chat/GraphQL/Octopus/Chat.graphql
Projects/Chat/Sources/ChatJourney.swift
Projects/Chat/Sources/ChatStore.swift
Projects/Chat/Sources/Models/Chat.swift
Projects/Chat/Sources/Services/DemoImplementation/ChatDemoClient.swift
Projects/Chat/Sources/Services/OctopusImplementation/FetchMessagesClientOctopus.swift
Projects/Chat/Sources/Services/Protocols/ChatUploadFileClient.swift
Projects/Chat/Sources/Views/ChatScreen.swift
Projects/Chat/Sources/Views/ChatScreenViewModel.swift
Projects/hCore/Sources/DeepLink.swift
Projects/hCore/Sources/Markdown+typealias.swift
Projects/hCoreUI/Sources/MarkdownTextView.swift
Projects/hCoreUI/Sources/Views/InfoCard.swift

- added banner message to the chat

Gen-1721: banner message

---

Projects/Profile/GraphQL/Octopus/Profile.graphql
Projects/Profile/Project.swift
Projects/Profile/Sources/Store/ProfileAction.swift
Projects/Profile/Sources/Store/ProfileState.swift
Projects/Profile/Sources/Store/ProfileStore.swift
Projects/Profile/Sources/Views/Components/ProfileRow.swift
Projects/Profile/Sources/Views/Components/ProfileRowType.swift
Projects/Profile/Sources/Views/Screens/Profile/Profile.swift

Added option in the profile for travel certificates

GEN-1756: add profile option

---

Projects/Contracts/Sources/Models/ContractModels.swift
Projects/Home/Sources/Components/FutureSectionView.swift
Projects/Home/Sources/Components/RenewalCard.swift
Projects/Home/Sources/HomeState.swift
Projects/hGraphQL/GraphQL/Octopus/Agreement.graphql

- Add supportsTravelCertificate to contract

add supportsTravelCertificate

---

Projects/ExampleUtil/Sources/MonetaryAmount+Runtime.swift
Projects/Forever/Example/Sources/ForeverInvitation.State+Runtime.swift
Projects/Forever/Example/Sources/MonetaryAmount+Runtime.swift
Projects/hCoreUI/Sources/hColor/hColor.swift
Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift

Removed runtime

---

Projects/Claims/Sources/Views/SubmitClaim/SummaryInfo/SubmitClaimSummaryScreen.swift
Projects/Contracts/Sources/Journeys/ContractInformation.swift
Projects/EditCoInsured/Sources/Models/CoInsuredModel.swift
Projects/EditCoInsured/Sources/View/CoInusuredInput.swift
Projects/MoveFlow/Sources/Model/MovingFlowModel.swift
Projects/MoveFlow/Sources/View/MovingFlowSuccess.swift
Projects/hCore/Sources/DateFormat/Date+LocalDateString.swift
Projects/hCore/Sources/DateFormat/String+toDate.swift
Projects/hCore/Sources/Masking.swift
Projects/hCore/Sources/Models/ServerBasedDate.swift
Projects/hCoreUI/Sources/hForm/hDatePickerField.swift

- Date refactoring and cleaning

Date refactoring and cleaning

---

Projects/Authentication/Sources/OTP/OpenEmailClientButton.swift
Projects/Profile/Sources/Views/Screens/AppInfo/AppInfoView.swift

- Added submit bug button
- [Notion](https://www.notion.so/hedviginsurance/a4c35052b6794b36a4b0d58b537cc325?v=c74a8cb958ab4ba6ba4c904d8540b106&p=7c6dccd0c9ed420faf59c0c03aaa0736&pm=s)

GEN-1814: Add submit bug button

---

Projects/Home/Sources/HomeState.swift
Projects/Home/Sources/Screens/Home.swift
Projects/TravelCertificate/Sources/Services/TravelInsuranceClientOctopus.swift

[Notion](https://www.notion.so/hedviginsurance/a4c35052b6794b36a4b0d58b537cc325?v=c74a8cb958ab4ba6ba4c904d8540b106&p=4670b0d950d546159b4d9430eb518b0b&pm=s)

Updated "Help center" and "Chat" on/off logic

---

Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift

Includes this commit https://github.com/HedvigInsurance/authlib/commit/617e0c5a028c06cc4af8f251cb270f350eaeb1c5 
Context:
https://hedviginsurance.slack.com/archives/C03U9C6Q7TP/p1708349732606569

Bump authlib

---

Projects/App/Sources/Journeys/LoggedInJourney.swift
Projects/Claims/Sources/ClaimMutation+Actions.swift
Projects/Claims/Sources/Journeys/ClaimJourneys.swift
Projects/Claims/Sources/SubmitClaimAction.swift
Projects/Claims/Sources/SubmitClaimState.swift
Projects/Claims/Sources/SubmitClaimStore.swift
Projects/Claims/Sources/Views/SubmitClaim/AudioRecording/SubmitClaimAudioRecordingScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/ClaimLoadingViewWithGenericError.swift
Projects/Claims/Sources/Views/SubmitClaim/Emergency/SumitClaimEmergencySelectScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/Entrypoints/SelectClaimEntrypoint.swift
Projects/Claims/Sources/Views/SubmitClaim/FilesUpload/FilesUploadScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/IncidentInfo/SubmitClaimOccurrencePlusLocationScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/SingleItem/SubmitClaimSingleItem.swift
Projects/Claims/Sources/Views/SubmitClaim/SubmitClaimContactScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/SummaryInfo/SubmitClaimSummaryScreen.swift
Projects/Claims/Sources/Views/submitClaim/Checkout/SubmitClaimCheckoutNoRepairScreen.swift
Projects/TerminateContracts/Sources/Journeys/TerminationFlowJourney.swift
Projects/TerminateContracts/Sources/Views/TerminationDeleteScreen.swift
Projects/hCoreUI/Sources/ActivityIndicatorView.swift

- Update to new error screen design in claims flow
- Added retry action in claims flow error screen

update design for error screen in claims flow

---

Projects/Authentication/Sources/SEBankID/BankIDLoginQR.swift
Projects/Authentication/Sources/Store/AuthenticationAction.swift
Projects/Authentication/Sources/Store/AuthenticationState.swift
Projects/Authentication/Sources/Store/AuthenticationStore.swift
Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift

- updated library
- updated code to support dynamic qr code (with a delay so it doesn't happen to fast)

GEN-1867: Update bank id to v6

---

Projects/Home/Sources/Screens/HelpCenter/HelpCenterStartView.swift
Projects/Home/Sources/Screens/HelpCenter/ReusableComponents.swift
Projects/hCoreUI/Sources/hForm/hRow.swift

Add haptic feedback for hRow

---

Projects/Claims/Sources/Models/FlowClaimPhoneNumberStepModel.swift
Projects/Claims/Sources/Views/SubmitClaim/SubmitClaimContactScreen.swift
Projects/hCore/Sources/String+isPhoneNumber.swift

- Added validation for phone number

Added phone number validation for claim phone number

---

Projects/hCoreUI/Sources/Document.swift

- fixed bug when trying to "Save to Files"

Fixed "Save to Files"

---

Projects/App/Sources/AppDelegate+Deeplinks.swift

- open help center when app is killed

Open help-center with deep link when app is killed

---

Projects/App/Sources/Journeys/LoggedInJourney.swift
Projects/App/Sources/Journeys/OnboardingJourney.swift
Projects/App/Sources/Journeys/WebRedirectJourney.swift

- Open "Get a price quote" and cross sell links directly in safari

Moved get a price and cross sell to open in safari

---

Projects/App/Project.swift
Projects/Market/Sources/Bundle+module.swift
Projects/hCoreUI/Project.swift
Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift
Tuist/ProjectDescriptionHelpers/Project+Templates.swift
swiftgen.yml

- Removed generating assets when not necessary

Updated tuist generating options

---

Projects/Claims/Sources/Models/FlowClamSingleItemStepModel.swift

- If possible and we have any matching name from availableModels with current device, prefill this under model

GEN-1922: prefill model name

---

Projects/Claims/Sources/Models/FlowClamSingleItemStepModel.swift
Projects/EditCoInsured/Sources/Services/OctopusImplementation/EditCoInsuredServiceOctopus.swift
Projects/EditCoInsured/Sources/Stores/EditCoInsuredStore.swift
Projects/EditCoInsured/Sources/View/CoInusuredInput.swift
Projects/hCore/Sources/Helpers/GraphQLErrors+description.swift

- Edit co insured errors handling

Updated errors handling for co insured

---

Projects/App/Sources/Journeys/FeaturesLoader.swift
Projects/Contracts/Sources/Contracts.swift
Projects/Contracts/Sources/Stores/ContractAction.swift
Projects/Contracts/Sources/Stores/ContractsStore.swift
Projects/Forever/Sources/Forever.swift
Projects/Payment/Sources/Screens/PaymentsView.swift
Projects/Profile/Sources/Views/Screens/Profile/Profile.swift
Projects/hCoreUI/Sources/Refreshable.swift
Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift

- Updated refresh control
- Added refresh control to forever
- Added refresh control to payments

Updated refresh control

---

Projects/Payment/Sources/Models/PaymentData.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsView.swift
Projects/Payment/Sources/Screens/PaymentsHistoryView.swift
Projects/Payment/Sources/Screens/PaymentsView.swift
Projects/Payment/Sources/Services/PaymentService/PaymentData+octopus.swift
Projects/Payment/Sources/Services/PaymentService/PaymentServiceOctopus.swift

- Fill PaymentDetails with info

fill PaymentDetails and change wrong text color

---

Projects/EditCoInsured/Sources/View/CoInusuredInput.swift
Projects/hCore/Sources/Masking.swift
Projects/hCoreUI/Sources/hForm/hFloatingTextField.swift
Projects/hCoreUI/Sources/hForm/hTextField.swift

Added ssn with 12 digits

---

Projects/Chat/Sources/Views/ChatInputView.swift
Projects/Claims/Sources/Models/ImagePicker.swift
Projects/hCore/Sources/Models/File.swift

- When uploading .heic from the Files, convert it to the jpeg

Added handling if the heic when selected from the files

---

Projects/hGraphQL/Sources/TokenRefresher.swift

- Fixed issue with refreshing token that left member with loading indicator screen
- Replaced Flow with Combine

GEN-2042: refactor token refresher

---

Projects/Claims/Sources/Services/OctopusImplementation/SubmitClaimServiceOctopus.swift

GEN-2029: Added supported steps for the claim flow

---

Projects/App/Sources/Journeys/LoggedInJourney.swift
Projects/Home/Sources/Screens/Home.swift
Projects/TerminateContracts/GraphQL/Octopus/FlowTerminationSurveyNext.graphql
Projects/TerminateContracts/GraphQL/Octopus/TerminationStartFlow.graphql
Projects/TerminateContracts/Sources/Journeys/TerminationFlowJourney.swift
Projects/TerminateContracts/Sources/Models/TerminationFlowDeletionNextModel.swift
Projects/TerminateContracts/Sources/Models/TerminationFlowSuccessNextModel.swift
Projects/TerminateContracts/Sources/Service/DemoImplementation/TerminateContractsDemoService.swift
Projects/TerminateContracts/Sources/Service/OctopusImplementation/TerminateContractsServiceOctopus.swift
Projects/TerminateContracts/Sources/Service/Protocols/TerminateContractsService.swift
Projects/TerminateContracts/Sources/Store/TerminationContractStore.swift
Projects/TerminateContracts/Sources/Views/ConfirmTerminationScreen.swift
Projects/TerminateContracts/Sources/Views/TerminationSurveyScreen.swift
Projects/hCoreUI/Sources/SwiftUI+Hero.swift
Projects/hCoreUI/Sources/hColor/hColor.swift
Projects/hCoreUI/Sources/hForm/hForm.swift
Projects/hCoreUI/Sources/hForm/hTextView.swift

GEN-2075: termination survey schema

---

Projects/App/Sources/AppDelegate+Notifications.swift
Projects/App/Sources/AppDelegate.swift
Projects/App/Sources/Generic/Extensions/UIApplication+AppDelegate.swift
Projects/App/Sources/Journeys/ClaimsJourneyMain.swift
Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/App/Sources/Screens/ClaimsScreen/Screens/ClaimFlowAskForPushnotifications.swift
Projects/Chat/Sources/ChatStore.swift
Projects/Chat/Sources/Navigation/ChatNavigation.swift
Projects/Chat/Sources/Views/ChatScreen.swift
Projects/Chat/Sources/Views/ChatScreenViewModel.swift
Projects/Claims/Sources/Navigation/ClaimsNavigation.swift
Projects/Claims/Sources/SubmitClaimAction.swift
Projects/Home/Sources/Navigation/HomeNavigation.swift
Projects/Profile/Sources/Store/ProfileAction.swift
Projects/Profile/Sources/Views/Components/NotificationsCardView.swift
Projects/Profile/Sources/Views/Screens/SettingsScreen/SettingsScreen.swift
Projects/hCore/Sources/NotificationCenter+NotificationName.swift
Projects/hCoreUI/Sources/DetentRouter.swift
Projects/hCoreUI/Sources/Router.swift

- Support push notifications in new navigation

add support for push notifications

---

Projects/Claims/Sources/Views/SubmitClaim/SubmitClaimContactScreen.swift
Projects/Home/Sources/Models/Questions.swift
Projects/Home/Sources/Screens/HelpCenter/HelpCenterStartView.swift
Projects/Home/Sources/Screens/HelpCenter/ReusableComponents.swift
Projects/hCoreUI/Sources/Views/KeyboardObserver.swift
Projects/hCoreUI/Sources/hForm/hFloatingTextField.swift
Projects/hCoreUI/Sources/hForm/hForm.swift

- Added search controller
- Filter quick actions and all questions

GEN-2104: Makerdays/help center search

---

Projects/EditCoInsured/Sources/Services/OctopusImplementation/EditCoInsuredServiceOctopus.swift
Projects/EditCoInsured/Sources/View/CoInusuredInput.swift

- Show error if we try to fetch underaged or hidden SSN information

GEN-2110: Added handling of underaged ssn

---

Projects/Forever/Sources/DiscountCodeSection.swift
Projects/Forever/Sources/Navigation/ForeverNavigation.swift
Projects/TravelCertificate/Sources/Views/TravelCertificateProcessingScreen.swift
Projects/hCoreUI/Sources/ActivityView.swift

- fixed iPad share code crash
- Fixed download travel certificate iPad crash

Added support for iPad activity view

---

Projects/Authentication/Sources/OTP/OTPCodeDisplay.swift
Projects/Authentication/Sources/OTP/OTPCodeLoadingOverlay.swift
Projects/Claims/Sources/AudioTrack/OverlayView.swift
Projects/Claims/Sources/AudioTrack/PlaybackFailedView.swift
Projects/Claims/Sources/AudioTrack/TrackPlayer.swift
Projects/Claims/Sources/Views/SubmitClaim/SummaryInfo/SubmitClaimEditSummaryScreen.swift
Projects/Claims/Sources/Views/submitClaim/Checkout/SubmitClaimCheckoutScreen.swift
Projects/Claims/Sources/Views/submitClaim/Checkout/SubmitClaimCheckoutTransferringScreen.swift
Projects/TerminateContracts/Sources/Views/SetTerminationDateLandingScreen.swift
Projects/hCoreUI/Sources/DetentRouter.swift
Projects/hCoreUI/Sources/Pill/hPill.swift
Projects/hCoreUI/Sources/PresentationStyle+Detented.swift
Projects/hCoreUI/Sources/Styling/DefaultStyling.swift
Projects/hCoreUI/Sources/Tooltip/Tooltip.swift
Projects/hCoreUI/Sources/Views/InfoCard.swift
Projects/hCoreUI/Sources/hButton/hButton.swift
Projects/hCoreUI/Sources/hColor/hColor.swift
Projects/hCoreUI/Sources/hForm/hFieldBackground.swift
Projects/hCoreUI/Sources/hForm/hSection.swift

- Added corner radius as an extension on the CGFloat
- Updated some of them
- Rework all of them when updating elements

GEN-2169: Corner radiueses

---

Projects/Claims/Sources/AudioTrack/OverlayView.swift
Projects/Claims/Sources/AudioTrack/TrackPlayer.swift
Projects/Claims/Sources/Models/FlowClaimAudioRecordingStepModel.swift
Projects/Claims/Sources/Views/SubmitClaim/AudioRecording/AudioRecorder.swift
Projects/Claims/Sources/Views/SubmitClaim/AudioRecording/RecordButton.swift
Projects/Claims/Sources/Views/SubmitClaim/AudioRecording/SubmitClaimAudioRecordingScreen.swift
Projects/hCore/Sources/GaussianDistGenerator.swift
Projects/hCoreUI/Sources/WaveformView.swift
Projects/hCoreUI/Sources/hForm/hSection.swift

- Updated audio components
- Updated shadow

GEN-2187 & GEN-2170:Updated voice memo + shadows

---

Projects/Contracts/Sources/Journeys/ContractCoverage.swift
Projects/hCoreUI/Sources/PerilCollection/PerilCollection.swift

GEN-2177: Update peril design

---

Projects/TerminateContracts/Sources/Views/SetTerminationDateLandingScreen.swift
Projects/hCoreUI/Sources/hForm/RadioFields/hRadioField.swift
Projects/hCoreUI/Sources/hForm/hCounterField.swift
Projects/hCoreUI/Sources/hForm/hDatePickerField.swift
Projects/hCoreUI/Sources/hForm/hFieldBackground.swift
Projects/hCoreUI/Sources/hForm/hFloatingField.swift
Projects/hCoreUI/Sources/hForm/hFloatingTextField.swift
Projects/hCoreUI/Sources/hText/hText.swift

GEN-2162 GEN-2163: Updated fields + counter

---

Projects/App/Sources/AppDelegate+Notifications.swift
Projects/App/Sources/AppDelegate.swift
Projects/Authentication/Sources/OTP/OTPResendCode.swift
Projects/Chat/Sources/Navigation/ChatNavigation.swift
Projects/Chat/Sources/Views/ChatScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/Deflect/SubmitClaimDeflectScreen.swift
Projects/Forever/Sources/DiscountCodeSection.swift
Projects/Profile/Sources/Views/Screens/AppInfo/AppInfoView.swift
Projects/Profile/Sources/Views/Screens/MyInfo/MyInfoView.swift
Projects/Profile/Sources/Views/Screens/SettingsScreen/MemberSubscriptionPreferenceView.swift
Projects/hCore/Sources/UIDevice+modelName.swift
Projects/hCoreUI/Sources/Toasts.swift
Projects/hCoreUI/Sources/Views/InfoCard.swift
Projects/hCoreUI/Sources/Views/NotificationStyle.swift

- Notification badge
- Info card

GEN-2174: Notification badge and info card

---

Projects/App/Sources/AppDelegate+Notifications.swift
Projects/App/Sources/AppDelegate.swift
Projects/App/Sources/Journeys/MainNavigationJourney.swift

- Only register when member is logged in 
- Invalidate token after members logout

Better APNS handling

---

Projects/App/Sources/Journeys/LoggedInNavigation.swift

- When you click on the tabBarItem of already selected tab, it should pop to root
Steps to reproduce:
1. Click on insurances tab
2. Open insurance details
3. Click on insurance tab
Result: should pop to Insurances root

Mimic normal behaviour on tabBarItem click

---

Projects/Contracts/Sources/Journeys/ContractCoverage.swift
Projects/Contracts/Sources/View/CrossSellingItem.swift
Projects/Contracts/Sources/View/CrossSellingStack.swift
Projects/hCoreUI/Sources/PerilCollection/PerilCollection.swift
Projects/hCoreUI/Sources/Views/BackgroundColorAnimation.swift

- Fix "cross sell" design
- [Figma](https://www.figma.com/design/5kmmDdh6StpXzbEfr7WevV/Hedvig-UI-Kit?node-id=16286-20578&m=dev)
- Fix animation for peril

GEN-2231: misc

---

Projects/Claims/Sources/Views/ClaimFilesView.swift
Projects/Claims/Sources/Views/submitClaim/Checkout/SubmitClaimCheckoutTransferringScreen.swift
Projects/hCoreUI/Sources/Views/ProcessingView.swift

- Updated loader (added style)

GEN-2229: Improvement/new design system/loader

---

Projects/hCoreUI/Sources/Styling/DefaultStyling.swift

GEN-2184: Tab bar upadate

---

Projects/Claims/Sources/Views/ClaimStatus.swift
Projects/Home/Sources/Screens/HelpCenter/ReusableComponents.swift
Projects/hCoreUI/Sources/Pill/hPill.swift
Projects/hCoreUI/Sources/hColor/hColor.swift

- Update hPill/highlight
- [Figma](https://www.figma.com/design/5kmmDdh6StpXzbEfr7WevV/Hedvig-UI-Kit?node-id=15981-25881&m=dev)

GEN-2180: highlight

---

Projects/hCoreUI/Sources/PerilCollection/PerilCollection.swift
Projects/hCoreUI/Sources/Views/Accordion.swift

- [Figma](https://www.figma.com/design/5kmmDdh6StpXzbEfr7WevV/Hedvig-UI-Kit?node-id=15404-12544&m=dev)
- Made Peril reuse accordion

GEN-2178: Accordion

---

Projects/hCoreUI/Sources/DetentRouter.swift
Projects/hCoreUI/Sources/SwiftUI+Hero.swift
Projects/hCoreUI/Sources/hForm/hTextView.swift

GEN-2179: Text view 

---

Projects/TerminateContracts/Sources/Views/SetTerminationDateLandingScreen.swift
Projects/hCoreUI/Sources/Views/Dropdown.swift

- Added dropdown component
- [Figma](https://www.figma.com/design/5kmmDdh6StpXzbEfr7WevV/Hedvig-UI-Kit?node-id=15695-21636&m=dev)

GEN-2165: dropdown

---

Projects/Chat/Sources/Helpers/Message+UI.swift
Projects/Chat/Sources/Views/ChatFileView.swift
Projects/Chat/Sources/Views/ChatInputView.swift
Projects/Chat/Sources/Views/ChatScreen.swift
Projects/Chat/Sources/Views/ImagesView.swift
Projects/hCore/Sources/Models/MimeType.swift

- Updated chat colors and spacing

GEN-2186: chat redesign

---

Projects/Home/GraphQL/Octopus/ImportantMessages.graphql
Projects/Home/Sources/Components/ImportantMessagesView.swift
Projects/Home/Sources/Models/ImportantMessage.swift
Projects/Home/Sources/Service/OctopusImplementation/HomeClientOctopus.swift

- removed deprecated link propery
- replaced it with linkInfo

GEN-2457: Updated important message link handling

---

Projects/Chat/Sources/Service/DemoImplementation/ConversationsClientDemo.swift
Projects/Chat/Sources/Views/InboxView.swift

- Limited number of lines
- Updated alignment
- Updated spacing
- Updated priority

Updated layout for inbox

---

Projects/Contracts/Sources/Journeys/ContractCoverage.swift
Projects/Contracts/Sources/Journeys/ContractDetail.swift
Projects/Contracts/Sources/Journeys/ContractDocuments.swift
Projects/Contracts/Sources/Service/DemoImplemenmtation/ContractsClientDemo.swift
Projects/Contracts/Sources/View/ScrollableSegmentedView.swift

- Added custom segmented view for insurance details
- Added scrolling between segments
- Added animation when moving to different segment

Added custom SegmentedView for insurance details

---

Projects/Claims/Sources/Views/SubmitClaim/AudioRecording/AudioRecorder.swift
Projects/Claims/Sources/Views/SubmitClaim/AudioRecording/RecordButton.swift

- Added border to the record button - updated recent in the design
- Fixed animations on the record button

Small UI fixes for audio recording

---

Projects/Chat/GraphQL/Octopus/Conversations.graphql
Projects/Chat/Sources/Models/Conversation.swift
Projects/Chat/Sources/Service/DemoImplementation/ConversationsClientDemo.swift
Projects/Chat/Sources/Service/OctopusImplementation/ConversationsClientOctopus.swift
Projects/Chat/Sources/Service/Protocols/ConversationClient.swift
Projects/Chat/Sources/Views/InboxView.swift
Projects/Claims/Sources/Views/ClaimDetailView.swift
Projects/Claims/Sources/Views/ClaimStatus.swift
Projects/hGraphQL/GraphQL/Octopus/ConversationFragment.graphql

- Stop query title and subtitle from conversation
- Added logic to handle this locally

remove title and subtitle from backend and update local logic for it

---

Projects/Claims/Sources/Claims.swift
Projects/Claims/Sources/Views/ClaimStatusCard.swift
Projects/Contracts/Sources/Journeys/ContractDetail.swift
Projects/Contracts/Sources/View/ContractTable.swift
Projects/Contracts/Sources/View/ScrollableSegmentedView.swift
Projects/Home/Sources/Components/ActiveSectionView.swift
Projects/Home/Sources/Screens/HelpCenter/HelpCenterStartView.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsContractDetails.swift
Projects/hCoreUI/Sources/Views/InfoCard/InfoCardScrollView.swift

Improvement/gen 2469 ipad UI fixes

---

Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/App/Sources/Journeys/MainNavigationJourney.swift

Fixed issue with calling language mutation when changing language

Added fix for updating language

---

Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/App/Sources/Journeys/LoginNavigation.swift
Projects/Chat/Sources/Navigation/ChatNavigation.swift
Projects/Claims/Sources/Navigation/ClaimsNavigation.swift
Projects/Claims/Sources/Views/FilesGridView.swift
Projects/Contracts/Sources/ContractsNavigation.swift
Projects/EditCoInsured/Sources/Navigation/EditCoInsuredNavigation.swift
Projects/EditCoInsured/Sources/View/EditCoInsured+modifier.swift
Projects/Forever/Sources/Navigation/ForeverNavigation.swift
Projects/Home/Sources/Components/RenewalCard.swift
Projects/Home/Sources/Navigation/HelpCenterNavigation.swift
Projects/MoveFlow/Sources/MovingFlowNavigationViewModel.swift
Projects/Payment/Sources/Navigation/PaymentNavigation.swift
Projects/Payment/Sources/Screens/ConnectPayments/ConnectPayment+modifier.swift
Projects/Profile/Sources/Navigation/ProfileNavigation.swift
Projects/Profile/Sources/Views/Screens/EuroBonus/EuroBonusNavigation.swift
Projects/Profile/Sources/Views/Screens/SettingsScreen/MemberSubscriptionPreferenceView.swift
Projects/TerminateContracts/Sources/Navigation/TerminationFlowNavigationViewModel.swift
Projects/TravelCertificate/Sources/TravelCertificateNavigation.swift
Projects/hCoreUI/Sources/InfoView/InfoView.swift
Projects/hCoreUI/Sources/PresentationStyle+Detented.swift
Projects/hCoreUI/Sources/Router/DetentRouter.swift
Projects/hCoreUI/Sources/Styling/DefaultStyling.swift
Projects/hCoreUI/Sources/hForm/hDatePickerField.swift

Moving forward to remove presentation dependancy

Removed flow and presentation dependancy from detent style

---

Projects/App/Sources/AppDelegate+Notifications.swift
Projects/App/Sources/AppDelegate+Tracking.swift
Projects/App/Sources/AppDelegate+Unleash.swift
Projects/App/Sources/AppDelegate.swift
Projects/App/Sources/Journeys/ClaimsJourneyMain.swift
Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/App/Sources/Journeys/MainNavigationJourney.swift
Projects/App/Sources/Screens/ClaimsScreen/Screens/ClaimFlowAskForPushnotifications.swift
Projects/Profile/Sources/Store/ProfileAction.swift
Projects/Profile/Sources/Store/ProfileState.swift
Projects/Profile/Sources/Store/ProfileStore.swift
Projects/Profile/Sources/Store/ProfileStoreHelper.swift
Projects/Profile/Sources/Views/Components/NotificationsCardView.swift
Projects/Profile/Sources/Views/Components/ProfileRow.swift
Projects/Profile/Sources/Views/Screens/AppInfo/AppInfoView.swift
Projects/Profile/Sources/Views/Screens/DeleteAccount/DeleteAccountView.swift
Projects/Profile/Sources/Views/Screens/DeleteAccount/DeleteAccountViewModel.swift
Projects/Profile/Sources/Views/Screens/DeleteAccount/DeleteRequestLoadingView.swift
Projects/Profile/Sources/Views/Screens/EmailPreferences/EmailPreferencesConfirmView.swift
Projects/Profile/Sources/Views/Screens/EuroBonus/ChangeEuroBonusView.swift
Projects/Profile/Sources/Views/Screens/EuroBonus/EuroBonusView.swift
Projects/Profile/Sources/Views/Screens/MyInfo/MyInfoView.swift
Projects/Profile/Sources/Views/Screens/Profile/Profile.swift
Projects/Profile/Sources/Views/Screens/SettingsScreen/MemberSubscriptionPreferenceView.swift
Projects/Profile/Sources/Views/Screens/SettingsScreen/SettingsView.swift

Replaced presentation from profile

Replaced presentation from profile

---

Projects/EditCoInsured/Tests/EditCoInsuredStoreTests.swift
Projects/EditCoInsured/Tests/MockData.swift

- Added success and fail test for .performCoInsuredChanges

add edit co-insured store tests

---

Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/App/Sources/Journeys/MainNavigationJourney.swift
Projects/Chat/Sources/Views/MessageView.swift
Projects/Contracts/Sources/Contracts.swift
Projects/Contracts/Sources/EditContract.swift
Projects/Contracts/Sources/Journeys/ContractCoverage.swift
Projects/Contracts/Sources/Journeys/ContractDetail.swift
Projects/Contracts/Sources/Journeys/ContractDocuments.swift
Projects/Contracts/Sources/Journeys/ContractInformation.swift
Projects/Contracts/Sources/Models/ContractModels.swift
Projects/Contracts/Sources/Stores/ContractAction.swift
Projects/Contracts/Sources/Stores/ContractState.swift
Projects/Contracts/Sources/Stores/ContractsStore.swift
Projects/Contracts/Sources/View/ContractTable.swift
Projects/Contracts/Sources/View/CrossSellingItem.swift
Projects/Contracts/Sources/View/CrossSellingScreen.swift
Projects/Contracts/Sources/View/CrossSellingStack.swift
Projects/Contracts/Sources/View/CrossSellingUnseenCircle.swift
Projects/Contracts/Sources/View/InsurableLimits/InsurableLimits.swift
Projects/Contracts/Sources/View/ScrollableSegmentedView.swift
Projects/Contracts/Sources/View/UpcomingChangesScreen.swift
Projects/Home/Sources/Components/RenewalCard.swift
Projects/Home/Sources/Navigation/HelpCenterNavigation.swift
Projects/Home/Sources/Screens/Home.swift
Projects/Home/Sources/Screens/HomeBottomScrollView.swift
Projects/Profile/Sources/Store/ProfileState.swift
Projects/Profile/Sources/Store/ProfileStoreHelper.swift
Projects/Profile/Sources/Views/Screens/DeleteAccount/DeleteAccountViewModel.swift
Projects/TravelCertificate/Sources/Views/WhoIsTravelingScreen.swift

Removed presentation from contracts

Removed presentation from contracts

---

Projects/App/Sources/Journeys/LoginNavigation.swift
Projects/App/Sources/Screens/Impersonation/ImpersonationSettings.swift
Projects/Market/Sources/LanguageAndMarketPickerView.swift
Projects/Market/Sources/MarketStore.swift
Projects/Market/Sources/PickLanguage.swift

Remove presentation from market

Remove presentation from market

---

Projects/Home/Sources/Screens/HomeBottomScrollView.swift
Projects/MoveFlow/Sources/MovingFlowNavigationViewModel.swift
Projects/MoveFlow/Sources/Service/OctopusImplementation/MoveFlowClientOctopus.swift
Projects/MoveFlow/Sources/Store/MoveFlowStore.swift
Projects/MoveFlow/Sources/View/MovingFlowAddExtraBuildingView.swift
Projects/MoveFlow/Sources/View/MovingFlowAddressView.swift
Projects/MoveFlow/Sources/View/MovingFlowConfirm.swift
Projects/MoveFlow/Sources/View/MovingFlowHouseView.swift
Projects/MoveFlow/Sources/View/MovingFlowHousingType.swift
Projects/MoveFlow/Sources/View/MovingFlowProcessingView.swift
Projects/MoveFlow/Sources/View/TypeOfBuildingPickerView.swift
Projects/Payment/Sources/Navigation/PaymentNavigation.swift
Projects/Payment/Sources/PaymentStore.swift
Projects/Payment/Sources/Screens/ConnectPayments/ConnectPaymentCard.swift
Projects/Payment/Sources/Screens/ConnectPayments/DirectDebitSetup.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsDiscount.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsView.swift
Projects/Payment/Sources/Screens/PaymentDiscounts/AddCampaingCodeView.swift
Projects/Payment/Sources/Screens/PaymentDiscounts/DeleteCampaignView.swift
Projects/Payment/Sources/Screens/PaymentDiscounts/PaymentsDiscountsView.swift
Projects/Payment/Sources/Screens/PaymentDiscounts/ReferralsView.swift
Projects/Payment/Sources/Screens/PaymentsHistoryView.swift
Projects/Payment/Sources/Screens/PaymentsView.swift
Projects/Payment/Sources/Service/PaymentService/OctopusImplementation/PaymentDiscountData+octopus.swift
Projects/Payment/Sources/Service/PaymentService/OctopusImplementation/PaymentHistoryData+octopus.swift
Projects/Payment/Tests/StoreTests/StoreDiscountsTests.swift
Projects/Payment/Tests/StoreTests/StoreHistoryTests.swift
Projects/Payment/Tests/StoreTests/StoreLoadTests.swift
Projects/Payment/Tests/StoreTests/StorePaymentStatusTests.swift

Remove presentation from move flow

Remove presentation from move flow

---

Projects/Home/Sources/Screens/HomeBottomScrollView.swift
Projects/Payment/Sources/Navigation/PaymentNavigation.swift
Projects/Payment/Sources/PaymentStore.swift
Projects/Payment/Sources/Screens/ConnectPayments/ConnectPaymentCard.swift
Projects/Payment/Sources/Screens/ConnectPayments/DirectDebitSetup.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsDiscount.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsView.swift
Projects/Payment/Sources/Screens/PaymentDiscounts/AddCampaingCodeView.swift
Projects/Payment/Sources/Screens/PaymentDiscounts/DeleteCampaignView.swift
Projects/Payment/Sources/Screens/PaymentDiscounts/PaymentsDiscountsView.swift
Projects/Payment/Sources/Screens/PaymentDiscounts/ReferralsView.swift
Projects/Payment/Sources/Screens/PaymentsHistoryView.swift
Projects/Payment/Sources/Screens/PaymentsView.swift
Projects/Payment/Sources/Service/PaymentService/OctopusImplementation/PaymentDiscountData+octopus.swift
Projects/Payment/Sources/Service/PaymentService/OctopusImplementation/PaymentHistoryData+octopus.swift
Projects/Payment/Tests/StoreTests/StoreDiscountsTests.swift
Projects/Payment/Tests/StoreTests/StoreHistoryTests.swift
Projects/Payment/Tests/StoreTests/StoreLoadTests.swift
Projects/Payment/Tests/StoreTests/StorePaymentStatusTests.swift

Removed presentation from payments

Removed presentation from payments

---

Projects/Contracts/Tests/MockData.swift
Projects/Contracts/Tests/StoreTests/ContractStoreTests.swift
Projects/Payment/Tests/StoreTests/StoreLoadTests.swift

Contract store tests

---

Projects/Claims/Tests/MockData.swift
Projects/Claims/Tests/SubmitClaimsStoreTests/AudioRecordingStoreTests.swift
Projects/Claims/Tests/SubmitClaimsStoreTests/ContractSelectStoreTests.swift
Projects/Claims/Tests/SubmitClaimsStoreTests/DateOfOccurrancePlusLocationStoreTests.swift
Projects/Claims/Tests/SubmitClaimsStoreTests/EmergencyConfirmRequestStoreTests.swift
Projects/Claims/Tests/SubmitClaimsStoreTests/FetchEntrypointGroupsStoreTests.swift
Projects/Claims/Tests/SubmitClaimsStoreTests/PhoneNumberStoreTests.swift
Projects/Claims/Tests/SubmitClaimsStoreTests/SingleItemCheckoutStoreTests.swift
Projects/Claims/Tests/SubmitClaimsStoreTests/SingleItemStoreTests.swift
Projects/Claims/Tests/SubmitClaimsStoreTests/StartClaimStoreTests.swift
Projects/Claims/Tests/SubmitClaimsStoreTests/SubmitFileUploadStoreTests.swift
Projects/Claims/Tests/SubmitClaimsStoreTests/SummaryStoreTests.swift

- Updated tests to check for error in loading states

Updated tests to check for error in the loading state in case of throwing

---

Projects/Contracts/Sources/Models/ContractModels.swift
Projects/Contracts/Sources/View/ContractTable.swift
Projects/Contracts/Sources/View/CrossSellingStack.swift

- Added info box for moving flow if the member has any active home insurance

GEN-2520: moving flow info box

---

Projects/App/Sources/AppDelegate+DI.swift
Projects/App/Sources/AppDelegate.swift
Projects/hCore/Sources/DateFormat/Date+LocalDateString.swift
Projects/hCore/Sources/DateFormat/String+toDate.swift
Projects/hCoreUI/Sources/Views/GeneralDatePicker.swift

- Added date service
- When updating language set new date service with the new language locale

Update date locale when language changes

---

Projects/hCore/Sources/Masking.swift

- Fixed issue with handling special characters

Update validation of the first and last name

---

Projects/Contracts/Sources/View/ScrollableSegmentedView.swift

- Updated scrolling behaviour to feel more natural

Improvement/insurance details scrolling 

---

Projects/Claims/Sources/Views/ClaimDetailView.swift
Projects/Home/Sources/Screens/Home.swift
Projects/hCoreUI/Sources/ChatButtonView/ChatButtonView.swift

- added logic for iOS navigation Bar items

Fix for iOS 18 navigation

---

Projects/App/Sources/AppDelegate+DI.swift
Projects/App/Sources/AppDelegate+Tracking.swift
Projects/App/Sources/AppDelegate.swift
Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift

- Updated datadog to log resources

Fixed issue with datadog not logging resources

---

Projects/Chat/GraphQL/Octopus/Conversations.graphql
Projects/Chat/GraphQL/Octopus/MarkConversationAsRead.graphql
Projects/Chat/Sources/Service/DemoImplementation/ConversationsClientDemo.swift
Projects/Chat/Sources/Service/OctopusImplementation/ConversationsClientOctopus.swift
Projects/Chat/Sources/Service/Protocols/ConversationClient.swift

- Removed mutation for mark as read

Remove mark as read mutation

---

Projects/Contracts/Sources/ContractsNavigation.swift
Projects/Contracts/Sources/Models/ContractModels.swift
Projects/Contracts/Sources/Stores/ContractState.swift
Projects/EditCoInsured/Sources/View/EditCoInsured+modifier.swift
Projects/EditCoInsuredShared/Sources/Models/ContractModel.swift
Projects/EditCoInsuredShared/Sources/Models/EditCoInsuredViewModel.swift
Projects/Home/Sources/Navigation/HelpCenterNavigation.swift
Projects/Home/Sources/Navigation/HomeNavigation.swift
Projects/TravelCertificate/Sources/TravelCertificateNavigation.swift

Fix for fetching already existing co-insured correctly

---

Projects/Forever/Sources/ChangeCodeView.swift

Fix for forever save code not working

---

Projects/App/Sources/AppDelegate+Tracking.swift
Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/Claims/Sources/Journeys/ClaimsProgressBar.swift
Projects/Claims/Sources/Views/SubmitClaim/SingleItem/PriceInputScreen.swift
Projects/Contracts/Sources/Journeys/ContractDetail.swift
Projects/Home/Sources/Screens/HelpCenter/HelpCenterStartView.swift
Projects/Profile/Sources/Views/Screens/MyInfo/MyInfoView.swift
Projects/TerminateContracts/Sources/Helpers/View+hide.swift
Projects/hCore/Sources/Masking.swift
Projects/hCoreUI/Sources/ChatButtonView/ChatButtonView.swift
Projects/hCoreUI/Sources/Document.swift
Projects/hCoreUI/Sources/InfoView/InfoView.swift
Projects/hCoreUI/Sources/Refreshable.swift
Projects/hCoreUI/Sources/Router/DetentRouter.swift
Projects/hCoreUI/Sources/Router/ModallyRouter.swift
Projects/hCoreUI/Sources/Router/Router.swift
Projects/hCoreUI/Sources/View+dismissButton.swift
Projects/hCoreUI/Sources/View+hidden.swift
Projects/hCoreUI/Sources/Views/DocumentPreview.swift
Projects/hCoreUI/Sources/Views/GeneralDatePicker.swift
Projects/hCoreUI/Sources/Views/InfoCard/InfoCardScrollView.swift
Projects/hCoreUI/Sources/hForm/hFloatingField.swift
Projects/hCoreUI/Sources/hForm/hFloatingTextField.swift
Projects/hCoreUI/Sources/hForm/hTextField.swift
Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift

Upgrade introspect library

---

Projects/Chat/Sources/Models/Conversation.swift
Projects/Chat/Sources/Service/DemoImplementation/ConversationsClientDemo.swift
Projects/Chat/Sources/Service/OctopusImplementation/ConversationsClientOctopus.swift
Projects/Chat/Sources/Views/InboxView.swift
Projects/Chat/Tests/TestChatViewModelIsConversationOpen.swift

- Updated sorting of the inbox conversations
- Added closed status
- [Figma](https://www.figma.com/design/Zh9eICcFh9ALpBRc37a9Yf/Case-Based-Messages-(CBM)?node-id=2562-3125&node-type=SECTION&t=HfiwoDWo10B2Qh8K-0)

Added closed to the inbox conversation's status

---

Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift

upgrade apollo to latest version

---

Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift

upgrade apollo-ios-codegen to latest version

---

Projects/Chat/Sources/Helpers/Message+UI.swift
Projects/Chat/Sources/Models/Chat.swift
Projects/Chat/Sources/Service/ChatService.swift
Projects/Chat/Sources/Views/ChatScreen.swift
Projects/Chat/Sources/Views/ChatScreenViewModel.swift
Projects/Chat/Sources/Views/MessageView.swift
Projects/Chat/Tests/MockData.swift
Projects/Chat/Tests/TestChatViewModelIsConversationOpen.swift
Projects/ExampleUtil/Sources/Setup.swift

Switch isConversationStatus from Bool to ConversationStatus

---

Projects/MoveFlow/Sources/MovingFlowNavigationViewModel.swift
Projects/MoveFlow/Sources/View/MovingFlowAddressView.swift
Projects/MoveFlow/Sources/View/MovingFlowHouseView.swift
Projects/TerminateContracts/Sources/Navigation/TerminationFlowNavigationViewModel.swift
Projects/hCoreUI/Sources/Activity/ActivityIndicatorView.swift
Projects/hCoreUI/Sources/ToggleStyles/CheckboxToggleStyle.swift
Projects/hCoreUI/Sources/hForm/hCounterField.swift

- Updated elements for disabled elements
- Fixed moving flow for the iOS 15 and iOS 16

Fixed moving flow for the iOS15 and iOS16

---

Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/Chat/Sources/Navigation/ChatNavigation.swift
Projects/Chat/Sources/Views/InboxView.swift
Projects/Claims/Sources/Navigation/ClaimsNavigation.swift
Projects/Claims/Sources/SubmitClaimStore.swift
Projects/Claims/Sources/Views/ClaimDetailView.swift
Projects/Claims/Sources/Views/ContactChatView.swift
Projects/Contracts/Sources/EditContract.swift
Projects/Contracts/Sources/View/CrossSellingItem.swift
Projects/Contracts/Sources/View/UpcomingChangesScreen.swift
Projects/Home/Sources/HomeState.swift
Projects/Home/Sources/Models/HelpCenterModel.swift
Projects/Home/Sources/Models/Questions.swift
Projects/Home/Sources/Navigation/HelpCenterNavigation.swift
Projects/Home/Sources/Navigation/HomeNavigation.swift
Projects/Home/Sources/Screens/HelpCenter/HelpCenterQuestionView.swift
Projects/Home/Sources/Screens/HelpCenter/HelpCenterStartView.swift
Projects/Home/Sources/Screens/HelpCenter/HelpCenterTopicView.swift
Projects/Home/Sources/Screens/HelpCenter/ReusableComponents.swift
Projects/MoveFlow/Sources/View/MovingFlowConfirm.swift
Projects/MoveFlow/Sources/View/MovingFlowHousingType.swift
Projects/Payment/Sources/Screens/ConnectPayments/ConnectPaymentCard.swift
Projects/hCore/Sources/DeepLink.swift
Projects/hCore/Sources/HelpCenter+topicType.swift

- Added deep links /chat, /inbox, /conversation
- Cleaned up everything related to chat topic

Add new deep links for chat

---

Projects/Chat/Sources/ChatStore.swift
Projects/Chat/Sources/Models/Chat.swift
Projects/Chat/Sources/Models/Message.swift
Projects/Chat/Sources/Service/ChatService.swift
Projects/Chat/Sources/Service/OctopusImplementation/ChatUploadFileClientOctopus.swift
Projects/Chat/Sources/Views/ChatFileView.swift
Projects/Chat/Sources/Views/ChatScreen.swift
Projects/Chat/Sources/Views/ChatScreenViewModel.swift
Projects/Chat/Sources/Views/MessageView.swift
Projects/Claims/Sources/Service/OctopusImplementation/UploadClaimFileClientOctopus.swift
Projects/Claims/Sources/Views/FilesGridView.swift
Projects/Contracts/Sources/View/ContractTable.swift
Projects/hCore/Sources/Models/File.swift
Projects/hCoreUI/Sources/Views/FileView.swift

- Save failed messages locally when chat is closed

remove chat service type and add list of failed messages

---

Projects/Claims/Sources/SubmitClaimStore.swift
Projects/Claims/Tests/SubmitClaimsStoreTests/DateOfOccurrancePlusLocationStoreTests.swift
Projects/Claims/Tests/SubmitClaimsStoreTests/StartClaimStoreTests.swift
Projects/Claims/Tests/SubmitClaimsStoreTests/SummaryStoreTests.swift
Projects/Home/Sources/Models/MemberContractState.swift
Projects/Home/Tests/HomeTests.swift
Projects/Home/Tests/MockData.swift
Projects/PresentableStore/Sources/PresentableStore/PresentableStore.swift

- It can happen that store isn't saved properly when 2 actions are sent at the same time or close to each other
- Added tests for the home screen to test this

Presentation store race condition fix

---

Projects/App/Sources/Journeys/ClaimsJourneyMain.swift
Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/App/Sources/Journeys/LoginNavigation.swift
Projects/Claims/Sources/Navigation/ClaimsNavigation.swift
Projects/Claims/Sources/Views/ClaimDetailView.swift
Projects/Contracts/Sources/ContractsNavigation.swift
Projects/EditCoInsured/Sources/Navigation/EditCoInsuredNavigation.swift
Projects/EditCoInsured/Sources/View/CoInsuredProcessingScreen.swift
Projects/EditCoInsured/Sources/View/CoInusuredInput.swift
Projects/EditCoInsured/Sources/View/EditCoInsured+modifier.swift
Projects/Forever/Sources/Navigation/ForeverNavigation.swift
Projects/Home/Sources/Navigation/HelpCenterNavigation.swift
Projects/MoveFlow/Sources/MovingFlowNavigationViewModel.swift
Projects/Payment/Sources/Navigation/PaymentNavigation.swift
Projects/Payment/Sources/Screens/PaymentDiscounts/AddCampaingCodeView.swift
Projects/Profile/Sources/Navigation/ProfileNavigation.swift
Projects/Profile/Sources/Views/Screens/DeleteAccount/DeleteAccountView.swift
Projects/Profile/Sources/Views/Screens/EuroBonus/EuroBonusNavigation.swift
Projects/TerminateContracts/Sources/Navigation/TerminationFlowNavigationViewModel.swift
Projects/hCoreUI/Sources/Router/DetentRouter.swift
Projects/hCoreUI/Sources/Router/Router.swift
Projects/hCoreUI/Sources/Views/DocumentPreview.swift
Projects/hCoreUI/Sources/Views/GeneralDatePicker.swift
Projects/hCoreUI/Sources/hForm/hDatePickerField.swift

- Updated the way we track views

Updating the way we track the views name

---

Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/Contracts/Sources/ContractsNavigation.swift
Projects/Contracts/Sources/EditContract.swift
Projects/Contracts/Sources/Journeys/ContractInformation.swift
Projects/Contracts/Sources/Models/ContractModels.swift
Projects/Contracts/Sources/Service/DemoImplemenmtation/ContractsClientDemo.swift
Projects/Contracts/Sources/Stores/ContractAction.swift
Projects/hCoreUI/Sources/Views/InsurableLimitsSectionView.swift
Projects/hGraphQL/GraphQL/Octopus/Agreement.graphql

- Added entry point to the change tier

GEN-2693: Added entry point for change tier

---

Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/ChangeTier/Sources/Navigation/ChangeTierNavigation.swift
Projects/Contracts/Project.swift
Projects/Contracts/Sources/ContractsNavigation.swift
Projects/Contracts/Sources/EditContract.swift
Projects/Home/Sources/Navigation/HelpCenterNavigation.swift
Projects/TerminateContracts/Sources/Navigation/TerminationFlowNavigationViewModel.swift

Added support for the 2 new redirect actions
- changeTierFoundBetterPrice
- changeTierMissingCoverageAndTerms

GEN-2696: Redirect termination actions

---

Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/Home/Sources/Navigation/HelpCenterNavigation.swift

- Handling cancellation redirection from the help center
- Handling cancellation redirection from the home

Handling cancellation redirect from help center and home

---

Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/Contracts/Sources/ContractsNavigation.swift
Projects/Home/Sources/Navigation/HelpCenterNavigation.swift
Projects/TerminateContracts/Project.swift
Projects/TerminateContracts/Sources/Navigation/TerminationFlowNavigationViewModel.swift

- Handling termination tier change redirect from one place

Handling changeTier redirection from one place

---

Projects/ChangeTier/Sources/Navigation/ChangeTierNavigation.swift
Projects/ChangeTier/Sources/Service/OctopusImplementation/ChangeTierClientOctopus.swift
Projects/ChangeTier/Sources/Views/ChangeTierLandingScreen.swift
Projects/ChangeTier/Sources/Views/ChangeTierViewModel.swift
Projects/TerminateContracts/Sources/Navigation/TerminationFlowNavigationViewModel.swift
Projects/TerminateContracts/Sources/Views/TerminationSurveyScreen.swift
Projects/hCore/Sources/UIApplication+GetTopViewController.swift
Projects/hCoreUI/Sources/Toasts.swift
Projects/hCoreUI/Sources/hButton/hButton.swift

- Checking for quotes before we start redirecting from the termination flow

Added check for quotes before we continue redirectin

---

Projects/ChangeTier/Sources/Views/CompareTierScreen.swift
Projects/hCore/Sources/Perils.swift
Projects/hCoreUI/Sources/Peril/Accordion.swift
Projects/hCoreUI/Sources/Peril/PerilCollection.swift

- Compare perils with highest tier and include those as disabled ones
- Add view for disabled peril

Add perils not in coverage

---

Projects/TerminateContracts/Sources/Views/TerminationSurveyScreen.swift

- Added minheight to make survey option less jumpy
- Reported in test session [here](https://www.notion.so/hedviginsurance/Tiers-App-114c3f71cb0a8049b4dcf218eb00df65?p=114c3f71cb0a80c68bf0d6fbb58335a6&pm=s)

add minheight

---

Projects/ChangeTier/Sources/Service/DemoImplementation/ChangeTierClientDemo.swift
Projects/hCore/Sources/Perils.swift
Projects/hCoreUI/Sources/Peril/PerilCollection.swift
Projects/hGraphQL/GraphQL/Octopus/ProductVariantFragment.graphql

Removed perils info

---

Projects/ChangeTier/Sources/Views/ChangeTierLandingScreen.swift
Projects/ChangeTier/Sources/Views/ChangeTierViewModel.swift

Fix for preselecting if tier or deductible count = 1

---

Projects/ChangeTier/Sources/Navigation/ChangeTierNavigation.swift
Projects/ChangeTier/Sources/Service/OctopusImplementation/ChangeTierClientOctopus.swift
Projects/ChangeTier/Sources/Views/ChangeTierLandingScreen.swift
Projects/ChangeTier/Sources/Views/ChangeTierViewModel.swift
Projects/TerminateContracts/Sources/Navigation/TerminationFlowNavigationViewModel.swift
Projects/hCoreUI/Sources/Views/InfoScreen.swift
Projects/hCoreUI/Sources/Views/StateView.swift

- Handled from help centar - with or without select insurance screen
- Handled from insurance, edit insurance, upgrade coverage
- Handled from termination flow
From edit insurance:
From termination flow:

Added missing quotes info screeen

---

Projects/App/Sources/Screens/ClaimsScreen/Screens/HonestyPledge.swift

- added tap gesture
- updated animationas

Update honesty pledge

---

Projects/ChangeTier/Sources/Views/CompareTierScreen.swift

Use selectedQuote in compare screen if there is any

---

Projects/ChangeTier/Sources/Models/ChangeTierIntentModel.swift
Projects/ChangeTier/Sources/Views/EditTierScreen.swift

Add “from” price if it’s the lowest

---

Projects/App/Sources/Journeys/ClaimsJourneyMain.swift
Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/Chat/Sources/Views/InboxView.swift
Projects/Claims/Sources/Claims.swift
Projects/Claims/Sources/Views/ClaimSection.swift
Projects/Contracts/Sources/ContractsNavigation.swift
Projects/Contracts/Sources/Journeys/ContractInformation.swift
Projects/Contracts/Sources/View/UpcomingChangesScreen.swift
Projects/EditCoInsured/Sources/View/AlreadyExistingCoInsured/InsuredPeopleScreen.swift
Projects/EditCoInsured/Sources/View/NewCoInsured/InsuredPeopleNewScreen.swift
Projects/EditCoInsured/Sources/View/NewCoInsured/RemoveCoInsuredScreen.swift
Projects/Forever/Sources/Components/InivtationTable.swift
Projects/Home/Sources/Navigation/HomeNavigation.swift
Projects/Home/Sources/Screens/HelpCenter/HelpCenterStartView.swift
Projects/Home/Sources/Screens/HelpCenter/ReusableComponents.swift
Projects/Home/Sources/Screens/Home.swift
Projects/Home/Sources/Screens/HomeBottomScrollView.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsContractDetails.swift
Projects/Profile/Sources/Views/Screens/AppInfo/AppInfoView.swift
Projects/Profile/Sources/Views/Screens/Profile/Profile.swift
Projects/TravelCertificate/Sources/Views/ListScreen.swift
Projects/hCore/Sources/Catalyst.swift
Projects/hCoreUI/Sources/Styling/DefaultStyling.swift
Projects/hCoreUI/Sources/Views/InfoCard/InfoCardScrollView.swift
Projects/hCoreUI/Sources/Views/InsurableLimitsSectionView.swift
Projects/hCoreUI/Sources/hForm/hForm.swift
Projects/hCoreUI/Sources/hForm/hSection.swift
Projects/hCoreUI/Sources/hForm/hTextView.swift

- replaced hSection withoutHorizontalPadding with hSectionWithoutHorizontalPadding
- removed minimalPadding
- updated claims scroll with general scroll pagination (looks smoother and adjust to the screen size)
- updated home bottom scroll  with general scroll pagination (looks smoother and adjust to the screen size)

Replaced withoutHorizontalPadding

---

Projects/ChangeTier/GraphQL/Octopus/ChangeTierCreateIntent.graphql
Projects/ChangeTier/GraphQL/Octopus/ContractsQuery.graphql
Projects/ChangeTier/Sources/Service/OctopusImplementation/ChangeTierClientOctopus.swift

- Update schema to include agreementToChange

add new schema

---

Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/ChangeTier/Sources/Navigation/ChangeTierNavigation.swift
Projects/ChangeTier/Sources/Views/ChangeTierProcessingScreen.swift
Projects/ChangeTier/Sources/Views/ChangeTierSummaryScreen.swift
Projects/MoveFlow/Sources/MovingFlowNavigationViewModel.swift

- refresh contracts after we are finished with move flow
- refresh contracts after we are done with the change tier flow

Refresh contract after we finish with either moving or change tier flow

---

Projects/ChangeTier/Sources/Service/OctopusImplementation/ChangeTierClientOctopus.swift
Projects/ChangeTier/Sources/Views/ChangeTierLandingScreen.swift
Projects/ChangeTier/Sources/Views/ChangeTierViewModel.swift
Projects/ChangeTier/Sources/Views/EditDeductibleScreen.swift
Projects/ChangeTier/Sources/Views/EditTierScreen.swift
Projects/Contracts/Sources/ContractsNavigation.swift
Projects/Contracts/Sources/Journeys/ContractCoverage.swift
Projects/Contracts/Sources/Journeys/ContractInformation.swift
Projects/Contracts/Sources/View/UpcomingChangesScreen.swift
Projects/hCoreUI/Sources/Styling/DefaultStyling.swift
Projects/hCoreUI/Sources/Views/Dropdown.swift
Projects/hCoreUI/Sources/Views/QuoteSummaryScreen.swift
Projects/hCoreUI/Sources/hForm/RadioFields/hRadioField.swift
Projects/hCoreUI/Sources/hForm/RadioFields/hRadioOptionField.swift
Projects/hCoreUI/Sources/hForm/hFieldBackground.swift
Projects/hCoreUI/Sources/hForm/hFloatingField.swift
Projects/hCoreUI/Sources/hForm/hFloatingTextField.swift
Projects/hCoreUI/Sources/hForm/hSection.swift

https://www.notion.so/hedviginsurance/UI-Review-Change-tier-flows-128c3f71cb0a80f5a695d7b8035fa853

UI check fixes

---

Projects/Claims/Sources/Navigation/ClaimsNavigation.swift
Projects/TerminateContracts/GraphQL/Octopus/TerminationStartFlow.graphql
Projects/TerminateContracts/Sources/Navigation/TerminateProgress.swift
Projects/TerminateContracts/Sources/Navigation/TerminationFlowNavigationViewModel.swift
Projects/TerminateContracts/Sources/Service/DemoImplementation/TerminateContractsClientDemo.swift
Projects/TerminateContracts/Sources/Service/OctopusImplementation/TerminateContractsClientOctopus.swift
Projects/TerminateContracts/Sources/Service/Protocols/TerminateContractsClient.swift
Projects/TerminateContracts/Sources/Store/TerminateContractAction.swift
Projects/TerminateContracts/Sources/Store/TerminationContractState.swift
Projects/TerminateContracts/Sources/Store/TerminationContractStore.swift
Projects/TerminateContracts/Sources/Views/TerminationSurveyScreen.swift
Projects/hCoreUI/Sources/View+onDeinit.swift

- Added progress for termination flow

Added progress for the termination flow

---

Projects/ChangeTier/Sources/Views/CompareTierScreen.swift
Projects/hCoreUI/Sources/ScrollView/TrackingOffsetModifier.swift

- Updated compare tiers animations

Added spring animations

---

Projects/Claims/Sources/Navigation/ClaimsNavigation.swift
Projects/Claims/Sources/Views/SubmitClaim/Entrypoints/SelectClaimEntrypoint.swift
Projects/hCoreUI/Sources/Progress/ProgressBar.swift

- return to previous value on dismiss fixes
- related to the [this PR](https://github.com/HedvigInsurance/ugglan/pull/1606)

Generic progress bar fixes deinit fixes

---

Projects/ChangeTier/Sources/Navigation/ChangeTierNavigation.swift
Projects/MoveFlow/Sources/Service/Navigation/MovingFlowNavigation.swift
Projects/hCoreUI/Sources/View+dismissButton.swift

- Added dismiss alert for the change tier flow
- Added dismiss alert for the moving flow

GEN-2853: Added generic dismiss button

---

Projects/MoveFlow/GraphQL/Octopus/MoveIntentCreate.graphql
Projects/MoveFlow/Sources/Model/MovingFlowModel.swift
Projects/MoveFlow/Sources/Service/OctopusImplementation/MoveFlowClientOctopus.swift
Projects/MoveFlow/Sources/View/MovingFlowAddressScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowHouseScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowHousingTypeScreen.swift

- Added new property to the MoveAddress fragment
- Implemented UI logic for showing it

GEN-2921: Implemented logic for using dynamic info box in the moving flow

---

Projects/Claims/Sources/Navigation/ClaimsNavigation.swift
Projects/Claims/Sources/Views/SubmitClaim/Contracts/SelectContractView.swift
Projects/Claims/Sources/Views/SubmitClaim/Emergency/SumitClaimEmergencySelectView.swift
Projects/Claims/Sources/Views/SubmitClaim/Entrypoints/SelectClaimEntrypoint.swift
Projects/Claims/Sources/Views/SubmitClaim/FilesUpload/FilesUploadScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/IncidentInfo/SubmitClaimOccurrencePlusLocationScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/SingleItem/SubmitClaimSingleItemScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/SubmitClaimContactScreen.swift

fix titles in claims flow to be according to new design system

---

Projects/ChangeTier/Sources/Navigation/ChangeTierNavigation.swift
Projects/ChangeTier/Sources/Service/ChangeTierService.swift
Projects/ChangeTier/Sources/Views/ChangeTierViewModel.swift
Projects/ChangeTier/Sources/Views/CompareTierScreen.swift
Projects/hCore/Sources/Codable+String.swift

- Added ChangeTier service
- Added logs fo the services

Added changeTier service logs

---

Projects/ChangeTier/Sources/Models/ChangeTierIntentModel.swift
Projects/ChangeTier/Sources/Navigation/ChangeTierNavigation.swift
Projects/ChangeTier/Sources/Service/OctopusImplementation/ChangeTierClientOctopus.swift
Projects/ChangeTier/Sources/Views/ChangeTierViewModel.swift
Projects/ChangeTier/Sources/Views/CompareTierScreen.swift

- Added current tier in select tier
- Added current tier in comparision

Make current tier selectable and comparable

---

Projects/TerminateContracts/GraphQL/Octopus/TerminationStartFlow.graphql
Projects/TerminateContracts/Sources/Models/TerminationConfig.swift
Projects/TerminateContracts/Sources/Models/TerminationFlowDateNextStepModel.swift
Projects/TerminateContracts/Sources/Models/TerminationFlowDeletionNextModel.swift
Projects/TerminateContracts/Sources/Navigation/TerminationFlowNavigationViewModel.swift
Projects/TerminateContracts/Sources/Service/OctopusImplementation/TerminateContractsClientOctopus.swift
Projects/TerminateContracts/Sources/Views/TerminationSummaryScreen.swift

- Added extraCoverageItems from schema into model and view

Added extraCoverageItems to termination summary

---

Projects/ChangeTier/Sources/Views/EditDeductibleScreen.swift
Projects/ChangeTier/Sources/Views/EditTierScreen.swift
Projects/Claims/Sources/Views/ClaimStatus.swift
Projects/hCoreUI/Sources/Pill/hPill.swift

- Make all grey pills translucent
- From [this thread](https://hedviginsurance.slack.com/archives/C03U9C6Q7TP/p1733914042156539)

update highlight colors

---

Projects/Addons/Sources/Models/AddonOffer.swift
Projects/Addons/Sources/Navigation/ChangeAddonNavigation.swift
Projects/Addons/Sources/Service/OctopusImplementation/AddonsClientOctopus.swift
Projects/Addons/Sources/Views/AddonProcessingScreen.swift
Projects/Addons/Sources/Views/AddonSelectInsuranceScreen.swift
Projects/Addons/Sources/Views/AddonSelectSubOptionScreen.swift
Projects/Addons/Sources/Views/ChangeAddonScreen.swift
Projects/Addons/Sources/Views/ChangeAddonSummaryScreen.swift
Projects/Addons/Sources/Views/ChangeAddonViewModel.swift
Projects/Addons/Sources/Views/ConfirmChangeAddonScreen.swift
Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/Contracts/Sources/Service/DemoImplemenmtation/ContractsClientDemo.swift
Projects/Contracts/Sources/Service/OctopusImplementation/ContractsClientOctopus.swift
Projects/Contracts/Sources/View/ContractTable.swift
Projects/TravelCertificate/Sources/Service/OctopusImplementation/TravelInsuranceClientOctopus.swift
Projects/TravelCertificate/Sources/TravelCertificateNavigation.swift
Projects/TravelCertificate/Sources/Views/ListScreen.swift

- Add select insurance step if multiple eligable contracts

add SelectInsurance step

---

Projects/Claims/Sources/Views/ClaimStatus.swift
Projects/Contracts/Sources/ContractsNavigation.swift
Projects/Contracts/Sources/Models/ContractModels.swift
Projects/TerminateContracts/GraphQL/Octopus/TerminationStartFlow.graphql
Projects/TerminateContracts/Sources/Models/TerminationConfig.swift
Projects/TerminateContracts/Sources/Models/TerminationFlowDateNextStepModel.swift
Projects/TerminateContracts/Sources/Models/TerminationFlowDeletionNextModel.swift
Projects/TerminateContracts/Sources/Navigation/TerminationFlowNavigationViewModel.swift
Projects/TerminateContracts/Sources/Service/OctopusImplementation/TerminateContractsClientOctopus.swift
Projects/TerminateContracts/Sources/Views/ConfirmTerminationScreen.swift
Projects/TerminateContracts/Sources/Views/SetTerminationDateLandingScreen.swift
Projects/TerminateContracts/Sources/Views/TerminationSummaryScreen.swift
Projects/TerminateContracts/Tests/MockData.swift
Projects/TerminateContracts/Tests/TerminateContractsTests.swift
Projects/hCore/Sources/FeatureFlags/FeatureFlagOctopus.swift
Projects/hCore/Sources/FeatureFlags/FeatureFlagsDemo.swift
Projects/hCore/Sources/FeatureFlags/FeatureFlagsProtocol.swift
Projects/hCore/Sources/Models/ProductVariant.swift
Projects/hCoreUI/Sources/StatusCard.swift

GEN-2982: Addons for termination

---

Projects/ChangeTier/Sources/Views/ChangeTierSummaryScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowConfirmScreen.swift
Projects/hCoreUI/Sources/Views/QuoteSummaryScreen.swift

Remove Q&A section from summary screen (and moving flow)

---

Projects/Addons/GraphQL/Octopus/AddonVariant.graphql
Projects/Addons/GraphQL/Octopus/CurrentAddonContract.graphql
Projects/Addons/GraphQL/Octopus/UpsellTravelAddonOffer.graphql
Projects/Addons/Sources/Models/AddonOffer.swift
Projects/Addons/Sources/Service/DemoImplementation/AddonsClientDemo.swift
Projects/Addons/Sources/Service/OctopusImplementation/AddonsClientOctopus.swift
Projects/Addons/Sources/Views/AddonSelectSubOptionScreen.swift
Projects/Addons/Sources/Views/ChangeAddonSummaryScreen.swift
Projects/Contracts/Sources/Models/ContractModels.swift
Projects/Contracts/Sources/Service/DemoImplemenmtation/ContractsClientDemo.swift
Projects/Contracts/Sources/View/ContractDocuments.swift
Projects/Contracts/Sources/View/UpcomingChangesScreen.swift
Projects/hCore/Sources/Perils.swift
Projects/hGraphQL/GraphQL/Octopus/Agreement.graphql
Projects/hGraphQL/GraphQL/Octopus/ProductAddonFragment.graphql
Projects/hGraphQL/Sources/Models/InsurableLimits.swift
Projects/hGraphQL/Sources/Models/hPDFDocument.swift

add addonVariant

---

Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/Claims/GraphQL/Octopus/StartClaimsFlow.graphql
Projects/Claims/Sources/Models/FlowClaimDeflectStepModel.swift
Projects/Claims/Sources/Navigation/ClaimsNavigation.swift
Projects/Claims/Sources/Service/OctopusImplementation/SubmitClaimClientOctopus.swift
Projects/Claims/Sources/Views/SubmitClaim/Car/SubmitClaimCarView.swift
Projects/Claims/Sources/Views/SubmitClaim/Deflect/SubmitClaimDeflectScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/SubViews/ClaimContactCard.swift
Projects/hCore/Sources/Models/Deflect.swift
Projects/hCoreUI/Sources/hButton/hButton.swift
Projects/hCoreUI/Sources/hForm/hSection.swift

- Added support for the ID protection deflect screen
- Refactor deflect model + partner model

GEN-3003: add ID Protection deflect screen

---

Projects/Claims/Sources/Views/SubmitClaim/Deflect/SubmitClaimDeflectScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/SubViews/SupportView.swift

- Fix support view according to [figma design](https://www.figma.com/design/SNVLvLq7ztclXiDqqMNXgY/Tiers-%26-Addons-(App)?node-id=3779-44128&t=445a0xSTrgbAF52p-0)

fix padding and background color for deflect support view

---

Projects/ChangeTier/Sources/Models/ChangeTierIntentModel.swift
Projects/MoveFlow/GraphQL/Octopus/MoveIntentCreate.graphql
Projects/MoveFlow/Sources/Model/MovingFlowModel.swift
Projects/MoveFlow/Sources/Service/Navigation/MovingFlowNavigation.swift
Projects/MoveFlow/Sources/Service/OctopusImplementation/MoveFlowClientOctopus.swift
Projects/MoveFlow/Sources/View/MovingFlowConfirmScreen.swift
Projects/hCoreUI/Sources/InfoView/InfoView.swift
Projects/hGraphQL/Sources/Models/hPDFDocument.swift

GEN-2987: Add addon data inside moving flow

---

Projects/ChangeTier/GraphQL/Octopus/ChangeTierCreateIntent.graphql
Projects/ChangeTier/Sources/Models/ChangeTierIntentModel.swift
Projects/ChangeTier/Sources/Navigation/ChangeTierNavigation.swift
Projects/ChangeTier/Sources/Service/DemoImplementation/ChangeTierClientDemo.swift
Projects/ChangeTier/Sources/Service/OctopusImplementation/ChangeTierClientOctopus.swift
Projects/ChangeTier/Sources/Views/ChangeTierSummaryScreen.swift
Projects/ChangeTier/Sources/Views/CompareTierScreen.swift
Projects/MoveFlow/Sources/Service/Navigation/MovingFlowNavigation.swift
Projects/MoveFlow/Sources/Service/OctopusImplementation/MoveFlowClientOctopus.swift

- Added addons in the change tier flow

GEN-3052: Feature/addons/change tier flow

---

Projects/ChangeTier/Sources/Views/CompareTierScreen.swift

Comparison screen tiers order for perils info

---

Projects/Contracts/Sources/View/ContractCoverage.swift
Projects/hCoreUI/Sources/Views/CoverageView.swift

- Display addon perils in insurance details coverage

GEN-3124: Display addon perils

---

Projects/ChangeTier/Sources/Service/OctopusImplementation/ChangeTierClientOctopus.swift
Projects/Contracts/Sources/Stores/ContractAction.swift
Projects/Contracts/Sources/View/ContractRow.swift
Projects/Home/Sources/Service/OctopusImplementation/HomeClientOctopus.swift
Projects/MoveFlow/Sources/Model/MovingFlowModel.swift
Projects/MoveFlow/Sources/Service/DemoImplementation/MoveFlowClientDemo.swift
Projects/MoveFlow/Sources/Service/OctopusImplementation/MoveFlowClientOctopus.swift
Projects/MoveFlow/Sources/View/MovingFlowAddressScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowConfirmScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowHouseScreen.swift
Projects/MoveFlow/Tests/MockData.swift
Projects/MoveFlow/Tests/ViewModelTests/MovingFlowHousingTypeViewModelTests.swift
Projects/hCore/Sources/FeatureFlags/FeatureFlagOctopus.swift
Projects/hCore/Sources/FeatureFlags/FeatureFlagsDemo.swift
Projects/hCore/Sources/FeatureFlags/FeatureFlagsProtocol.swift
Projects/hCoreUI/Sources/Views/QuoteSummaryScreen.swift

- Removed tiers flag
- Removed moving flow version
- Removed unused code

Removed tiers flag + moving flow version

---

Projects/MoveFlow/GraphQL/Octopus/MoveIntentCreate.graphql
Projects/MoveFlow/Sources/Service/OctopusImplementation/MoveFlowClientOctopus.swift

Remove quotes in the move intent

---

Projects/hCore/Sources/FeatureFlags/FeatureFlagOctopus.swift
Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift

- Since they [fixed](https://github.com/Unleash/unleash-proxy-client-swift/issues/98) the issue and updated library, we can remove nonisolated

Updated Unleash client + removed nonisolated

---

Projects/MoveFlow/GraphQL/Octopus/MoveIntentCreate.graphql
Projects/MoveFlow/Sources/Model/MovingFlowModel.swift
Projects/MoveFlow/Sources/Service/Navigation/MovingFlowNavigation.swift
Projects/MoveFlow/Sources/Service/OctopusImplementation/MoveFlowClientOctopus.swift

- Update dialog to get data from BE

Set confirm addon removal using data from BE

---

Projects/hCoreUI/Sources/Views/ScrollableSegmentedView.swift

- Added scrollable header view in case elements gets too large

Added scrollable header view for scrollable segmented view

---

Projects/Addons/Sources/Navigation/ChangeAddonNavigation.swift
Projects/Addons/Sources/Views/AddonLearnMoreView.swift
Projects/Addons/Sources/Views/ChangeAddonScreen.swift

- Added perils to addon learn more screen
- [Figma](https://www.figma.com/design/SNVLvLq7ztclXiDqqMNXgY/Tiers-%26-Addons-(App)?node-id=4138-59106&t=2myQJJe4gpN3Q86c-0)

GEN-3184: Add perils to addon learn more

---

Projects/Addons/Sources/Service/OctopusImplementation/AddonsClientOctopus.swift
Projects/Addons/Sources/Views/ChangeAddonSummaryScreen.swift
Projects/ChangeTier/Sources/Navigation/ChangeTierNavigation.swift
Projects/ChangeTier/Sources/Views/ChangeTierSummaryScreen.swift
Projects/ChangeTier/Sources/Views/EditDeductibleScreen.swift
Projects/ChangeTier/Sources/Views/EditTierScreen.swift
Projects/MoveFlow/GraphQL/Octopus/MoveIntentCommit.graphql
Projects/MoveFlow/Sources/Service/DemoImplementation/MoveFlowClientDemo.swift
Projects/MoveFlow/Sources/Service/Navigation/MovingFlowNavigation.swift
Projects/MoveFlow/Sources/Service/OctopusImplementation/MoveFlowClientOctopus.swift
Projects/MoveFlow/Sources/Service/Protocols/MoveFlowClient.swift
Projects/MoveFlow/Sources/View/MovingFlowConfirmScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowProcessingScreen.swift
Projects/hCoreUI/Sources/InfoView/InfoView.swift
Projects/hCoreUI/Sources/Peril/Accordion.swift
Projects/hCoreUI/Sources/Pill/hPill.swift
Projects/hCoreUI/Sources/StatusCard.swift
Projects/hCoreUI/Sources/Views/ContractInformation.swift
Projects/hCoreUI/Sources/Views/CoverageView.swift
Projects/hCoreUI/Sources/Views/PriceField.swift
Projects/hCoreUI/Sources/Views/QuoteSummaryScreen.swift

GEN-3108: Added opt out addon for moving flow

---

Projects/Chat/Sources/Models/Message.swift
Projects/Chat/Sources/Views/ChatInputView.swift
Projects/Chat/Sources/Views/MessageView.swift

- Trim incoming messages
- Check if message is empty when sending it

Trim conversation messages

---

Projects/Addons/Sources/Views/AddonLearnMoreView.swift

- Updated addon learn more design to include pill
- [Figma](https://www.figma.com/design/SNVLvLq7ztclXiDqqMNXgY/Tiers-%26-Addons-(App)?node-id=4138-59105&m=dev)

add pill to learn more view

---

Projects/Addons/Sources/Views/AddonLearnMoreView.swift
Projects/Addons/Sources/Views/AddonSelectSubOptionScreen.swift
Projects/Addons/Sources/Views/ChangeAddonScreen.swift
Projects/Addons/Sources/Views/ConfirmChangeAddonScreen.swift

Updated addons forms

---

Projects/Addons/Sources/Models/AddonOffer.swift
Projects/Addons/Sources/Service/DemoImplementation/AddonsClientDemo.swift
Projects/Addons/Sources/Views/AddonSelectSubOptionScreen.swift
Projects/ChangeTier/Sources/Views/ChangeTierSummaryScreen.swift
Projects/MoveFlow/Sources/Service/Navigation/MovingFlowNavigation.swift
Projects/hGraphQL/GraphQL/Octopus/ProductAddonFragment.graphql
Projects/hGraphQL/Sources/Models/InsurableLimits.swift

- Removed querying insurable limits form addonVariant
- Removed insurableLimits from AddonVariant model

Remove insurable limits from addonVariant

---

Projects/App/Sources/Screens/ClaimsScreen/Screens/ClaimFlowAskForPushnotifications.swift
Projects/App/Sources/Screens/Impersonation/ImpersonationSettings.swift
Projects/Authentication/Sources/OTP/OTPCodeEntryView.swift
Projects/Authentication/Sources/OTP/OTPEntryView.swift
Projects/Authentication/Sources/SEBankID/BankIDLoginQRView.swift
Projects/Contracts/Sources/View/CrossSellingScreen.swift

- Form update for authentication
- Form update for contracts
- Form update for ugglan

Form update for authentication, contracts and ugglan

---

Projects/Claims/Sources/Views/ClaimDetailView.swift
Projects/Claims/Sources/Views/ClaimFilesView.swift
Projects/Claims/Sources/Views/SubmitClaim/Car/SubmitClaimCarView.swift
Projects/Claims/Sources/Views/SubmitClaim/Deflect/SubmitClaimDeflectScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/Emergency/SumitClaimEmergencySelectView.swift
Projects/Claims/Sources/Views/SubmitClaim/SingleItem/PriceInputScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/SummaryInfo/SubmitClaimEditSummaryScreen.swift
Projects/Claims/Sources/Views/SubmitClaim/SummaryInfo/SubmitClaimSummaryScreen.swift
Projects/Claims/Sources/Views/submitClaim/Checkout/SubmitClaimCheckoutScreen.swift
Projects/EditCoInsured/Sources/Navigation/EditCoInsuredNavigation.swift
Projects/EditCoInsured/Sources/View/AlreadyExistingCoInsured/InsuredPeopleScreen.swift
Projects/EditCoInsured/Sources/View/CoInusuredInput.swift
Projects/EditCoInsured/Sources/View/NewCoInsured/InsuredPeopleNewScreen.swift
Projects/EditCoInsured/Sources/View/NewCoInsured/RemoveCoInsuredScreen.swift

- Updated form for edit co insured
- Updated form for claims

Form update  for edit co insured and claims

---

Projects/Addons/Sources/Views/AddonCardView.swift
Projects/Contracts/Sources/Contracts.swift
Projects/Contracts/Sources/View/ContractTable.swift

- UI update for addon banner card
- [Ticket](https://www.notion.so/hedviginsurance/UI-Review-Addon-related-areas-128c3f71cb0a80f5a695d7b8035fa853?p=184c3f71cb0a80a0878ac4ce6212e164&pm=s)

update padding and color on addon banner card

---

Projects/hCoreUI/Sources/Views/CoverageView.swift

- Updated spacing
- [Figma](https://www.figma.com/design/SNVLvLq7ztclXiDqqMNXgY/Tiers-%26-Addons-(App)?node-id=4265-53768&t=F8FPKbnuAmGVhi5i-0)
- [Ticket](https://www.notion.so/hedviginsurance/UI-Update-Coverage-tab-in-insurance-184c3f71cb0a800eb90aea2d6b77d637)

Update design in insurance coverage tab

---

Projects/Contracts/Sources/View/ContractDocuments.swift

- Updated design in documents tab
- [Ticket](https://www.notion.so/hedviginsurance/UI-Update-Documents-tab-in-insurance-184c3f71cb0a80eb8706ef9300a348a5)

Update design in documents tab

---

Projects/MoveFlow/GraphQL/Octopus/MoveIntentCreate.graphql
Projects/MoveFlow/Sources/Model/MovingFlowModel.swift
Projects/MoveFlow/Sources/Service/Navigation/MovingFlowNavigation.swift
Projects/MoveFlow/Sources/Service/OctopusImplementation/MoveFlowClientOctopus.swift

- Updated exposure name on summary card for moving flow
- [Figma](https://www.figma.com/design/SNVLvLq7ztclXiDqqMNXgY/Tiers-%26-Addons-(App)?node-id=4265-54217&t=HEjbANj4872PGz8g-0)

Update exposure name in summary card

---

Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsContractDetails.swift

Payments: truncated and moving title

---

Projects/Payment/Tests/PaymentMockData.swift
Projects/Payment/Tests/ServiceTests/PaymentServiceTests.swift
Projects/Payment/Tests/StoreTests/StoreLoadTests.swift

Update payment tests

---

Projects/Payment/GraphQL/Octopus/PaymentData.graphql
Projects/Payment/Sources/Helpers/PaymentData+titleView.swift
Projects/Payment/Sources/PaymentStore.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentStatusView.swift
Projects/Payment/Sources/Screens/PaymentsView.swift
Projects/Payment/Sources/Service/PaymentService/DemoImplementation/PaymentClientDemo.swift
Projects/Payment/Sources/Service/PaymentService/OctopusImplementation/PaymentClientOctopus.swift
Projects/Payment/Sources/Service/PaymentService/OctopusImplementation/PaymentData+octopus.swift
Projects/Payment/Sources/Service/PaymentService/OctopusImplementation/PaymentHistoryData+octopus.swift
Projects/Payment/Sources/Service/PaymentService/Protocols/PaymentClient.swift
Projects/TerminateContracts/Sources/Views/SetTerminationDate.swift
Projects/TerminateContracts/Sources/Views/SetTerminationDateLandingScreen.swift
Projects/hCoreUI/Sources/Views/GeneralDatePicker.swift
Projects/hGraphQL/Sources/Apollo Extensions/ApolloClient+Fetch.swift

GEN3211:  added processing payments

---

Projects/hGraphQL/Sources/HeadersInterceptor.swift

- Fixed [crash](https://app.datadoghq.eu/error-tracking?query=application.id%3A416e8fc0-c96a-4485-8c74-84412960a479%20env%3Aprod&fromUser=false&issue_states=open&issueId=18086d1c-e0c0-11ef-a206-da7ad0900005&refresh_mode=sliding&source=all&from_ts=1738672189721&to_ts=1738675789721&live=true)

Fixed chrash for missing access token

---

Projects/Contracts/Sources/View/ContractRow.swift

- Reported issue. Screen get extra horizontal since we have fixed size for tags. Adding Tags could fix this on more nicer way .

Fixed contract row spacing using TagKit

---

Projects/Addons/Sources/Service/Protocols/AddonsClient.swift
Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/hCore/Sources/DeepLink.swift

- Added support for the deep link

GEN-3225: Support travel addon deep link

---

Projects/EditCoInsured/Sources/View/EditCoInsured+modifier.swift
Projects/EditCoInsuredShared/Sources/Models/EditCoInsuredViewModel.swift
Projects/hCore/Sources/Helpers/GraphQLErrors+description.swift

- Added better handling of edit co insured errors
- different error message for graphsQLerrors cases

Added better handling of edit co insured error

---

Projects/MoveFlow/Sources/View/MovingFlowAddressScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowHouseScreen.swift
Projects/hCoreUI/Sources/hForm/hFloatingTextField.swift

Tha main reason for this is update of the localization. We have longer text now and we are switching all fields to medium
[Localize issue](https://www.notion.so/hedviginsurance/Addons-E2E-test-18fc3f71cb0a80a797f7e4bc3c85974b?p=18fc3f71cb0a810e9a43cb24b2015b16&pm=s)
+ changed move flow fields to medium

MovingFlowSize: Updated moving flow to medium size

---

Projects/ChangeTier/GraphQL/Octopus/ChangeTierCreateIntent.graphql
Projects/ChangeTier/Sources/Models/ChangeTierIntentModel.swift
Projects/ChangeTier/Sources/Service/DemoImplementation/ChangeTierClientDemo.swift
Projects/ChangeTier/Sources/Service/OctopusImplementation/ChangeTierClientOctopus.swift
Projects/ChangeTier/Sources/Views/ChangeTierViewModel.swift
Projects/ChangeTier/Sources/Views/CompareTierScreen.swift
Projects/ChangeTier/Sources/Views/EditDeductibleScreen.swift
Projects/MoveFlow/Sources/Service/OctopusImplementation/MoveFlowClientOctopus.swift

- Fixed issue with not showing proper previous price for change tier when we have addon in the current insurane

ChangeTier: Replaced premium with base premium

---

Projects/Profile/Sources/Views/Screens/DeleteAccount/DeleteAccountView.swift

Use deeplink instead of having open chat from the delete account bottom sheet

---

Projects/Contracts/Sources/ContractsNavigation.swift
Projects/TerminateContracts/Sources/Models/TerminateInsuranceViewModel.swift
Projects/TerminateContracts/Sources/Navigation/TerminationFlowNavigationViewModel.swift
Projects/TerminateContracts/Sources/Service/TerminateContractsService.swift
Projects/TerminateContracts/Sources/Views/TerminationSurveyScreen.swift

- Add termination client wrapper

Add termination service

---

Projects/App/Sources/AppDelegate.swift

- If we have presented modal, it will be not dismissed if the member get force logout

Fixed issue where force logout doesn't dismiss presented VCs

---

Projects/Addons/GraphQL/Octopus/UpsellTravelAddonOffer.graphql
Projects/Addons/Sources/Models/AddonLogInfo.swift
Projects/Addons/Sources/Models/AddonOffer.swift
Projects/Addons/Sources/Navigation/ChangeAddonNavigation.swift
Projects/Addons/Sources/Service/DemoImplementation/AddonsClientDemo.swift
Projects/Addons/Sources/Service/OctopusImplementation/AddonsClientOctopus.swift
Projects/Addons/Sources/Views/AddonProcessingScreen.swift
Projects/Addons/Sources/Views/AddonSelectInsuranceScreen.swift
Projects/Addons/Sources/Views/AddonSelectSubOptionScreen.swift
Projects/Addons/Sources/Views/ChangeAddonScreen.swift
Projects/Addons/Sources/Views/ChangeAddonSummaryScreen.swift
Projects/Addons/Sources/Views/ChangeAddonViewModel.swift
Projects/Addons/Sources/Views/ConfirmChangeAddonScreen.swift
Projects/App/Sources/DatadogLogger.swift
Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/Contracts/Sources/View/ContractTable.swift
Projects/TravelCertificate/Sources/Views/ListScreen.swift
Projects/hGraphQL/Sources/Log.swift

- Added logs for purchased action
- Added logs for upgraded action
Event can be checked [here](https://app.datadoghq.eu/rum/sessions?query=%40type%3Aaction%20%40application.id%3A416e8fc0-c96a-4485-8c74-84412960a479%20env%3Adev%20%40action.type%3Acustom&agg_m=count&agg_m_source=base&agg_t=count&cols=&fromUser=true&viz=stream&from_ts=1740043227362&to_ts=1740129627362&live=true).

Log purchased and upgraded addons event

---

Projects/App/Sources/Journeys/LoggedInNavigation.swift
Projects/Chat/Sources/Helpers/Message+UI.swift
Projects/Chat/Sources/Navigation/ChatNavigation.swift
Projects/Chat/Sources/Views/ChatInputView.swift
Projects/Chat/Sources/Views/ChatScreen.swift
Projects/Chat/Sources/Views/ChatScreenViewModel.swift
Projects/Chat/Sources/Views/MessageView.swift
Projects/Chat/Sources/Views/MessageViews/ActionView.swift
Projects/Chat/Sources/Views/MessageViews/LinkView.swift

- Refactoring and cleaning of chat to make it more readable

Chat refactoring and cleaning

---

Projects/hCoreUI/Sources/Toasts.swift

GEN-3347: Fix voice over for toasts

---

Projects/Forever/Sources/ChangeCodeView.swift
Projects/Forever/Sources/DiscountCodeSection.swift
Projects/Forever/Sources/Forever.swift
Projects/Forever/Sources/Navigation/ForeverNavigation.swift

Reworked forever VMs

---

Projects/Contracts/Sources/Stores/ContractState.swift
Projects/Contracts/Sources/View/ContractTable.swift
Projects/TravelCertificate/Sources/Views/ListScreen.swift

Moved addon config generation to one place

---

Projects/Payment/Sources/Models/PaymentData.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsDiscount.swift
Projects/Payment/Sources/Service/PaymentService/OctopusImplementation/PaymentData+octopus.swift

Added check for if referral

---

Projects/App/Sources/AppDelegate+Notifications.swift
Projects/App/Sources/Navigation/LoggedInNavigation.swift

- added new notification type
- handling of that notification type

GEN-3386: Added support for addon travel push notification type

---

Projects/App/Sources/Navigation/LoggedInNavigation.swift
Projects/Home/GraphQL/Octopus/HomeQuery.graphql
Projects/Home/Sources/HomeState.swift
Projects/Home/Sources/Screens/HomeBottomScrollView.swift
Projects/Home/Sources/Screens/HomeScreen.swift
Projects/Home/Sources/Service/DemoImplementation/HomeClientDemo.swift
Projects/Home/Sources/Service/OctopusImplementation/HomeClientOctopus.swift
Projects/Home/Sources/Service/Protocols/HomeClient.swift

- Fetch memberId from home instead of passing it

Fetch memberId from home instead of passing it

---

Projects/MoveFlow/Sources/Model/MoveConfigurationModel.swift
Projects/MoveFlow/Sources/Model/MoveQuotesModel.swift
Projects/MoveFlow/Sources/Model/MovingFlowModel.swift
Projects/MoveFlow/Sources/Navigation/MovingFlowNavigation.swift
Projects/MoveFlow/Sources/Service/DemoImplementation/MoveFlowClientDemo.swift
Projects/MoveFlow/Sources/Service/Navigation/MovingFlowNavigation.swift
Projects/MoveFlow/Sources/Service/OctopusImplementation/MoveFlowClientOctopus.swift
Projects/MoveFlow/Sources/Service/Protocols/MoveFlowClient.swift
Projects/MoveFlow/Sources/View/MovingFlowAddressScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowConfirmScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowHouseScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowHousingTypeScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowProcessingScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowSelectContractScreen.swift
Projects/MoveFlow/Sources/View/TypeOfBuildingPickerScreen.swift
Projects/hCoreUI/Sources/Activity/ActivityIndicatorView.swift

- Separate moving flow data into 2 models and some other refactoring

Refactor moving flow and separate into 2 models

---

Projects/ChangeTier/Sources/Views/CompareTierScreen.swift

- comparison screen order now depends from the response. Not from tiers that we injected into view model

Fixed comparison screen logic 

---

Projects/CrossSell/Sources/Store/CrossSellState.swift
Projects/CrossSell/Sources/View/CrossSellingStack.swift
Projects/CrossSell/Sources/View/CrossSellingUnseenCircle.swift
Projects/Home/Sources/Screens/HomeScreen.swift

- Removed view model
- Read data from store

Used store for crossSellingStack instead of view model

---

Projects/Contracts/Sources/Stores/ContractAction.swift
Projects/CrossSell/Sources/Store/CrossSellAction.swift
Projects/CrossSell/Sources/Store/CrossSellState.swift
Projects/CrossSell/Sources/Store/CrossSellStore.swift
Projects/CrossSell/Sources/View/CrossSellingStack.swift
Projects/Home/Sources/Screens/HomeScreen.swift

- Add cross sell store and store cross sells there

Add cross sell store

---

Projects/ChangeTier/Sources/Views/CompareTierScreen.swift
Projects/Chat/Sources/ChatStore.swift
Projects/Chat/Tests/MockData.swift
Projects/Chat/Tests/TestChatViewModelBanner.swift
Projects/Chat/Tests/TestChatViewModelFetchAndPreviousNewMessages.swift
Projects/Chat/Tests/TestChatViewModelFetchNewMessages.swift
Projects/Chat/Tests/TestChatViewModelFetchPreviousMessages.swift
Projects/Chat/Tests/TestChatViewModelIsConversationOpen.swift
Projects/Chat/Tests/TestChatViewModelLastDeliveredMessage.swift
Projects/Chat/Tests/TestChatViewModelSendMessage.swift
Projects/Chat/Tests/TestChatViewModelTitle.swift
Projects/Contracts/Tests/ContractTests.swift
Projects/Contracts/Tests/MockData.swift
Projects/Contracts/Tests/StoreTests/ContractStoreTests.swift
Projects/CrossSell/Tests/CrossSellTests.swift
Projects/CrossSell/Tests/MockData.swift
Projects/Home/Tests/HomeTests.swift
Projects/Home/Tests/MockData.swift
Projects/Payment/Tests/StoreTests/StoreDiscountsTests.swift
Projects/Payment/Tests/ViewModelTests/CampaignViewModelTests.swift
Projects/Payment/Tests/ViewModelTests/PaymentDetailsDiscountViewModelTests.swift

Updated tests

---

Projects/CrossSell/Tests/StoreTests/CrossSellStoreTests.swift

Add cross sell store tests

---

Projects/App/Sources/Service/OctopusClientsImplementation/ChatUploadFileClientOctopus.swift
Projects/App/Sources/Service/OctopusClientsImplementation/ConversationsClientOctopus.swift
Projects/App/Sources/Service/OctopusClientsImplementation/FetchClaimClientOctopus.swift
Projects/App/Sources/Service/OctopusClientsImplementation/FetchClaimDetailsClientOctopus.swift
Projects/Chat/Project.swift
Projects/Chat/Sources/Helpers/MessageType+Helpers.swift
Projects/Chat/Sources/Models/Conversation.swift
Projects/Chat/Sources/Models/Message.swift
Projects/Chat/Sources/Service/ChatService.swift
Projects/Chat/Sources/Service/Protocols/ChatUploadFileClient.swift
Projects/Chat/Sources/Service/Protocols/ConversationClient.swift
Projects/Chat/Sources/Views/ChatScreen.swift
Projects/Chat/Sources/Views/ChatScreenViewModel.swift
Projects/Claims/Sources/Service/Protocols/FetchClaimDetailsClient.swift

Removed hGraphQL from:
- chat
- claims
- claim details

Removed hGrapQL from chat, claims and claim details

---

Projects/App/Sources/Service/OctopusClientsImplementation/ChatUploadFileClientOctopus.swift
Projects/App/Sources/Service/OctopusClientsImplementation/ConversationsClientOctopus.swift
Projects/App/Sources/Service/OctopusClientsImplementation/CrossSellClientOctopus.swift
Projects/App/Sources/Service/OctopusClientsImplementation/FetchClaimClientOctopus.swift
Projects/App/Sources/Service/OctopusClientsImplementation/FetchClaimDetailsClientOctopus.swift
Projects/Chat/Project.swift
Projects/Chat/Sources/Helpers/MessageType+Helpers.swift
Projects/Chat/Sources/Models/Conversation.swift
Projects/Chat/Sources/Models/Message.swift
Projects/Chat/Sources/Service/ChatService.swift
Projects/Chat/Sources/Service/Protocols/ChatUploadFileClient.swift
Projects/Chat/Sources/Service/Protocols/ConversationClient.swift
Projects/Chat/Sources/Views/ChatScreen.swift
Projects/Chat/Sources/Views/ChatScreenViewModel.swift
Projects/Claims/Sources/Service/Protocols/FetchClaimDetailsClient.swift
Projects/CrossSell/Sources/Service/CrossSellService.swift
Projects/CrossSell/Sources/Store/CrossSellStore.swift

Remove hGraphQL from Cross sell

---

Projects/App/Sources/Service/OctopusClientsImplementation/ForeverClientOctopus.swift
Projects/Forever/Project.swift
Projects/Forever/Sources/ChangeCodeView.swift
Projects/Forever/Sources/Components/InivtationTable.swift
Projects/Forever/Sources/Components/PriceSectionView.swift
Projects/Forever/Sources/Forever.swift
Projects/Forever/Sources/Header.swift
Projects/hGraphQL/GraphQL/Octopus/Forever/MemberReferralnformation.graphql

- Removed hGraphQL from Forever module

GEN-3424: remove hGraphQL from forever

---

Projects/Contracts/Sources/View/ContractRow.swift
Projects/Home/Sources/Service/OctopusImplementation/HomeClientOctopus.swift

- Added card info when having pending contract
- Updated logic about home screen when we have only pending contracts
- Issue was reported [here](https://hedviginsurance.slack.com/archives/CPCUHMMJQ/p1741855953083179)

Fix issue with pending insurances

---

Projects/MoveFlow/Sources/Navigation/MovingFlowNavigation.swift
Projects/MoveFlow/Sources/View/MovingFlowSelectContractScreen.swift

Create itemPickerConfig on MovingFlowSelectContractScreen init

---

Projects/TravelCertificate/GraphQL/Octopus/TravelCertificateSpecifications.graphql
Projects/TravelCertificate/Sources/Models/TravelInsuranceContractSpecification.swift
Projects/TravelCertificate/Sources/Service/OctopusImplementation/TravelInsuranceClientOctopus.swift
Projects/TravelCertificate/Sources/TravelCertificateNavigation.swift
Projects/TravelCertificate/Sources/Views/ListScreen.swift
Projects/TravelCertificate/Sources/Views/StartDateScreen.swift
Projects/TravelCertificate/Sources/Views/TravelCertificateProcessingScreen.swift
Projects/TravelCertificate/Sources/Views/TravelCertificateSelectInsuranceScreen.swift
Projects/TravelCertificate/Sources/Views/WhoIsTravelingScreen.swift

Add subtitle to TravelCertificateSelectInsuranceScreen

---

Projects/App/Sources/Navigation/LoggedInNavigation.swift
Projects/CrossSell/Sources/View/CrossSellingScreen.swift

Added this because we need configs for it to work

Added logic to handle contract ids

---

Projects/Payment/Sources/Screens/PaymentDiscounts/PaymentsDiscountsView.swift
Projects/hCore/Sources/FeatureFlags/FeatureFlagOctopus.swift
Projects/hCore/Sources/FeatureFlags/FeatureFlagsDemo.swift
Projects/hCore/Sources/FeatureFlags/FeatureFlagsProtocol.swift

- Add feature flag for redeem code

GEN-3483: add redeem code feature flag

---

Projects/Claims/Sources/Models/ClaimModel.swift
Projects/Claims/Sources/Service/OctopusImplementation/FetchClaimClientOctopus.swift
Projects/Claims/Sources/Views/ClaimDetailView.swift
Projects/Claims/Sources/Views/ClaimStatus.swift
Projects/Claims/Sources/Views/ClaimStatusBar.swift
Projects/Claims/Sources/Views/ContactChatView.swift

- Having stronger relation with graphQL response for outcome and status
- Making outcome optional
- Removed outcome types that will never be present

Updated claim status + outcome to represent values that we actually have

---

Projects/Claims/GraphQL/Octopus/Claims.graphql
Projects/Claims/Sources/Models/ClaimModel.swift
Projects/Claims/Sources/Service/DemoImplementation/FetchClaimDetailsClientDemo.swift
Projects/Claims/Sources/Service/OctopusImplementation/FetchClaimClientOctopus.swift
Projects/Claims/Sources/Views/ClaimDetailView.swift
Projects/Claims/Sources/Views/ClaimStatus.swift

Add info text handling for closed claim

---

Projects/App/Sources/Screens/Impersonation/ImpersonationSettings.swift
Projects/Claims/Sources/Views/ClaimDetailView.swift
Projects/CrossSell/Sources/View/CrossSellingStack.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsView.swift
Projects/Payment/Sources/Screens/PaymentDiscounts/PaymentsDiscountsView.swift
Projects/Payment/Sources/Screens/PaymentsHistoryView.swift
Projects/SubmitClaim/Sources/Views/Checkout/SubmitClaimCheckoutScreen.swift
Projects/SubmitClaim/Sources/Views/SummaryInfo/SubmitClaimSummaryScreen.swift
Projects/hCoreUI/Sources/ItemPickerScreen.swift
Projects/hCoreUI/Sources/hForm/hSection.swift

- Refactored header inside hSection to take in arguments and create a generic title view instead
- Removed footer inside hSection since since it was only used for impersonation view

hSetion title refactoring

---

Projects/Claims/GraphQL/Octopus/Claims.graphql
Projects/Claims/Sources/Models/ClaimModel.swift
Projects/Claims/Sources/Service/DemoImplementation/FetchClaimDetailsClientDemo.swift
Projects/Claims/Sources/Service/OctopusImplementation/FetchClaimClientOctopus.swift
Projects/Claims/Sources/Views/ClaimDetailView.swift
Projects/Claims/Sources/Views/ClaimStatus.swift
Projects/Claims/Tests/FetchClaimsTests.swift
Projects/Claims/Tests/MockData.swift

- Removed deprecated properties
- Added new displayItems list from BE 
- Updated tests accordingly

GEN-3487: Added claim details list from BE

---

Projects/Addons/Sources/Models/AddonOffer.swift
Projects/Addons/Sources/Navigation/ChangeAddonNavigation.swift
Projects/App/Sources/Navigation/LoggedInNavigation.swift
Projects/CrossSell/GraphQL/Octopus/UpsellTravelAddonBannerCrossSell.graphql
Projects/CrossSell/Project.swift
Projects/CrossSell/Sources/Service/DemoImplementation/CrossSellClientDemo.swift
Projects/CrossSell/Sources/Service/OctopusImplementation/CrossSellClientOctopus.swift
Projects/CrossSell/Sources/Service/Protocols/CrossSellClient.swift
Projects/CrossSell/Sources/Store/CrossSellAction.swift
Projects/CrossSell/Sources/Store/CrossSellState.swift
Projects/CrossSell/Sources/Store/CrossSellStore.swift
Projects/CrossSell/Sources/View/CrossSellingItem.swift
Projects/CrossSell/Sources/View/CrossSellingScreen.swift
Projects/CrossSell/Sources/View/CrossSellingStack.swift
Projects/CrossSell/Tests/CrossSellTests.swift
Projects/CrossSell/Tests/MockData.swift
Projects/CrossSell/Tests/StoreTests/CrossSellStoreTests.swift
Projects/hCoreUI/Sources/Router/Router.swift

- [Figma](https://www.figma.com/design/cPsNUYT5LvPTKSmRhCFoXL/Claim-Closed-Flow?node-id=175-29001&t=pwfPDkANEDEAWMC6-0)
- Also created generic title view for title + subtitle that can be reused

GEN-3460: Updated cross sell screen

---

Projects/App/Sources/Service/OctopusClientsImplementation/TerminateContractsClientOctopus.swift
Projects/TerminateContracts/Sources/Models/TerminationFlowDateNextStepModel.swift
Projects/TerminateContracts/Sources/Models/TerminationFlowDeletionNextModel.swift
Projects/TerminateContracts/Sources/Models/TerminationFlowFailedNextModel.swift
Projects/TerminateContracts/Sources/Models/TerminationFlowStartNextStepModel.swift
Projects/TerminateContracts/Sources/Models/TerminationFlowSuccessNextModel.swift
Projects/TerminateContracts/Sources/Models/TerminationFlowSurveyStepModel.swift
Projects/TerminateContracts/Sources/Service/Protocols/TerminateContractsClient.swift
Projects/TerminateContracts/Sources/Service/TerminateContractsService.swift
Projects/TerminateContracts/Sources/Views/ReusableComponents.swift
Projects/TerminateContracts/Sources/Views/SetTerminationDate.swift

GEN-3428: Remove hGraphQL from terminate contract flow

---

Projects/App/Sources/Service/OctopusClientsImplementation/MoveFlowClientOctopus.swift
Projects/MoveFlow/Sources/Model/MoveConfigurationModel.swift
Projects/MoveFlow/Sources/Model/MoveQuotesModel.swift
Projects/MoveFlow/Sources/Navigation/MovingFlowNavigation.swift
Projects/MoveFlow/Sources/Service/Protocols/MoveFlowClient.swift
Projects/MoveFlow/Sources/View/MovingFlowAddExtraBuildingScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowAddressScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowConfirmScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowHouseScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowHousingTypeScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowProcessingScreen.swift
Projects/MoveFlow/Sources/View/TypeOfBuildingPickerScreen.swift
Projects/MoveFlow/Tests/ViewModelTests/AddressInputModelTests.swift
Projects/MoveFlow/Tests/ViewModelTests/HouseInformationInputModelTests.swift
Projects/MoveFlow/Tests/ViewModelTests/MovingFlowAddExtraBuildingViewModelTests.swift
Projects/MoveFlow/Tests/ViewModelTests/MovingFlowHousingTypeViewModelTests.swift

GEN-3427: Removed hGraphQL from move flow

---

Projects/App/Sources/Navigation/LoggedInNavigation.swift
Projects/CrossSell/Sources/View/CrossSellingScreen.swift
Projects/Home/Sources/Navigation/HomeNavigation.swift
Projects/Home/Sources/Screens/HomeScreen.swift

- Add logging for claim id on cross sell screen

add logging for claim id in cross sell

---

Projects/Addons/Sources/Views/AddonSelectSubOptionScreen.swift
Projects/ChangeTier/Sources/Views/EditDeductibleScreen.swift
Projects/ChangeTier/Sources/Views/EditTierScreen.swift
Projects/Chat/Sources/Views/ChatScreen.swift
Projects/Chat/Sources/Views/ChatScreenViewModel.swift
Projects/Payment/Sources/Helpers/PaymentData+titleView.swift
Projects/Payment/Sources/Navigation/PaymentNavigation.swift
Projects/hCoreUI/Sources/Router/Router.swift

- Refactor title view since all title views use the same design

Refactor title view

---

Projects/App/Sources/Navigation/LoggedInNavigation.swift
Projects/Home/GraphQL/Octopus/MemberActions.graphql
Projects/Home/Sources/Models/QuickAction.swift
Projects/Home/Sources/Service/OctopusImplementation/HomeClientOctopus.swift
Projects/SubmitClaim/GraphQL/Octopus/StartClaimsFlow.graphql
Projects/SubmitClaim/Sources/Models/FlowClaimDeflectStepModel.swift
Projects/SubmitClaim/Sources/Views/Deflect/SubmitClaimDeflectScreen.swift
Projects/SubmitClaim/Sources/Views/SubViews/ClaimContactCard.swift
Projects/hCore/Sources/Models/Deflect.swift

Fetch partner image height from BE

---

Projects/App/Sources/Navigation/LoggedInNavigation.swift
Projects/Claims/Sources/Models/ClaimModel.swift
Projects/CrossSell/Sources/View/CrossSellingScreen.swift
Projects/Home/Sources/Navigation/HomeNavigation.swift
Projects/Home/Sources/Screens/HomeScreen.swift

- Added cross sale type
- Updated claim info for cross sale log

Updated logs for X-sell

---

Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsDiscount.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsView.swift
Projects/Payment/Sources/Screens/PaymentDiscounts/PaymentsDiscountsView.swift

Removed info button on discounts if add campaign is disabled

---

Projects/MoveFlow/Sources/Model/MoveConfigurationModel.swift
Projects/MoveFlow/Sources/Navigation/MovingFlowNavigation.swift
Projects/hCoreUI/Sources/Activity/ActivityIndicatorView.swift

Updated error screen for moving flow

---

Projects/SubmitClaim/GraphQL/Octopus/StartClaimsFlow.graphql
Projects/SubmitClaim/Sources/Models/FlowClaimSummaryStepModel.swift
Projects/SubmitClaim/Sources/Service/OctopusImplementation/SubmitClaimClientOctopus.swift
Projects/SubmitClaim/Sources/Views/SummaryInfo/SubmitClaimSummaryScreen.swift

- added subject of claim to the summary
- added details of claim to the summary

GEN-3520: Added subject of claim and details

---

Projects/Home/Sources/Navigation/HomeNavigation.swift

Always show cross sell after success flow

---

Projects/InsuranceEvidence/Example/Resources/Assets.xcassets/AppIcon.appiconset/contents.json
Projects/InsuranceEvidence/Example/Resources/Assets.xcassets/contents.json
Projects/InsuranceEvidence/Example/Sources/AppDelegate.swift
Projects/InsuranceEvidence/GraphQL/Octopus/InsuranceEvidenceCanCreate.graphql
Projects/InsuranceEvidence/GraphQL/Octopus/InsuranceEvidenceCreate.graphql
Projects/InsuranceEvidence/GraphQL/Octopus/InsuranceEvidenceInitialData.graphql
Projects/InsuranceEvidence/Project.swift
Projects/InsuranceEvidence/Resources/Assets.xcassets/contents.json
Projects/InsuranceEvidence/Sources/Models/InsuranceEvidence.swift
Projects/InsuranceEvidence/Sources/Models/InsuranceEvidenceInitialData.swift
Projects/InsuranceEvidence/Sources/Models/InsuranceEvidenceInput.swift
Projects/InsuranceEvidence/Sources/Service/Client/InsuranceEvidenceClient.swift
Projects/InsuranceEvidence/Sources/Service/Client/InsuranceEvidenceClientDemo.swift
Projects/InsuranceEvidence/Sources/Service/Client/InsuranceEvidenceClientOctopus.swift
Projects/InsuranceEvidence/Sources/Service/InsuranceEvidenceService.swift

- added basic project
- added end points

GEN-3541: Insurance Evidence - Added project + octopus implementation

---

Projects/Chat/Sources/Views/ChatInputView.swift
Projects/Chat/Sources/Views/ImagesView.swift
Projects/Claims/Sources/Models/ImagePicker.swift
Projects/hCore/Sources/DateFormat/Date+CurrentMilliseconds.swift
Projects/hCore/Sources/DateFormat/Date+LocalDateString.swift

Updated names of the files when uploading

---

Projects/App/Sources/AppDelegate+Notifications.swift
Projects/App/Sources/Navigation/LoggedInNavigation.swift
Projects/hCore/Sources/DeepLink.swift

- Deep link `insurance-evidence` added
- Push notification `INSURANCE_EVIDENCE` added

GEN-3605: Deep link and push notification for insurance evidence

---

Projects/App/Sources/AppDelegate+Notifications.swift
Projects/App/Sources/Navigation/LoggedInNavigation.swift

Add push notification for travel certificate

---

Projects/App/Sources/Screens/ClaimsScreen/Screens/HonestyPledge.swift
Projects/Forever/Sources/Components/PieChart/PieChartView.swift
Projects/hCoreUI/Sources/ToolbarButtonView/ToolbarButtonView.swift
Projects/hCoreUI/Sources/ToolbarButtonView/TooltipView.swift
Projects/hCoreUI/Sources/Views/Animation+styles.swift

- Better transition for tooltip - dynamic position calculate for arrow and anchor
- Fixed tooltip leading position
| From | To |
|--------|--------|
| ![Simulator Screenshot - iPhone 16 - 2025-04-23 at 10 27 21](https://github.com/user-attachments/assets/096a812e-9e36-4ddb-9953-387b9adc7cc8) | ![Simulator Screenshot - iPhone 16 - 2025-04-23 at 10 33 13](https://github.com/user-attachments/assets/7b179aba-94cf-45ad-a043-5de2cd0f736f) |

Tooltip appearance + fix for leading

---

Projects/TravelCertificate/Sources/Views/TravelCertificateProcessingScreen.swift

Changed successViewTitle text for travel certificate

---

Projects/App/Config/Production/Info.plist
Projects/App/Config/Test/Info.plist
Projects/Market/Sources/Market.swift
Projects/MoveFlow/Sources/View/MovingFlowHouseScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowHousingTypeScreen.swift
Projects/hCore/Sources/Localization.swift
Projects/hCoreUI/Sources/Localization.Locale+Icon.swift
scripts/translations.sh

- Remove danish and norwegian support
ToDo:
- after merge, when submitting new release, remove danish and norwegian

Remove danish and norwegian support

---

Projects/Campaign/Sources/Navigation/CampaignNavigation.swift
Projects/Campaign/Sources/Service/CampaignClient.swift
Projects/Campaign/Sources/Service/DemoImplementation/CampaignClientDemo.swift
Projects/Campaign/Sources/Service/OctopusImplementation/CampaignClientOctopus.swift
Projects/Campaign/Sources/Service/OctopusImplementation/PaymentDiscountData+octopus.swift
Projects/Campaign/Sources/Store/CampaignAction.swift
Projects/Campaign/Sources/Store/CampaignStore.swift
Projects/Campaign/Sources/Views/AddCampaingCodeView.swift
Projects/Campaign/Sources/Views/DeleteCampaignView.swift
Projects/Campaign/Sources/Views/DiscountsView.swift
Projects/Campaign/Tests/CampaignMockData.swift
Projects/Payment/GraphQL/Octopus/PaymentData.graphql
Projects/Payment/Sources/Models/PaymentData.swift
Projects/Payment/Sources/Navigation/PaymentNavigation.swift
Projects/Payment/Sources/PaymentStore.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsContractDetails.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsView.swift
Projects/Payment/Sources/Service/DemoImplementation/PaymentClientDemo.swift
Projects/Payment/Sources/Service/OctopusImplementation/PaymentData+octopus.swift
Projects/Payment/Sources/Service/OctopusImplementation/PaymentHistoryData+octopus.swift
Projects/Payment/Sources/Service/Protocols/PaymentClient.swift

- Removed unused properties from payments
- reworked campaign module a little

Removed unused properties + little cleanup

---

Projects/Campaign/GraphQL/Octopus/DiscountsData.graphql
Projects/Campaign/Sources/Models/PaymentDiscountsData.swift
Projects/Campaign/Sources/Service/DemoImplementation/CampaignClientDemo.swift
Projects/Campaign/Sources/Service/OctopusImplementation/PaymentDiscountData+octopus.swift
Projects/Campaign/Sources/Views/DiscountsView.swift
Projects/MoveFlow/Sources/View/MovingFlowHouseScreen.swift
Projects/hCore/Sources/String+join.swift

- Set code/name in referrals properly
- Set display name properly
- [Figma](https://www.figma.com/design/zItETkT4mu5ANVDYED5gEm/UX-Improvements--Small-Projects-?node-id=887-17130&t=M8CgYINcicb3id9k-0)

GEN-3666: Campaign updates

---

Projects/TerminateContracts/Sources/Navigation/TerminationFlowNavigationViewModel.swift
Projects/hCoreUI/Sources/InfoView/InfoView.swift

Issue was that its not working if we place "HolderInfoView" in navigation using .toolbar
https://github.com/user-attachments/assets/09a951ff-90c8-4599-910c-285a18aeeb17
This should fix it
https://github.com/user-attachments/assets/c0848fa4-9452-441e-90f7-e0c70315a37c

(fix) Navigation info button

---

Projects/hCore/Sources/Localization.swift
scripts/translations.sh
swiftgen.yml
swiftgen/localization.stencil

Updated code to use en instead of en-SV

---

Projects/SubmitClaim/Sources/Views/SingleItem/PriceInputScreen.swift
Projects/hCoreUI/Sources/hButton/ReusableButtons/hSaveButton.swift
Projects/hCoreUI/Sources/hForm/hDatePickerField.swift
Projects/hCoreUI/Sources/hForm/hFieldBackground.swift
Projects/hCoreUI/Sources/hForm/hFloatingTextField.swift

- https://reports.useit.se/hedvig-iosapp-may2025/problems/resize-text-issues-with-input-fields-in-the-app/

GEN-3733: Fix dynamic font for larger fonts in input fields

---

Projects/hCoreUI/Sources/Views/InfoCard/InfoCardScrollView.swift
Projects/hCoreUI/Sources/Views/ScrollableSegmentedView.swift

- Updated scrolling logic for both scroll view with and without pager
- TODO: merge scrolls into one component
[Notion](https://www.notion.so/hedviginsurance/Scrolling-animation-is-laggy-and-doesn-t-stick-1f3c3f71cb0a808693ecfc34b0b6cebc)

Added additional layer for smoother scrolling exp

---

Projects/App/Sources/Service/OctopusClientsImplementation/CrossSellClientOctopus.swift
Projects/CrossSell/Sources/Models/CrossSellModels.swift

Since we added new cross-sell types, we need to know how to handle them

Expanded Cross sell types with new ones

---

Projects/hCoreUI/Sources/CommonAnimations/Rotate.swift
Projects/hCoreUI/Sources/ToolbarButtonView/ToolbarButtonView.swift
Projects/hCoreUI/Sources/ToolbarButtonView/TooltipType.swift

- added rotation animation
This is not the way we want to handle it tbh, but this part require some more work to make it nicer. #legacy

Feature/cross sell/navigation button animation

---

Projects/CrossSell/Sources/Store/CrossSellAction.swift
Projects/CrossSell/Sources/Store/CrossSellState.swift
Projects/CrossSell/Sources/Store/CrossSellStore.swift
Projects/Home/Sources/Navigation/HomeNavigation.swift

Reset new offer badge

---

Projects/hCoreUI/Sources/PresentationStyle+Detented.swift

- Make custom blurred background based on the background color in figma
- [Notion link](https://www.notion.so/hedviginsurance/Opaque-frosting-bottom-sheet-modal-1f3c3f71cb0a801eb44ddfae2eb401ca)

Make custom blurred background

---

Projects/Profile/Sources/Views/Screens/AppInfo/AppInfoView.swift
Projects/hCoreUI/Sources/hForm/hRow.swift

Fixed issue with accessibility position on App Info view.
| Before | After |
|--------|--------|
| ![Simulator Screenshot - iPhone 16 - 2025-06-23 at 10 18 22](https://github.com/user-attachments/assets/466e0ba0-54a1-42ce-9943-ad9fd329ce44) | ![Simulator Screenshot - iPhone 16 - 2025-06-23 at 10 19 24](https://github.com/user-attachments/assets/cf5aef58-d13b-455b-ae0b-c4571b56bca0) |

Change content position of hRow

---

Projects/Claims/Sources/Views/ClaimStatusBar.swift
Projects/Claims/Sources/Views/ClaimStatusCard.swift

Fixed for large font size
| Before | After |
|--------|--------|
| ![Simulator Screenshot - iPhone 16 - 2025-06-23 at 10 38 52](https://github.com/user-attachments/assets/1038e8c6-8d3c-4630-86f1-a6d7a9bff972) | ![Simulator Screenshot - iPhone 16 - 2025-06-23 at 10 35 31](https://github.com/user-attachments/assets/c03ca4dc-efbd-48b0-8e83-8091d793c620) |

Claim card accessibility fixes

---

Projects/CrossSell/Sources/View/Components/CrossSellButtonComponent.swift
Projects/CrossSell/Sources/View/CrossSellingCentered.swift
Projects/CrossSell/Sources/View/CrossSellingModal.swift
Projects/hCoreUI/Sources/VCModifier.swift

- Dismiss cross sell on recommended url click

Dismiss cross sell on url clicked

---

Projects/App/Sources/Service/OctopusClientsImplementation/MoveFlowClientOctopus.swift
Projects/MoveFlow/Sources/Model/MoveConfigurationModel.swift
Projects/MoveFlow/Sources/View/MovingFlowAddressScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowHouseScreen.swift
Projects/MoveFlow/Sources/View/MovingFlowHousingTypeScreen.swift
Projects/hGraphQL/GraphQL/Octopus/MoveFlow/MoveIntentCreate.graphql

Remove info box for moving flow

GEN-3917: Remove info box for moving flow

---

LocalModules/Environment/Sources/Environment/Environment.swift
Projects/App/Config/Production/Hedvig.entitlements
Projects/App/Config/Test/Ugglan.entitlements

- Added link.dev.hedvigit.com on stage handling
- Added link.hedvig.com on prod handling

GEN-3928: link deeplinks handling

---

Projects/App/Sources/Service/OctopusClientsImplementation/TerminateContractsClientOctopus.swift
Projects/TerminateContracts/Sources/Models/TerminationFlowDateNextStepModel.swift
Projects/TerminateContracts/Sources/Views/TerminationSummaryScreen.swift
Projects/TerminateContracts/Tests/MockData.swift
Projects/TerminateContracts/Tests/TerminateContractsTests.swift
Projects/hCoreUI/Sources/Toasts.swift
Projects/hCoreUI/Sources/Views/NotificationStyle.swift
Projects/hGraphQL/GraphQL/Octopus/TerminiateContracts/TerminationStartFlow.graphql

- Added info on termination flow
- Updated toast image colour based on the type
Waiting for [odyssey](https://github.com/HedvigInsurance/odyssey/pull/691) to be released/tested

GEN-3914:Feature/bundle discount/gen 3914 termination flow info

---

Projects/App/Sources/Service/OctopusClientsImplementation/CrossSellClientOctopus.swift
Projects/CrossSell/Sources/Service/CrossSellClient.swift
Projects/EditCoInsuredShared/Sources/Models/EditCoInsuredViewModel.swift

- Remove cross sell trigger after co-insured flow

Remove cross sell trigger after co-insured flow

---

Projects/App/Sources/Service/OctopusClientsImplementation/AuthenticationClientAuthLib.swift
Projects/Authentication/Sources/Service/AuthenticationClient.swift
README.md
Tuist/ProjectDescriptionHelpers/Project+DependenciesTemplate.swift
scripts/post-build-action.sh

Reverts HedvigInsurance/ugglan#1935

Revert "Migrate from authlib to umbrella"

---

Projects/App/Sources/Service/OctopusClientsImplementation/MoveFlowClientOctopus.swift

- Waiting for schema to be pushed to prod

Remove deprecated apiVersion field

---

Projects/hCoreUI/Sources/MarkdownTextView.swift

Fixed issue reported multiple times about chat messages, but the latest one is [here](https://hedviginsurance.slack.com/archives/CPCUHMMJQ/p1753101998003709).

Fixed cut off messages in the chat

---

Projects/App/Config/Production/Info.plist
Projects/App/Config/Test/Info.plist
Projects/App/Sources/Service/OctopusClientsImplementation/MoveFlowClientOctopus.swift
Projects/NotificationService/Info.plist
Projects/Profile/Sources/Views/Screens/AppInfo/AppInfoView.swift
Projects/hCoreUI/Sources/Views/EditContractScreen.swift
Projects/hGraphQL/GraphQL/Octopus/MoveFlow/MoveIntentCreate.graphql

GEN-3976:Added moving flow graphQL updates

---

ci_scripts/ci_post_clone.sh
ci_scripts/ci_post_xcodebuild.sh

- upload DSYM to datadog on release CI
- tested [here](https://appstoreconnect.apple.com/teams/37c6b82e-93ea-4a0d-a3fb-4056a2ff6b92/apps/1303668531/ci/builds/544d3e1f-3c92-4f65-afec-a61bf86400ba/action/bc750963-5efe-4d6f-aa0c-8d32b8adde44/logs)

Upload dsym on release ci

---

Projects/hCoreUI/Sources/hButton/hButton.swift
Projects/hCoreUI/Sources/hButton/hButtonStyle/hButtonStyle.swift

- Since we introduced new button style with border for summary card
- [Design here](https://www.figma.com/design/zItETkT4mu5ANVDYED5gEm/UX-Improvements--Small-Projects-?node-id=1649-2934&m=dev)

add option to add border around button

---

Projects/hCoreUI/Sources/StatusCard.swift

- Add option to have white background and shadow to match new design requirements
- [New design](https://www.figma.com/design/zItETkT4mu5ANVDYED5gEm/UX-Improvements--Small-Projects-?node-id=1649-2934&m=dev)

Status card white background + shadow

---

Projects/Contracts/Sources/ContractsNavigation.swift
Projects/Contracts/Sources/View/ContractInformation.swift
Projects/Contracts/Sources/View/UpcomingChangesScreen.swift

- Display date on format "dd mm yyyy" instead of "yyyy-mm-dd"
- [Commented here from test session ](https://www.notion.so/hedviginsurance/Upcoming-changes-Price-displayed-incorrectly-pic-in-OPEN-263c3f71cb0a81628363c28bca3147e9)

display date format fix

---

Projects/App/Sources/Service/OctopusClientsImplementation/ContractsClientOctopus.swift
Projects/ChangeTier/Sources/Views/ChangeTierLandingScreen.swift
Projects/Contracts/Sources/ContractsNavigation.swift
Projects/Contracts/Sources/Models/ContractModels.swift
Projects/Contracts/Sources/Service/DemoImplementation/ContractsClientDemo.swift
Projects/Contracts/Sources/View/ContractInformation.swift
Projects/Contracts/Sources/View/UpcomingChangesScreen.swift
Projects/Contracts/Tests/StoreTests/ContractStoreTests.swift
Projects/hGraphQL/GraphQL/Octopus/SharedFragments/AgreementFragment.graphql

Removed view certificate after edit co insured
Added view certificate in upcoming changes

Insurance details -  view certificate

---

Projects/Addons/Sources/Models/AddonOffer.swift
Projects/Addons/Sources/Service/DemoImplementation/AddonsClientDemo.swift
Projects/Addons/Sources/Views/AddonSelectSubOptionScreen.swift
Projects/Addons/Sources/Views/ChangeAddonSummaryScreen.swift
Projects/Addons/Sources/Views/ChangeAddonViewModel.swift
Projects/App/Sources/Service/OctopusClientsImplementation/AddonsClientOctopus.swift
Projects/App/Sources/Service/OctopusClientsImplementation/ContractsClientOctopus.swift
Projects/Contracts/Sources/Models/ContractModels.swift
Projects/Contracts/Sources/Service/DemoImplementation/ContractsClientDemo.swift
Projects/Contracts/Sources/View/Components/ItemCostView.swift
Projects/Contracts/Sources/View/UpcomingChangesScreen.swift
Projects/hCore/Sources/Models/ItemCost.swift
Projects/hCore/Sources/Models/Premium.swift
Projects/hCoreUI/Sources/Views/QuoteSummaryScreen/QuoteSummaryScreen.swift
Projects/hCoreUI/Sources/Views/QuoteSummaryScreen/QuoteSummaryViewModel.swift
Projects/hGraphQL/GraphQL/Octopus/Addons/UpsellTravelAddonOffer.graphql

- Graphql api integration
- Added displayNameLong as costBreakdown items in summary screen with prices

GEN-4170: Addon Graphql API Integration

---

Projects/App/Sources/Service/OctopusClientsImplementation/CampaignsClientOctopus.swift
Projects/App/Sources/Service/OctopusClientsImplementation/PaymentsClientOctopus.swift
Projects/Campaign/Sources/Models/PaymentDiscountsData.swift
Projects/Campaign/Sources/Service/DemoImplementation/CampaignClientDemo.swift
Projects/Campaign/Sources/Views/DiscountDetailView.swift
Projects/Campaign/Sources/Views/DiscountsView.swift
Projects/Campaign/Tests/CampaignMockData.swift
Projects/Campaign/Tests/StoreTests/StoreDiscountsTests.swift
Projects/Campaign/Tests/ViewModelTests/PaymentDetailsDiscountViewModelTests.swift
Projects/Payment/Sources/Models/PaymentData.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsContractDetails.swift
Projects/Payment/Sources/Screens/PaymentDetails/PaymentDetailsView.swift
Projects/Payment/Sources/Service/Protocols/PaymentClientDemo.swift
Projects/Payment/Tests/PaymentMockData.swift
Projects/Payment/Tests/ServiceTests/PaymentServiceTests.swift
Projects/Payment/Tests/StoreTests/StoreLoadTests.swift
Projects/hGraphQL/GraphQL/Octopus/Campaign/DiscountsData.graphql

- Updated model
- Updated graphql
- Adjusted views to updated model
Affecting discounts in both discounts and payments details
Design: [Figma](https://www.figma.com/design/bgQsRTbBnpYRzbhee97ilh/Bundle-Discounts?node-id=511-3173&m=dev)

GEN-4002: Payments and discounts graphql implementation

---

ci_scripts/ci_post_clone.sh

Replace brew with miso for getting tuist for xcode cloud

---

Projects/App/Sources/Service/OctopusClientsImplementation/ConversationsClientOctopus.swift
Projects/Chat/Sources/Helpers/Message+Timestamp.swift
Projects/Chat/Sources/Helpers/Message+UI.swift
Projects/Chat/Sources/Models/Message.swift
Projects/Chat/Sources/Views/ChatScreen.swift

- [Figma](https://www.figma.com/design/c65DTS6Qxzk9XAlUc0tH7z/Service-AI-Bot?node-id=270-13464&m=dev)
- Change 2

GEN-4254: Update time stamp string for automated message

---

Projects/Chat/Sources/Views/ChatScreen.swift
Projects/hCoreUI/Sources/Views/NotificationStyle.swift
Projects/hCoreUI/Sources/hColor/hColor.swift

- Add escalation banner
- Skipped colorful border
- [Figma](https://www.figma.com/design/c65DTS6Qxzk9XAlUc0tH7z/Service-AI-Bot?node-id=270-13420&m=dev)

add escalation banner

---

Projects/hGraphQL/Sources/ApolloClient.swift
Projects/hGraphQL/Sources/HeadersInterceptor.swift
Projects/hGraphQL/Sources/NetworkInterceptorProvider.swift

- added new hedvig app version header
- reworked how we set them

Added Hedvig-app-version + reworked headers

---

Projects/CrossSell/Sources/View/Components/CrossSellDiscountProgressComponent.swift

- Added animation for potential BD discount
TODO: check accessibility on the main branch
- Blocker

GEN-4314: Animate potential discount in cross sell
